[package]
name = "pl-model"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
live-tests = []

[dependencies]
base64 = { workspace = true }
image = { workspace = true }
pl-core = { workspace = true }
sha2 = { workspace = true }
pl-protocol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-tungstenite = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true, features = ["multipart"] }
eventsource-stream = { workspace = true }

[dev-dependencies]
pl-provider-fixture = { workspace = true }
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
