[package]
name = "pl-model"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
live-tests = []

[dependencies]
pl-protocol = { workspace = true }
pl-trace = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bitflags = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
async-openai = { workspace = true }
secrecy = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[[test]]
name = "deepseek_live"
path = "tests/deepseek_live.rs"
required-features = ["live-tests"]

[[test]]
name = "openai_live"
path = "tests/openai_live.rs"
required-features = ["live-tests"]

[[test]]
name = "zhipu_live"
path = "tests/zhipu_live.rs"
required-features = ["live-tests"]
