import type { ProviderTemplateRecord } from "../types";

export const previewTemplates: ProviderTemplateRecord[] = [
  {
    id: "deepseek",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com",
    defaultModel: "deepseek-v4-flash",
    wireApi: "chat",
    defaultModels: [
      {
        slug: "deepseek-v4-flash",
        displayName: "DeepSeek V4 Flash",
        description: "DeepSeek fast reasoning model with thinking mode.",
        contextWindow: 1_000_000,
        maxContextWindow: 1_000_000,
        maxOutputTokens: 384_000,
        reasoningEfforts: ["high", "max"],
        capabilities: ["streaming", "function_calling", "parallel_tool_calls", "reasoning"],
        inputModalities: ["text"],
        truncationMode: "tokens",
        truncationLimit: 10_000,
      },
      {
        slug: "deepseek-v4-pro",
        displayName: "DeepSeek V4 Pro",
        description: "DeepSeek flagship reasoning model with thinking mode.",
        contextWindow: 1_000_000,
        maxContextWindow: 1_000_000,
        maxOutputTokens: 384_000,
        reasoningEfforts: ["high", "max"],
        capabilities: ["streaming", "function_calling", "parallel_tool_calls", "reasoning"],
        inputModalities: ["text"],
        truncationMode: "tokens",
        truncationLimit: 10_000,
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-4.1",
    wireApi: "responses",
    defaultModels: [
      {
        slug: "gpt-4.1",
        displayName: "GPT-4.1",
        contextWindow: 1_050_000,
        maxContextWindow: 1_050_000,
        maxOutputTokens: 128_000,
        reasoningEfforts: ["medium", "high"],
        capabilities: [
          "streaming",
          "function_calling",
          "vision",
          "parallel_tool_calls",
          "reasoning",
          "web_search",
        ],
        inputModalities: ["text", "image"],
        truncationMode: "tokens",
        truncationLimit: 10_000,
      },
      {
        slug: "o4-mini",
        displayName: "o4 mini",
        contextWindow: 400_000,
        maxContextWindow: 400_000,
        maxOutputTokens: 128_000,
        reasoningEfforts: ["medium"],
        capabilities: [
          "streaming",
          "function_calling",
          "vision",
          "parallel_tool_calls",
          "reasoning",
          "web_search",
        ],
        inputModalities: ["text", "image"],
        truncationMode: "tokens",
        truncationLimit: 10_000,
      },
    ],
  },
];
