import type { ProviderTemplateRecord } from "../types";

function zhipuTextModel(
  slug: string,
  displayName: string,
  description: string,
  contextWindow: number,
  maxOutputTokens: number,
) {
  return {
    slug,
    displayName,
    description,
    contextWindow,
    maxContextWindow: contextWindow,
    maxOutputTokens,
    reasoningEfforts: ["enabled", "none"],
    capabilities: ["streaming", "function_calling", "parallel_tool_calls", "reasoning"],
    inputModalities: ["text"],
    truncationMode: "tokens",
    truncationLimit: 10_000,
  };
}

const zhipuDefaultModels = [
  zhipuTextModel(
    "glm-5.1",
    "GLM-5.1",
    "Zhipu latest flagship model with stronger coding and long-horizon agent work.",
    200_000,
    128_000,
  ),
  zhipuTextModel(
    "glm-5",
    "GLM-5",
    "Zhipu high-intelligence foundation model for coding and agentic planning.",
    200_000,
    128_000,
  ),
  zhipuTextModel(
    "glm-5-turbo",
    "GLM-5-Turbo",
    "Zhipu GLM-5 Turbo model optimized for long task continuity.",
    200_000,
    128_000,
  ),
  zhipuTextModel(
    "glm-4.7",
    "GLM-4.7",
    "Zhipu high-intelligence model for dialogue, reasoning, agents, and coding.",
    200_000,
    128_000,
  ),
  zhipuTextModel(
    "glm-4.7-flashx",
    "GLM-4.7-FlashX",
    "Zhipu lightweight high-speed model for general text tasks.",
    200_000,
    128_000,
  ),
  zhipuTextModel(
    "glm-4.7-flash",
    "GLM-4.7-Flash",
    "Zhipu free GLM-4.7 base model.",
    200_000,
    128_000,
  ),
];

export const previewTemplates: ProviderTemplateRecord[] = [
  {
    id: "deepseek",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com",
    defaultModel: "deepseek-v4-flash",
    wireApi: "chat",
    defaultModels: [
      {
        slug: "deepseek-v4-flash",
        displayName: "DeepSeek V4 Flash",
        description: "DeepSeek fast reasoning model with thinking mode.",
        contextWindow: 1_000_000,
        maxContextWindow: 1_000_000,
        maxOutputTokens: 384_000,
        currency: "CNY",
        inputPricePerMTok: 1,
        outputPricePerMTok: 2,
        cacheReadPricePerMTok: 0.02,
        reasoningEfforts: ["high", "max"],
        capabilities: ["streaming", "function_calling", "parallel_tool_calls", "reasoning"],
        inputModalities: ["text"],
        truncationMode: "tokens",
        truncationLimit: 10_000,
      },
      {
        slug: "deepseek-v4-pro",
        displayName: "DeepSeek V4 Pro",
        description: "DeepSeek flagship reasoning model with thinking mode.",
        contextWindow: 1_000_000,
        maxContextWindow: 1_000_000,
        maxOutputTokens: 384_000,
        currency: "CNY",
        inputPricePerMTok: 3,
        outputPricePerMTok: 6,
        cacheReadPricePerMTok: 0.025,
        reasoningEfforts: ["high", "max"],
        capabilities: ["streaming", "function_calling", "parallel_tool_calls", "reasoning"],
        inputModalities: ["text"],
        truncationMode: "tokens",
        truncationLimit: 10_000,
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-4.1",
    wireApi: "responses",
    defaultModels: [
      {
        slug: "gpt-4.1",
        displayName: "GPT-4.1",
        contextWindow: 1_050_000,
        maxContextWindow: 1_050_000,
        maxOutputTokens: 128_000,
        currency: "USD",
        inputPricePerMTok: 2,
        outputPricePerMTok: 8,
        cacheReadPricePerMTok: 0.5,
        reasoningEfforts: ["medium", "high"],
        capabilities: [
          "streaming",
          "function_calling",
          "vision",
          "parallel_tool_calls",
          "reasoning",
          "web_search",
        ],
        inputModalities: ["text", "image"],
        truncationMode: "tokens",
        truncationLimit: 10_000,
      },
      {
        slug: "o4-mini",
        displayName: "o4 mini",
        contextWindow: 400_000,
        maxContextWindow: 400_000,
        maxOutputTokens: 128_000,
        currency: "USD",
        inputPricePerMTok: 1,
        outputPricePerMTok: 4,
        cacheReadPricePerMTok: 0.25,
        reasoningEfforts: ["medium"],
        capabilities: [
          "streaming",
          "function_calling",
          "vision",
          "parallel_tool_calls",
          "reasoning",
          "web_search",
        ],
        inputModalities: ["text", "image"],
        truncationMode: "tokens",
        truncationLimit: 10_000,
      },
    ],
  },
  {
    id: "zhipu-api",
    name: "Zhipu GLM API",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultModel: "glm-5.1",
    wireApi: "chat",
    defaultModels: zhipuDefaultModels,
  },
  {
    id: "zhipu-coding-plan",
    name: "Zhipu GLM Coding Plan",
    baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    defaultModel: "glm-5.1",
    wireApi: "chat",
    defaultModels: zhipuDefaultModels,
  },
];
