// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'interaction.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

class BridgeInteractionChangedDto {
  final String interactionId;
  final String kind;
  final String status;
  final String sessionId;
  final String turnId;
  final String? itemId;
  final String? toolId;
  final String? agentPath;
  final BridgeInteractionPayloadDto payload;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? resolvedAt;

  const BridgeInteractionChangedDto({
    required this.interactionId,
    required this.kind,
    required this.status,
    required this.sessionId,
    required this.turnId,
    this.itemId,
    this.toolId,
    this.agentPath,
    required this.payload,
    required this.createdAt,
    required this.updatedAt,
    this.resolvedAt,
  });

  @override
  int get hashCode =>
      interactionId.hashCode ^
      kind.hashCode ^
      status.hashCode ^
      sessionId.hashCode ^
      turnId.hashCode ^
      itemId.hashCode ^
      toolId.hashCode ^
      agentPath.hashCode ^
      payload.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      resolvedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeInteractionChangedDto &&
          runtimeType == other.runtimeType &&
          interactionId == other.interactionId &&
          kind == other.kind &&
          status == other.status &&
          sessionId == other.sessionId &&
          turnId == other.turnId &&
          itemId == other.itemId &&
          toolId == other.toolId &&
          agentPath == other.agentPath &&
          payload == other.payload &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          resolvedAt == other.resolvedAt;
}

@freezed
sealed class BridgeInteractionPayloadDto with _$BridgeInteractionPayloadDto {
  const BridgeInteractionPayloadDto._();

  const factory BridgeInteractionPayloadDto.userInput({
    required List<BridgeUserQuestionDto> questions,
  }) = BridgeInteractionPayloadDto_UserInput;
  const factory BridgeInteractionPayloadDto.toolApproval({
    required String name,
    required String argumentsJson,
    String? workingDirectory,
    String? parentAgentId,
  }) = BridgeInteractionPayloadDto_ToolApproval;
  const factory BridgeInteractionPayloadDto.planConfirmation({
    required String planId,
    required String content,
  }) = BridgeInteractionPayloadDto_PlanConfirmation;
}

class BridgeUserQuestionDto {
  final String id;
  final String header;
  final String question;
  final bool isOther;
  final bool isSecret;
  final List<BridgeUserQuestionOptionDto>? options;

  const BridgeUserQuestionDto({
    required this.id,
    required this.header,
    required this.question,
    required this.isOther,
    required this.isSecret,
    this.options,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      header.hashCode ^
      question.hashCode ^
      isOther.hashCode ^
      isSecret.hashCode ^
      options.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeUserQuestionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          header == other.header &&
          question == other.question &&
          isOther == other.isOther &&
          isSecret == other.isSecret &&
          options == other.options;
}

class BridgeUserQuestionOptionDto {
  final String label;
  final String description;

  const BridgeUserQuestionOptionDto({
    required this.label,
    required this.description,
  });

  @override
  int get hashCode => label.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeUserQuestionOptionDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          description == other.description;
}
