// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'runtime.dart';
import 'settings.dart';
import 'thread_stream.dart';
import 'updater.dart';
part 'response.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProviderUsagesResponse`, `SkillsResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class ArchiveThreadResult {
  final String archivedRootId;
  final List<String> removedThreadIds;
  final BridgeThread? nextRoot;

  const ArchiveThreadResult({
    required this.archivedRootId,
    required this.removedThreadIds,
    this.nextRoot,
  });

  @override
  int get hashCode =>
      archivedRootId.hashCode ^ removedThreadIds.hashCode ^ nextRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveThreadResult &&
          runtimeType == other.runtimeType &&
          archivedRootId == other.archivedRootId &&
          removedThreadIds == other.removedThreadIds &&
          nextRoot == other.nextRoot;
}

class BridgeAgentDirectoryData {
  final List<BridgeAgentDirectoryEntryDto> agents;

  const BridgeAgentDirectoryData({required this.agents});

  @override
  int get hashCode => agents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAgentDirectoryData &&
          runtimeType == other.runtimeType &&
          agents == other.agents;
}

@freezed
sealed class BridgeAgentDirectoryState with _$BridgeAgentDirectoryState {
  const BridgeAgentDirectoryState._();

  const factory BridgeAgentDirectoryState.uninitialized(
    BridgeUninitializedResource field0,
  ) = BridgeAgentDirectoryState_Uninitialized;
  const factory BridgeAgentDirectoryState.loading(
    BridgeLoadingResource field0,
  ) = BridgeAgentDirectoryState_Loading;
  const factory BridgeAgentDirectoryState.ready({
    required BridgeReadyResource resource,
    required BridgeAgentDirectoryData value,
  }) = BridgeAgentDirectoryState_Ready;
  const factory BridgeAgentDirectoryState.refreshing({
    required BridgeRefreshingResource resource,
    required BridgeAgentDirectoryData value,
  }) = BridgeAgentDirectoryState_Refreshing;
  const factory BridgeAgentDirectoryState.stale({
    required BridgeStaleResource resource,
    required BridgeAgentDirectoryData value,
  }) = BridgeAgentDirectoryState_Stale;
  const factory BridgeAgentDirectoryState.degraded({
    required BridgeDegradedResource resource,
    required BridgeAgentDirectoryData value,
  }) = BridgeAgentDirectoryState_Degraded;
  const factory BridgeAgentDirectoryState.failed(BridgeFailedResource field0) =
      BridgeAgentDirectoryState_Failed;
  const factory BridgeAgentDirectoryState.stopped(
    BridgeStoppedResource field0,
  ) = BridgeAgentDirectoryState_Stopped;
}

class BridgeConfigRecoveryReport {
  final String backupPath;

  const BridgeConfigRecoveryReport({required this.backupPath});

  @override
  int get hashCode => backupPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeConfigRecoveryReport &&
          runtimeType == other.runtimeType &&
          backupPath == other.backupPath;
}

/// `listThreadsPage` 请求；`cursor` 为 `null` 时从最新一页开始。
class BridgeListThreadsPageRequest {
  final String? cursor;
  final int limit;

  const BridgeListThreadsPageRequest({this.cursor, required this.limit});

  @override
  int get hashCode => cursor.hashCode ^ limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeListThreadsPageRequest &&
          runtimeType == other.runtimeType &&
          cursor == other.cursor &&
          limit == other.limit;
}

class BridgeLspStateData {
  final BridgeLspHealthDto health;

  const BridgeLspStateData({required this.health});

  @override
  int get hashCode => health.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLspStateData &&
          runtimeType == other.runtimeType &&
          health == other.health;
}

@freezed
sealed class BridgeLspStateSnapshot with _$BridgeLspStateSnapshot {
  const BridgeLspStateSnapshot._();

  const factory BridgeLspStateSnapshot.uninitialized(
    BridgeUninitializedResource field0,
  ) = BridgeLspStateSnapshot_Uninitialized;
  const factory BridgeLspStateSnapshot.loading(BridgeLoadingResource field0) =
      BridgeLspStateSnapshot_Loading;
  const factory BridgeLspStateSnapshot.ready({
    required BridgeReadyResource resource,
    required BridgeLspStateData value,
  }) = BridgeLspStateSnapshot_Ready;
  const factory BridgeLspStateSnapshot.refreshing({
    required BridgeRefreshingResource resource,
    required BridgeLspStateData value,
  }) = BridgeLspStateSnapshot_Refreshing;
  const factory BridgeLspStateSnapshot.stale({
    required BridgeStaleResource resource,
    required BridgeLspStateData value,
  }) = BridgeLspStateSnapshot_Stale;
  const factory BridgeLspStateSnapshot.degraded({
    required BridgeDegradedResource resource,
    required BridgeLspStateData value,
  }) = BridgeLspStateSnapshot_Degraded;
  const factory BridgeLspStateSnapshot.failed(BridgeFailedResource field0) =
      BridgeLspStateSnapshot_Failed;
  const factory BridgeLspStateSnapshot.stopped(BridgeStoppedResource field0) =
      BridgeLspStateSnapshot_Stopped;
}

class BridgeMcpStateData {
  final String desiredConfigFingerprint;
  final String appliedConfigFingerprint;
  final BridgeMcpHealthDto health;

  const BridgeMcpStateData({
    required this.desiredConfigFingerprint,
    required this.appliedConfigFingerprint,
    required this.health,
  });

  @override
  int get hashCode =>
      desiredConfigFingerprint.hashCode ^
      appliedConfigFingerprint.hashCode ^
      health.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMcpStateData &&
          runtimeType == other.runtimeType &&
          desiredConfigFingerprint == other.desiredConfigFingerprint &&
          appliedConfigFingerprint == other.appliedConfigFingerprint &&
          health == other.health;
}

@freezed
sealed class BridgeMcpStateSnapshot with _$BridgeMcpStateSnapshot {
  const BridgeMcpStateSnapshot._();

  const factory BridgeMcpStateSnapshot.uninitialized(
    BridgeUninitializedResource field0,
  ) = BridgeMcpStateSnapshot_Uninitialized;
  const factory BridgeMcpStateSnapshot.loading(BridgeLoadingResource field0) =
      BridgeMcpStateSnapshot_Loading;
  const factory BridgeMcpStateSnapshot.ready({
    required BridgeReadyResource resource,
    required BridgeMcpStateData value,
  }) = BridgeMcpStateSnapshot_Ready;
  const factory BridgeMcpStateSnapshot.refreshing({
    required BridgeRefreshingResource resource,
    required BridgeMcpStateData value,
  }) = BridgeMcpStateSnapshot_Refreshing;
  const factory BridgeMcpStateSnapshot.stale({
    required BridgeStaleResource resource,
    required BridgeMcpStateData value,
  }) = BridgeMcpStateSnapshot_Stale;
  const factory BridgeMcpStateSnapshot.degraded({
    required BridgeDegradedResource resource,
    required BridgeMcpStateData value,
  }) = BridgeMcpStateSnapshot_Degraded;
  const factory BridgeMcpStateSnapshot.failed(BridgeFailedResource field0) =
      BridgeMcpStateSnapshot_Failed;
  const factory BridgeMcpStateSnapshot.stopped(BridgeStoppedResource field0) =
      BridgeMcpStateSnapshot_Stopped;
}

class BridgeModelPerformanceSample {
  final PlatformInt64 completedAt;
  final String providerInstanceId;
  final String providerDisplayName;
  final String model;
  final BigInt completionTokens;
  final BigInt ttftMillis;
  final BigInt decodeMillis;
  final BigInt totalResponseMillis;
  final double tokensPerSecond;

  const BridgeModelPerformanceSample({
    required this.completedAt,
    required this.providerInstanceId,
    required this.providerDisplayName,
    required this.model,
    required this.completionTokens,
    required this.ttftMillis,
    required this.decodeMillis,
    required this.totalResponseMillis,
    required this.tokensPerSecond,
  });

  @override
  int get hashCode =>
      completedAt.hashCode ^
      providerInstanceId.hashCode ^
      providerDisplayName.hashCode ^
      model.hashCode ^
      completionTokens.hashCode ^
      ttftMillis.hashCode ^
      decodeMillis.hashCode ^
      totalResponseMillis.hashCode ^
      tokensPerSecond.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelPerformanceSample &&
          runtimeType == other.runtimeType &&
          completedAt == other.completedAt &&
          providerInstanceId == other.providerInstanceId &&
          providerDisplayName == other.providerDisplayName &&
          model == other.model &&
          completionTokens == other.completionTokens &&
          ttftMillis == other.ttftMillis &&
          decodeMillis == other.decodeMillis &&
          totalResponseMillis == other.totalResponseMillis &&
          tokensPerSecond == other.tokensPerSecond;
}

class BridgeModelPerformanceSnapshot {
  final BigInt revision;
  final PlatformInt64 updatedAt;
  final List<BridgeSessionCostSnapshot> sessionCosts;
  final List<BridgeModelPerformanceSummary> summaries;
  final List<BridgeModelPerformanceSample> history;

  const BridgeModelPerformanceSnapshot({
    required this.revision,
    required this.updatedAt,
    required this.sessionCosts,
    required this.summaries,
    required this.history,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      updatedAt.hashCode ^
      sessionCosts.hashCode ^
      summaries.hashCode ^
      history.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelPerformanceSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          updatedAt == other.updatedAt &&
          sessionCosts == other.sessionCosts &&
          summaries == other.summaries &&
          history == other.history;
}

class BridgeModelPerformanceSummary {
  final String providerInstanceId;
  final String providerDisplayName;
  final String model;
  final BigInt sampleCount;
  final BigInt completionTokens;
  final BigInt totalTtftMillis;
  final BigInt totalDecodeMillis;
  final BigInt totalResponseMillis;
  final double tokensPerSecond;
  final double averageTtftMillis;
  final double averageResponseMillis;

  const BridgeModelPerformanceSummary({
    required this.providerInstanceId,
    required this.providerDisplayName,
    required this.model,
    required this.sampleCount,
    required this.completionTokens,
    required this.totalTtftMillis,
    required this.totalDecodeMillis,
    required this.totalResponseMillis,
    required this.tokensPerSecond,
    required this.averageTtftMillis,
    required this.averageResponseMillis,
  });

  @override
  int get hashCode =>
      providerInstanceId.hashCode ^
      providerDisplayName.hashCode ^
      model.hashCode ^
      sampleCount.hashCode ^
      completionTokens.hashCode ^
      totalTtftMillis.hashCode ^
      totalDecodeMillis.hashCode ^
      totalResponseMillis.hashCode ^
      tokensPerSecond.hashCode ^
      averageTtftMillis.hashCode ^
      averageResponseMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelPerformanceSummary &&
          runtimeType == other.runtimeType &&
          providerInstanceId == other.providerInstanceId &&
          providerDisplayName == other.providerDisplayName &&
          model == other.model &&
          sampleCount == other.sampleCount &&
          completionTokens == other.completionTokens &&
          totalTtftMillis == other.totalTtftMillis &&
          totalDecodeMillis == other.totalDecodeMillis &&
          totalResponseMillis == other.totalResponseMillis &&
          tokensPerSecond == other.tokensPerSecond &&
          averageTtftMillis == other.averageTtftMillis &&
          averageResponseMillis == other.averageResponseMillis;
}

@freezed
sealed class BridgePersistenceState with _$BridgePersistenceState {
  const BridgePersistenceState._();

  const factory BridgePersistenceState.ready({required BigInt pendingCommits}) =
      BridgePersistenceState_Ready;
  const factory BridgePersistenceState.flushing({
    required BigInt pendingCommits,
    BigInt? oldestPendingRevision,
  }) = BridgePersistenceState_Flushing;
  const factory BridgePersistenceState.degraded({
    required BigInt pendingCommits,
    BigInt? oldestPendingRevision,
    required PlatformInt64 firstFailedAt,
    required BridgeStateError error,
  }) = BridgePersistenceState_Degraded;
  const factory BridgePersistenceState.recovering({
    required BigInt pendingCommits,
    BigInt? oldestPendingRevision,
    required PlatformInt64 firstFailedAt,
  }) = BridgePersistenceState_Recovering;
  const factory BridgePersistenceState.blocked({
    required BigInt pendingCommits,
    BigInt? oldestPendingRevision,
    required PlatformInt64 firstFailedAt,
    required BridgeStateError error,
  }) = BridgePersistenceState_Blocked;
}

class BridgePersistenceStateSnapshot {
  final BigInt revision;
  final BridgePersistenceState state;

  const BridgePersistenceStateSnapshot({
    required this.revision,
    required this.state,
  });

  @override
  int get hashCode => revision.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePersistenceStateSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          state == other.state;
}

class BridgeProjectDirectoryData {
  final List<ProjectDto> projects;

  const BridgeProjectDirectoryData({required this.projects});

  @override
  int get hashCode => projects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProjectDirectoryData &&
          runtimeType == other.runtimeType &&
          projects == other.projects;
}

@freezed
sealed class BridgeProjectDirectoryState with _$BridgeProjectDirectoryState {
  const BridgeProjectDirectoryState._();

  const factory BridgeProjectDirectoryState.uninitialized(
    BridgeUninitializedResource field0,
  ) = BridgeProjectDirectoryState_Uninitialized;
  const factory BridgeProjectDirectoryState.loading(
    BridgeLoadingResource field0,
  ) = BridgeProjectDirectoryState_Loading;
  const factory BridgeProjectDirectoryState.ready({
    required BridgeReadyResource resource,
    required BridgeProjectDirectoryData value,
  }) = BridgeProjectDirectoryState_Ready;
  const factory BridgeProjectDirectoryState.refreshing({
    required BridgeRefreshingResource resource,
    required BridgeProjectDirectoryData value,
  }) = BridgeProjectDirectoryState_Refreshing;
  const factory BridgeProjectDirectoryState.stale({
    required BridgeStaleResource resource,
    required BridgeProjectDirectoryData value,
  }) = BridgeProjectDirectoryState_Stale;
  const factory BridgeProjectDirectoryState.degraded({
    required BridgeDegradedResource resource,
    required BridgeProjectDirectoryData value,
  }) = BridgeProjectDirectoryState_Degraded;
  const factory BridgeProjectDirectoryState.failed(
    BridgeFailedResource field0,
  ) = BridgeProjectDirectoryState_Failed;
  const factory BridgeProjectDirectoryState.stopped(
    BridgeStoppedResource field0,
  ) = BridgeProjectDirectoryState_Stopped;
}

@freezed
sealed class BridgeProviderUsageData with _$BridgeProviderUsageData {
  const BridgeProviderUsageData._();

  const factory BridgeProviderUsageData.deepSeekBalance(
    DeepSeekBalanceDto field0,
  ) = BridgeProviderUsageData_DeepSeekBalance;
  const factory BridgeProviderUsageData.zhipuCodingPlan(
    ZhipuCodingPlanUsageDto field0,
  ) = BridgeProviderUsageData_ZhipuCodingPlan;
}

@freezed
sealed class BridgeProviderUsageState with _$BridgeProviderUsageState {
  const BridgeProviderUsageState._();

  const factory BridgeProviderUsageState.unsupported() =
      BridgeProviderUsageState_Unsupported;
  const factory BridgeProviderUsageState.missingCredential({
    required String message,
  }) = BridgeProviderUsageState_MissingCredential;
  const factory BridgeProviderUsageState.ready({
    required BridgeProviderUsageData data,
  }) = BridgeProviderUsageState_Ready;
  const factory BridgeProviderUsageState.failed({
    required BridgeStateError error,
  }) = BridgeProviderUsageState_Failed;
}

class BridgeProviderUsageStateData {
  final String configFingerprint;
  final List<ProviderUsageDto> usages;

  const BridgeProviderUsageStateData({
    required this.configFingerprint,
    required this.usages,
  });

  @override
  int get hashCode => configFingerprint.hashCode ^ usages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderUsageStateData &&
          runtimeType == other.runtimeType &&
          configFingerprint == other.configFingerprint &&
          usages == other.usages;
}

@freezed
sealed class BridgeProviderUsageStateSnapshot
    with _$BridgeProviderUsageStateSnapshot {
  const BridgeProviderUsageStateSnapshot._();

  const factory BridgeProviderUsageStateSnapshot.uninitialized(
    BridgeUninitializedResource field0,
  ) = BridgeProviderUsageStateSnapshot_Uninitialized;
  const factory BridgeProviderUsageStateSnapshot.loading(
    BridgeLoadingResource field0,
  ) = BridgeProviderUsageStateSnapshot_Loading;
  const factory BridgeProviderUsageStateSnapshot.ready({
    required BridgeReadyResource resource,
    required BridgeProviderUsageStateData value,
  }) = BridgeProviderUsageStateSnapshot_Ready;
  const factory BridgeProviderUsageStateSnapshot.refreshing({
    required BridgeRefreshingResource resource,
    required BridgeProviderUsageStateData value,
  }) = BridgeProviderUsageStateSnapshot_Refreshing;
  const factory BridgeProviderUsageStateSnapshot.stale({
    required BridgeStaleResource resource,
    required BridgeProviderUsageStateData value,
  }) = BridgeProviderUsageStateSnapshot_Stale;
  const factory BridgeProviderUsageStateSnapshot.degraded({
    required BridgeDegradedResource resource,
    required BridgeProviderUsageStateData value,
  }) = BridgeProviderUsageStateSnapshot_Degraded;
  const factory BridgeProviderUsageStateSnapshot.failed(
    BridgeFailedResource field0,
  ) = BridgeProviderUsageStateSnapshot_Failed;
  const factory BridgeProviderUsageStateSnapshot.stopped(
    BridgeStoppedResource field0,
  ) = BridgeProviderUsageStateSnapshot_Stopped;
}

class BridgeRecoveryStateData {
  final List<BridgeStudioRecoveryIssueDto> issues;

  const BridgeRecoveryStateData({required this.issues});

  @override
  int get hashCode => issues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRecoveryStateData &&
          runtimeType == other.runtimeType &&
          issues == other.issues;
}

@freezed
sealed class BridgeRecoveryStateSnapshot with _$BridgeRecoveryStateSnapshot {
  const BridgeRecoveryStateSnapshot._();

  const factory BridgeRecoveryStateSnapshot.uninitialized(
    BridgeUninitializedResource field0,
  ) = BridgeRecoveryStateSnapshot_Uninitialized;
  const factory BridgeRecoveryStateSnapshot.loading(
    BridgeLoadingResource field0,
  ) = BridgeRecoveryStateSnapshot_Loading;
  const factory BridgeRecoveryStateSnapshot.ready({
    required BridgeReadyResource resource,
    required BridgeRecoveryStateData value,
  }) = BridgeRecoveryStateSnapshot_Ready;
  const factory BridgeRecoveryStateSnapshot.refreshing({
    required BridgeRefreshingResource resource,
    required BridgeRecoveryStateData value,
  }) = BridgeRecoveryStateSnapshot_Refreshing;
  const factory BridgeRecoveryStateSnapshot.stale({
    required BridgeStaleResource resource,
    required BridgeRecoveryStateData value,
  }) = BridgeRecoveryStateSnapshot_Stale;
  const factory BridgeRecoveryStateSnapshot.degraded({
    required BridgeDegradedResource resource,
    required BridgeRecoveryStateData value,
  }) = BridgeRecoveryStateSnapshot_Degraded;
  const factory BridgeRecoveryStateSnapshot.failed(
    BridgeFailedResource field0,
  ) = BridgeRecoveryStateSnapshot_Failed;
  const factory BridgeRecoveryStateSnapshot.stopped(
    BridgeStoppedResource field0,
  ) = BridgeRecoveryStateSnapshot_Stopped;
}

class BridgeSessionCostSnapshot {
  final String rootThreadId;
  final List<BridgeRuntimeCostAmount> estimatedCosts;
  final bool hasUnpricedUsage;

  const BridgeSessionCostSnapshot({
    required this.rootThreadId,
    required this.estimatedCosts,
    required this.hasUnpricedUsage,
  });

  @override
  int get hashCode =>
      rootThreadId.hashCode ^
      estimatedCosts.hashCode ^
      hasUnpricedUsage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSessionCostSnapshot &&
          runtimeType == other.runtimeType &&
          rootThreadId == other.rootThreadId &&
          estimatedCosts == other.estimatedCosts &&
          hasUnpricedUsage == other.hasUnpricedUsage;
}

class BridgeSettingsStateData {
  final BridgeStudioSettingsDto settings;

  const BridgeSettingsStateData({required this.settings});

  @override
  int get hashCode => settings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSettingsStateData &&
          runtimeType == other.runtimeType &&
          settings == other.settings;
}

@freezed
sealed class BridgeSettingsStateSnapshot with _$BridgeSettingsStateSnapshot {
  const BridgeSettingsStateSnapshot._();

  const factory BridgeSettingsStateSnapshot.uninitialized(
    BridgeUninitializedResource field0,
  ) = BridgeSettingsStateSnapshot_Uninitialized;
  const factory BridgeSettingsStateSnapshot.loading(
    BridgeLoadingResource field0,
  ) = BridgeSettingsStateSnapshot_Loading;
  const factory BridgeSettingsStateSnapshot.ready({
    required BridgeReadyResource resource,
    required BridgeSettingsStateData value,
  }) = BridgeSettingsStateSnapshot_Ready;
  const factory BridgeSettingsStateSnapshot.refreshing({
    required BridgeRefreshingResource resource,
    required BridgeSettingsStateData value,
  }) = BridgeSettingsStateSnapshot_Refreshing;
  const factory BridgeSettingsStateSnapshot.stale({
    required BridgeStaleResource resource,
    required BridgeSettingsStateData value,
  }) = BridgeSettingsStateSnapshot_Stale;
  const factory BridgeSettingsStateSnapshot.degraded({
    required BridgeDegradedResource resource,
    required BridgeSettingsStateData value,
  }) = BridgeSettingsStateSnapshot_Degraded;
  const factory BridgeSettingsStateSnapshot.failed(
    BridgeFailedResource field0,
  ) = BridgeSettingsStateSnapshot_Failed;
  const factory BridgeSettingsStateSnapshot.stopped(
    BridgeStoppedResource field0,
  ) = BridgeSettingsStateSnapshot_Stopped;
}

class BridgeSkillSearchResult {
  final String projectId;
  final BigInt catalogRevision;
  final List<SkillSummaryDto> matches;
  final bool truncated;

  const BridgeSkillSearchResult({
    required this.projectId,
    required this.catalogRevision,
    required this.matches,
    required this.truncated,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      catalogRevision.hashCode ^
      matches.hashCode ^
      truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSkillSearchResult &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          catalogRevision == other.catalogRevision &&
          matches == other.matches &&
          truncated == other.truncated;
}

@freezed
sealed class BridgeSkillsResourceState with _$BridgeSkillsResourceState {
  const BridgeSkillsResourceState._();

  const factory BridgeSkillsResourceState.uninitialized(
    BridgeUninitializedResource field0,
  ) = BridgeSkillsResourceState_Uninitialized;
  const factory BridgeSkillsResourceState.loading(
    BridgeLoadingResource field0,
  ) = BridgeSkillsResourceState_Loading;
  const factory BridgeSkillsResourceState.ready({
    required BridgeReadyResource resource,
    required BridgeSkillsStateData value,
  }) = BridgeSkillsResourceState_Ready;
  const factory BridgeSkillsResourceState.refreshing({
    required BridgeRefreshingResource resource,
    required BridgeSkillsStateData value,
  }) = BridgeSkillsResourceState_Refreshing;
  const factory BridgeSkillsResourceState.stale({
    required BridgeStaleResource resource,
    required BridgeSkillsStateData value,
  }) = BridgeSkillsResourceState_Stale;
  const factory BridgeSkillsResourceState.degraded({
    required BridgeDegradedResource resource,
    required BridgeSkillsStateData value,
  }) = BridgeSkillsResourceState_Degraded;
  const factory BridgeSkillsResourceState.failed(BridgeFailedResource field0) =
      BridgeSkillsResourceState_Failed;
  const factory BridgeSkillsResourceState.stopped(
    BridgeStoppedResource field0,
  ) = BridgeSkillsResourceState_Stopped;
}

class BridgeSkillsStateData {
  final String configFingerprint;
  final BigInt catalogRevision;
  final List<SkillSummaryDto> skills;
  final List<ModeSummaryDto> modes;
  final List<String> warnings;
  final bool complete;

  const BridgeSkillsStateData({
    required this.configFingerprint,
    required this.catalogRevision,
    required this.skills,
    required this.modes,
    required this.warnings,
    required this.complete,
  });

  @override
  int get hashCode =>
      configFingerprint.hashCode ^
      catalogRevision.hashCode ^
      skills.hashCode ^
      modes.hashCode ^
      warnings.hashCode ^
      complete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSkillsStateData &&
          runtimeType == other.runtimeType &&
          configFingerprint == other.configFingerprint &&
          catalogRevision == other.catalogRevision &&
          skills == other.skills &&
          modes == other.modes &&
          warnings == other.warnings &&
          complete == other.complete;
}

class BridgeSkillsStateSnapshot {
  final String projectId;
  final BridgeSkillsResourceState state;

  const BridgeSkillsStateSnapshot({
    required this.projectId,
    required this.state,
  });

  @override
  int get hashCode => projectId.hashCode ^ state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSkillsStateSnapshot &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          state == other.state;
}

class BridgeStudioStartupResult {
  final RuntimeSnapshot runtime;
  final BridgeConfigRecoveryReport? configRecovery;

  const BridgeStudioStartupResult({required this.runtime, this.configRecovery});

  @override
  int get hashCode => runtime.hashCode ^ configRecovery.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioStartupResult &&
          runtimeType == other.runtimeType &&
          runtime == other.runtime &&
          configRecovery == other.configRecovery;
}

class BridgeStudioStateSnapshot {
  final RuntimeSnapshot runtime;
  final BridgeProjectDirectoryState projectDirectory;

  /// 目录分页窗口的首页；后续页通过 `listThreadsPage` keyset cursor 加载。
  final BridgeThreadDirectoryPage threadDirectory;
  final BridgeAgentDirectoryState agentDirectory;
  final BridgeSettingsStateSnapshot settings;
  final BridgeRecoveryStateSnapshot recovery;
  final BridgeMcpStateSnapshot mcp;
  final BridgeLspStateSnapshot lsp;
  final List<BridgeSkillsStateSnapshot> skillsByProject;
  final BridgeProviderUsageStateSnapshot providerUsage;
  final BridgeModelPerformanceSnapshot modelPerformance;
  final BridgeUpdaterStateSnapshot updater;
  final BridgePersistenceStateSnapshot persistence;

  const BridgeStudioStateSnapshot({
    required this.runtime,
    required this.projectDirectory,
    required this.threadDirectory,
    required this.agentDirectory,
    required this.settings,
    required this.recovery,
    required this.mcp,
    required this.lsp,
    required this.skillsByProject,
    required this.providerUsage,
    required this.modelPerformance,
    required this.updater,
    required this.persistence,
  });

  @override
  int get hashCode =>
      runtime.hashCode ^
      projectDirectory.hashCode ^
      threadDirectory.hashCode ^
      agentDirectory.hashCode ^
      settings.hashCode ^
      recovery.hashCode ^
      mcp.hashCode ^
      lsp.hashCode ^
      skillsByProject.hashCode ^
      providerUsage.hashCode ^
      modelPerformance.hashCode ^
      updater.hashCode ^
      persistence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioStateSnapshot &&
          runtimeType == other.runtimeType &&
          runtime == other.runtime &&
          projectDirectory == other.projectDirectory &&
          threadDirectory == other.threadDirectory &&
          agentDirectory == other.agentDirectory &&
          settings == other.settings &&
          recovery == other.recovery &&
          mcp == other.mcp &&
          lsp == other.lsp &&
          skillsByProject == other.skillsByProject &&
          providerUsage == other.providerUsage &&
          modelPerformance == other.modelPerformance &&
          updater == other.updater &&
          persistence == other.persistence;
}

@freezed
sealed class BridgeThreadDirectoryPage with _$BridgeThreadDirectoryPage {
  const BridgeThreadDirectoryPage._();

  const factory BridgeThreadDirectoryPage.uninitialized(
    BridgeUninitializedResource field0,
  ) = BridgeThreadDirectoryPage_Uninitialized;
  const factory BridgeThreadDirectoryPage.loading(
    BridgeLoadingResource field0,
  ) = BridgeThreadDirectoryPage_Loading;
  const factory BridgeThreadDirectoryPage.ready({
    required BridgeReadyResource resource,
    required BridgeThreadDirectoryPageData value,
  }) = BridgeThreadDirectoryPage_Ready;
  const factory BridgeThreadDirectoryPage.refreshing({
    required BridgeRefreshingResource resource,
    required BridgeThreadDirectoryPageData value,
  }) = BridgeThreadDirectoryPage_Refreshing;
  const factory BridgeThreadDirectoryPage.stale({
    required BridgeStaleResource resource,
    required BridgeThreadDirectoryPageData value,
  }) = BridgeThreadDirectoryPage_Stale;
  const factory BridgeThreadDirectoryPage.degraded({
    required BridgeDegradedResource resource,
    required BridgeThreadDirectoryPageData value,
  }) = BridgeThreadDirectoryPage_Degraded;
  const factory BridgeThreadDirectoryPage.failed(BridgeFailedResource field0) =
      BridgeThreadDirectoryPage_Failed;
  const factory BridgeThreadDirectoryPage.stopped(
    BridgeStoppedResource field0,
  ) = BridgeThreadDirectoryPage_Stopped;
}

/// Thread directory 分页窗口页数据（按 `updatedAt` 倒序、id 倒序的 keyset cursor）。
class BridgeThreadDirectoryPageData {
  final List<BridgeThread> threads;

  /// `None` 表示没有更旧的页。
  final String? nextCursor;

  const BridgeThreadDirectoryPageData({required this.threads, this.nextCursor});

  @override
  int get hashCode => threads.hashCode ^ nextCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeThreadDirectoryPageData &&
          runtimeType == other.runtimeType &&
          threads == other.threads &&
          nextCursor == other.nextCursor;
}

class DeepSeekBalanceDto {
  final bool isAvailable;
  final List<DeepSeekBalanceInfoDto> balances;

  const DeepSeekBalanceDto({required this.isAvailable, required this.balances});

  @override
  int get hashCode => isAvailable.hashCode ^ balances.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeepSeekBalanceDto &&
          runtimeType == other.runtimeType &&
          isAvailable == other.isAvailable &&
          balances == other.balances;
}

class DeepSeekBalanceInfoDto {
  final String currency;
  final String totalBalance;
  final String grantedBalance;
  final String toppedUpBalance;

  const DeepSeekBalanceInfoDto({
    required this.currency,
    required this.totalBalance,
    required this.grantedBalance,
    required this.toppedUpBalance,
  });

  @override
  int get hashCode =>
      currency.hashCode ^
      totalBalance.hashCode ^
      grantedBalance.hashCode ^
      toppedUpBalance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeepSeekBalanceInfoDto &&
          runtimeType == other.runtimeType &&
          currency == other.currency &&
          totalBalance == other.totalBalance &&
          grantedBalance == other.grantedBalance &&
          toppedUpBalance == other.toppedUpBalance;
}

class InterruptTurnResponse {
  final String threadId;
  final String turnId;
  final bool interrupted;

  const InterruptTurnResponse({
    required this.threadId,
    required this.turnId,
    required this.interrupted,
  });

  @override
  int get hashCode =>
      threadId.hashCode ^ turnId.hashCode ^ interrupted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InterruptTurnResponse &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          turnId == other.turnId &&
          interrupted == other.interrupted;
}

class ModeSummaryDto {
  final String id;
  final String displayName;
  final String description;
  final int order;
  final String source;
  final String providerId;

  const ModeSummaryDto({
    required this.id,
    required this.displayName,
    required this.description,
    required this.order,
    required this.source,
    required this.providerId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      order.hashCode ^
      source.hashCode ^
      providerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModeSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          description == other.description &&
          order == other.order &&
          source == other.source &&
          providerId == other.providerId;
}

class ProjectDto {
  final String id;
  final String name;
  final String path;
  final String? sshServerId;
  final PlatformInt64 updatedAt;

  const ProjectDto({
    required this.id,
    required this.name,
    required this.path,
    this.sshServerId,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      path.hashCode ^
      sshServerId.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          path == other.path &&
          sshServerId == other.sshServerId &&
          updatedAt == other.updatedAt;
}

class ProviderUsageDto {
  final String providerId;
  final BigInt revision;
  final PlatformInt64 updatedAt;
  final BridgeProviderUsageState state;

  const ProviderUsageDto({
    required this.providerId,
    required this.revision,
    required this.updatedAt,
    required this.state,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      revision.hashCode ^
      updatedAt.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderUsageDto &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          revision == other.revision &&
          updatedAt == other.updatedAt &&
          state == other.state;
}

class SkillInvocationPolicyDto {
  final bool modelInvocable;
  final bool userInvocable;

  const SkillInvocationPolicyDto({
    required this.modelInvocable,
    required this.userInvocable,
  });

  @override
  int get hashCode => modelInvocable.hashCode ^ userInvocable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillInvocationPolicyDto &&
          runtimeType == other.runtimeType &&
          modelInvocable == other.modelInvocable &&
          userInvocable == other.userInvocable;
}

@freezed
sealed class SkillResourceBaseDto with _$SkillResourceBaseDto {
  const SkillResourceBaseDto._();

  const factory SkillResourceBaseDto.directory({required String path}) =
      SkillResourceBaseDto_Directory;
  const factory SkillResourceBaseDto.url({required String url}) =
      SkillResourceBaseDto_Url;
  const factory SkillResourceBaseDto.opaque({required String description}) =
      SkillResourceBaseDto_Opaque;
}

class SkillSummaryDto {
  final String name;
  final String description;
  final String? category;
  final List<String> platforms;
  final String source;
  final String providerId;
  final SkillInvocationPolicyDto invocation;
  final SkillResourceBaseDto resourceBase;

  const SkillSummaryDto({
    required this.name,
    required this.description,
    this.category,
    required this.platforms,
    required this.source,
    required this.providerId,
    required this.invocation,
    required this.resourceBase,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      category.hashCode ^
      platforms.hashCode ^
      source.hashCode ^
      providerId.hashCode ^
      invocation.hashCode ^
      resourceBase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillSummaryDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          category == other.category &&
          platforms == other.platforms &&
          source == other.source &&
          providerId == other.providerId &&
          invocation == other.invocation &&
          resourceBase == other.resourceBase;
}

class StartNewThreadResponse {
  final BridgeThread thread;
  final StartTurnResponse receipt;

  const StartNewThreadResponse({required this.thread, required this.receipt});

  @override
  int get hashCode => thread.hashCode ^ receipt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartNewThreadResponse &&
          runtimeType == other.runtimeType &&
          thread == other.thread &&
          receipt == other.receipt;
}

class StartTurnResponse {
  final String threadId;
  final String turnId;
  final BigInt revision;

  const StartTurnResponse({
    required this.threadId,
    required this.turnId,
    required this.revision,
  });

  @override
  int get hashCode => threadId.hashCode ^ turnId.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartTurnResponse &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          turnId == other.turnId &&
          revision == other.revision;
}

class SteerTurnResponse {
  final String threadId;
  final String turnId;
  final BigInt revision;

  const SteerTurnResponse({
    required this.threadId,
    required this.turnId,
    required this.revision,
  });

  @override
  int get hashCode => threadId.hashCode ^ turnId.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SteerTurnResponse &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          turnId == other.turnId &&
          revision == other.revision;
}

class ZhipuCodingPlanUsageDto {
  final String? level;
  final List<ZhipuQuotaLimitDto> limits;

  const ZhipuCodingPlanUsageDto({this.level, required this.limits});

  @override
  int get hashCode => level.hashCode ^ limits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZhipuCodingPlanUsageDto &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          limits == other.limits;
}

class ZhipuQuotaLimitDto {
  final String window;
  final String label;
  final double percentage;
  final double? currentValue;
  final double? total;
  final double? remaining;
  final PlatformInt64? nextResetAt;
  final List<ZhipuToolUsageDetailDto> usageDetails;

  const ZhipuQuotaLimitDto({
    required this.window,
    required this.label,
    required this.percentage,
    this.currentValue,
    this.total,
    this.remaining,
    this.nextResetAt,
    required this.usageDetails,
  });

  @override
  int get hashCode =>
      window.hashCode ^
      label.hashCode ^
      percentage.hashCode ^
      currentValue.hashCode ^
      total.hashCode ^
      remaining.hashCode ^
      nextResetAt.hashCode ^
      usageDetails.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZhipuQuotaLimitDto &&
          runtimeType == other.runtimeType &&
          window == other.window &&
          label == other.label &&
          percentage == other.percentage &&
          currentValue == other.currentValue &&
          total == other.total &&
          remaining == other.remaining &&
          nextResetAt == other.nextResetAt &&
          usageDetails == other.usageDetails;
}

class ZhipuToolUsageDetailDto {
  final String name;
  final double? currentValue;
  final double? total;
  final double? percentage;

  const ZhipuToolUsageDetailDto({
    required this.name,
    this.currentValue,
    this.total,
    this.percentage,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      currentValue.hashCode ^
      total.hashCode ^
      percentage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZhipuToolUsageDetailDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          currentValue == other.currentValue &&
          total == other.total &&
          percentage == other.percentage;
}
