// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'runtime.dart';
import 'settings.dart';
import 'thread_stream.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BridgeStudioSnapshotResponse {
  final List<ProjectDto> projects;
  final String? selectedProjectId;
  final List<BridgeThread> threads;
  final String? selectedThreadId;
  final BridgeTaskRuntimeDto? selectedThreadTask;
  final List<BridgeStudioRecoveryIssueDto> recoveryIssues;
  final BridgeStudioSettingsDto settings;

  const BridgeStudioSnapshotResponse({
    required this.projects,
    this.selectedProjectId,
    required this.threads,
    this.selectedThreadId,
    this.selectedThreadTask,
    required this.recoveryIssues,
    required this.settings,
  });

  @override
  int get hashCode =>
      projects.hashCode ^
      selectedProjectId.hashCode ^
      threads.hashCode ^
      selectedThreadId.hashCode ^
      selectedThreadTask.hashCode ^
      recoveryIssues.hashCode ^
      settings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioSnapshotResponse &&
          runtimeType == other.runtimeType &&
          projects == other.projects &&
          selectedProjectId == other.selectedProjectId &&
          threads == other.threads &&
          selectedThreadId == other.selectedThreadId &&
          selectedThreadTask == other.selectedThreadTask &&
          recoveryIssues == other.recoveryIssues &&
          settings == other.settings;
}

class DeepSeekBalanceDto {
  final bool isAvailable;
  final List<DeepSeekBalanceInfoDto> balances;

  const DeepSeekBalanceDto({required this.isAvailable, required this.balances});

  @override
  int get hashCode => isAvailable.hashCode ^ balances.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeepSeekBalanceDto &&
          runtimeType == other.runtimeType &&
          isAvailable == other.isAvailable &&
          balances == other.balances;
}

class DeepSeekBalanceInfoDto {
  final String currency;
  final String totalBalance;
  final String grantedBalance;
  final String toppedUpBalance;

  const DeepSeekBalanceInfoDto({
    required this.currency,
    required this.totalBalance,
    required this.grantedBalance,
    required this.toppedUpBalance,
  });

  @override
  int get hashCode =>
      currency.hashCode ^
      totalBalance.hashCode ^
      grantedBalance.hashCode ^
      toppedUpBalance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeepSeekBalanceInfoDto &&
          runtimeType == other.runtimeType &&
          currency == other.currency &&
          totalBalance == other.totalBalance &&
          grantedBalance == other.grantedBalance &&
          toppedUpBalance == other.toppedUpBalance;
}

class InterruptTurnResponse {
  final String threadId;
  final String turnId;
  final bool interrupted;

  const InterruptTurnResponse({
    required this.threadId,
    required this.turnId,
    required this.interrupted,
  });

  @override
  int get hashCode =>
      threadId.hashCode ^ turnId.hashCode ^ interrupted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InterruptTurnResponse &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          turnId == other.turnId &&
          interrupted == other.interrupted;
}

class ProjectDto {
  final String id;
  final String name;
  final String path;
  final PlatformInt64 updatedAt;

  const ProjectDto({
    required this.id,
    required this.name,
    required this.path,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ path.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          path == other.path &&
          updatedAt == other.updatedAt;
}

class ProviderUsageDto {
  final String providerId;
  final PlatformInt64 updatedAt;
  final String status;
  final String usageKind;
  final String? message;
  final DeepSeekBalanceDto? balance;
  final ZhipuCodingPlanUsageDto? codingPlan;

  const ProviderUsageDto({
    required this.providerId,
    required this.updatedAt,
    required this.status,
    required this.usageKind,
    this.message,
    this.balance,
    this.codingPlan,
  });

  @override
  int get hashCode =>
      providerId.hashCode ^
      updatedAt.hashCode ^
      status.hashCode ^
      usageKind.hashCode ^
      message.hashCode ^
      balance.hashCode ^
      codingPlan.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderUsageDto &&
          runtimeType == other.runtimeType &&
          providerId == other.providerId &&
          updatedAt == other.updatedAt &&
          status == other.status &&
          usageKind == other.usageKind &&
          message == other.message &&
          balance == other.balance &&
          codingPlan == other.codingPlan;
}

class ProviderUsagesResponse {
  final List<ProviderUsageDto> usages;

  const ProviderUsagesResponse({required this.usages});

  @override
  int get hashCode => usages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderUsagesResponse &&
          runtimeType == other.runtimeType &&
          usages == other.usages;
}

class SkillSummaryDto {
  final String name;

  const SkillSummaryDto({required this.name});

  @override
  int get hashCode => name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillSummaryDto &&
          runtimeType == other.runtimeType &&
          name == other.name;
}

class SkillsResponse {
  final List<SkillSummaryDto> skills;

  const SkillsResponse({required this.skills});

  @override
  int get hashCode => skills.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillsResponse &&
          runtimeType == other.runtimeType &&
          skills == other.skills;
}

class StartTurnResponse {
  final String threadId;
  final String turnId;
  final BigInt revision;

  const StartTurnResponse({
    required this.threadId,
    required this.turnId,
    required this.revision,
  });

  @override
  int get hashCode => threadId.hashCode ^ turnId.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartTurnResponse &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          turnId == other.turnId &&
          revision == other.revision;
}

class SteerTurnResponse {
  final String threadId;
  final String turnId;
  final BigInt revision;

  const SteerTurnResponse({
    required this.threadId,
    required this.turnId,
    required this.revision,
  });

  @override
  int get hashCode => threadId.hashCode ^ turnId.hashCode ^ revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SteerTurnResponse &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          turnId == other.turnId &&
          revision == other.revision;
}

class ZhipuCodingPlanUsageDto {
  final String? level;
  final List<ZhipuQuotaLimitDto> limits;

  const ZhipuCodingPlanUsageDto({this.level, required this.limits});

  @override
  int get hashCode => level.hashCode ^ limits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZhipuCodingPlanUsageDto &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          limits == other.limits;
}

class ZhipuQuotaLimitDto {
  final String window;
  final String label;
  final double percentage;
  final double? currentValue;
  final double? total;
  final double? remaining;
  final PlatformInt64? nextResetAt;
  final List<ZhipuToolUsageDetailDto> usageDetails;

  const ZhipuQuotaLimitDto({
    required this.window,
    required this.label,
    required this.percentage,
    this.currentValue,
    this.total,
    this.remaining,
    this.nextResetAt,
    required this.usageDetails,
  });

  @override
  int get hashCode =>
      window.hashCode ^
      label.hashCode ^
      percentage.hashCode ^
      currentValue.hashCode ^
      total.hashCode ^
      remaining.hashCode ^
      nextResetAt.hashCode ^
      usageDetails.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZhipuQuotaLimitDto &&
          runtimeType == other.runtimeType &&
          window == other.window &&
          label == other.label &&
          percentage == other.percentage &&
          currentValue == other.currentValue &&
          total == other.total &&
          remaining == other.remaining &&
          nextResetAt == other.nextResetAt &&
          usageDetails == other.usageDetails;
}

class ZhipuToolUsageDetailDto {
  final String name;
  final double? currentValue;
  final double? total;
  final double? percentage;

  const ZhipuToolUsageDetailDto({
    required this.name,
    this.currentValue,
    this.total,
    this.percentage,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      currentValue.hashCode ^
      total.hashCode ^
      percentage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZhipuToolUsageDetailDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          currentValue == other.currentValue &&
          total == other.total &&
          percentage == other.percentage;
}
