// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'settings.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_input_source`, `bridge_modality`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Provider 配置中由用户定义的模型，不复制内置 catalog 元数据。
class BridgeCustomModelSettingsDto {
  final BigInt contextWindow;
  final BigInt maxOutputTokens;
  final String slug;
  final String displayName;
  final List<String> reasoningEfforts;
  final String baseInstructions;
  final String wireProtocol;
  final List<String> supportedConnectionModes;
  final String defaultConnectionMode;

  const BridgeCustomModelSettingsDto({
    required this.contextWindow,
    required this.maxOutputTokens,
    required this.slug,
    required this.displayName,
    required this.reasoningEfforts,
    required this.baseInstructions,
    required this.wireProtocol,
    required this.supportedConnectionModes,
    required this.defaultConnectionMode,
  });

  @override
  int get hashCode =>
      contextWindow.hashCode ^
      maxOutputTokens.hashCode ^
      slug.hashCode ^
      displayName.hashCode ^
      reasoningEfforts.hashCode ^
      baseInstructions.hashCode ^
      wireProtocol.hashCode ^
      supportedConnectionModes.hashCode ^
      defaultConnectionMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCustomModelSettingsDto &&
          runtimeType == other.runtimeType &&
          contextWindow == other.contextWindow &&
          maxOutputTokens == other.maxOutputTokens &&
          slug == other.slug &&
          displayName == other.displayName &&
          reasoningEfforts == other.reasoningEfforts &&
          baseInstructions == other.baseInstructions &&
          wireProtocol == other.wireProtocol &&
          supportedConnectionModes == other.supportedConnectionModes &&
          defaultConnectionMode == other.defaultConnectionMode;
}

/// DeepSeek 原生 Web 搜索的 canonical bridge 快照。
class BridgeDeepSeekWebSearchSettingsDto {
  final bool configuredEnabled;
  final bool effectiveEnabled;
  final String availability;
  final bool selected;
  final String? providerId;
  final String? model;

  const BridgeDeepSeekWebSearchSettingsDto({
    required this.configuredEnabled,
    required this.effectiveEnabled,
    required this.availability,
    required this.selected,
    this.providerId,
    this.model,
  });

  @override
  int get hashCode =>
      configuredEnabled.hashCode ^
      effectiveEnabled.hashCode ^
      availability.hashCode ^
      selected.hashCode ^
      providerId.hashCode ^
      model.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeDeepSeekWebSearchSettingsDto &&
          runtimeType == other.runtimeType &&
          configuredEnabled == other.configuredEnabled &&
          effectiveEnabled == other.effectiveEnabled &&
          availability == other.availability &&
          selected == other.selected &&
          providerId == other.providerId &&
          model == other.model;
}

/// Flutter 本地通用设置的 typed 快照。
class BridgeGeneralSettingsDto {
  final bool followSystemTheme;
  final bool followActiveTurn;
  final bool compactTimeline;

  const BridgeGeneralSettingsDto({
    required this.followSystemTheme,
    required this.followActiveTurn,
    required this.compactTimeline,
  });

  static Future<BridgeGeneralSettingsDto> default_() => RustLib.instance.api
      .crateApiStudioTypesSettingsBridgeGeneralSettingsDtoDefault();

  @override
  int get hashCode =>
      followSystemTheme.hashCode ^
      followActiveTurn.hashCode ^
      compactTimeline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGeneralSettingsDto &&
          runtimeType == other.runtimeType &&
          followSystemTheme == other.followSystemTheme &&
          followActiveTurn == other.followActiveTurn &&
          compactTimeline == other.compactTimeline;
}

/// Instructions 页的 canonical 设置。
class BridgeInstructionsSettingsDto {
  final String baseOverride;
  final String developer;
  final String user;
  final BigInt projectDocMaxBytes;
  final List<String> projectDocFallbackFilenames;

  const BridgeInstructionsSettingsDto({
    required this.baseOverride,
    required this.developer,
    required this.user,
    required this.projectDocMaxBytes,
    required this.projectDocFallbackFilenames,
  });

  @override
  int get hashCode =>
      baseOverride.hashCode ^
      developer.hashCode ^
      user.hashCode ^
      projectDocMaxBytes.hashCode ^
      projectDocFallbackFilenames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeInstructionsSettingsDto &&
          runtimeType == other.runtimeType &&
          baseOverride == other.baseOverride &&
          developer == other.developer &&
          user == other.user &&
          projectDocMaxBytes == other.projectDocMaxBytes &&
          projectDocFallbackFilenames == other.projectDocFallbackFilenames;
}

enum BridgeMcpServerConfiguration { enabled, disabled, missingCredential }

/// MCP 设置页的 canonical server 视图。
class BridgeMcpServerSettingsDto {
  final String id;
  final String transport;
  final String endpoint;
  final BridgeMcpServerConfiguration configuration;
  final String sourceKind;
  final String mutationPolicy;

  const BridgeMcpServerSettingsDto({
    required this.id,
    required this.transport,
    required this.endpoint,
    required this.configuration,
    required this.sourceKind,
    required this.mutationPolicy,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      transport.hashCode ^
      endpoint.hashCode ^
      configuration.hashCode ^
      sourceKind.hashCode ^
      mutationPolicy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMcpServerSettingsDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          transport == other.transport &&
          endpoint == other.endpoint &&
          configuration == other.configuration &&
          sourceKind == other.sourceKind &&
          mutationPolicy == other.mutationPolicy;
}

class BridgeModelCapabilities {
  final List<BridgeModelInputCapability> input;
  final List<BridgeModelModality> output;
  final bool streaming;
  final bool temperature;
  final bool reasoning;
  final bool webSearch;
  final bool functionCalling;
  final bool parallelToolCalls;
  final bool customTools;
  final bool freeformTools;

  const BridgeModelCapabilities({
    required this.input,
    required this.output,
    required this.streaming,
    required this.temperature,
    required this.reasoning,
    required this.webSearch,
    required this.functionCalling,
    required this.parallelToolCalls,
    required this.customTools,
    required this.freeformTools,
  });

  @override
  int get hashCode =>
      input.hashCode ^
      output.hashCode ^
      streaming.hashCode ^
      temperature.hashCode ^
      reasoning.hashCode ^
      webSearch.hashCode ^
      functionCalling.hashCode ^
      parallelToolCalls.hashCode ^
      customTools.hashCode ^
      freeformTools.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelCapabilities &&
          runtimeType == other.runtimeType &&
          input == other.input &&
          output == other.output &&
          streaming == other.streaming &&
          temperature == other.temperature &&
          reasoning == other.reasoning &&
          webSearch == other.webSearch &&
          functionCalling == other.functionCalling &&
          parallelToolCalls == other.parallelToolCalls &&
          customTools == other.customTools &&
          freeformTools == other.freeformTools;
}

class BridgeModelCatalogDescriptor {
  final String id;
  final List<BridgeModelDescriptor> models;

  const BridgeModelCatalogDescriptor({required this.id, required this.models});

  @override
  int get hashCode => id.hashCode ^ models.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelCatalogDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          models == other.models;
}

/// Provider 实例对 canonical catalog 模型的连接方式覆盖。
class BridgeModelConnectionSettingsDto {
  final String slug;
  final String connectionMode;

  const BridgeModelConnectionSettingsDto({
    required this.slug,
    required this.connectionMode,
  });

  @override
  int get hashCode => slug.hashCode ^ connectionMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelConnectionSettingsDto &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          connectionMode == other.connectionMode;
}

class BridgeModelDescriptor {
  final String id;
  final String displayName;
  final String? description;
  final BigInt? contextWindow;
  final BigInt? maxContextWindow;
  final BigInt? maxOutputTokens;
  final BridgeModelTransportDescriptor transport;
  final BridgeModelCapabilities capabilities;
  final BridgeModelReasoningDescriptor? reasoning;
  final BridgeModelPricing? pricing;

  const BridgeModelDescriptor({
    required this.id,
    required this.displayName,
    this.description,
    this.contextWindow,
    this.maxContextWindow,
    this.maxOutputTokens,
    required this.transport,
    required this.capabilities,
    this.reasoning,
    this.pricing,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      contextWindow.hashCode ^
      maxContextWindow.hashCode ^
      maxOutputTokens.hashCode ^
      transport.hashCode ^
      capabilities.hashCode ^
      reasoning.hashCode ^
      pricing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          description == other.description &&
          contextWindow == other.contextWindow &&
          maxContextWindow == other.maxContextWindow &&
          maxOutputTokens == other.maxOutputTokens &&
          transport == other.transport &&
          capabilities == other.capabilities &&
          reasoning == other.reasoning &&
          pricing == other.pricing;
}

class BridgeModelInputCapability {
  final BridgeModelModality modality;
  final List<BridgeModelInputSource> sources;
  final int? maxCount;
  final BigInt? maxBytes;
  final BigInt? maxTotalBytes;
  final int? maxWidth;
  final int? maxHeight;
  final List<String> mediaTypes;

  const BridgeModelInputCapability({
    required this.modality,
    required this.sources,
    this.maxCount,
    this.maxBytes,
    this.maxTotalBytes,
    this.maxWidth,
    this.maxHeight,
    required this.mediaTypes,
  });

  @override
  int get hashCode =>
      modality.hashCode ^
      sources.hashCode ^
      maxCount.hashCode ^
      maxBytes.hashCode ^
      maxTotalBytes.hashCode ^
      maxWidth.hashCode ^
      maxHeight.hashCode ^
      mediaTypes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelInputCapability &&
          runtimeType == other.runtimeType &&
          modality == other.modality &&
          sources == other.sources &&
          maxCount == other.maxCount &&
          maxBytes == other.maxBytes &&
          maxTotalBytes == other.maxTotalBytes &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight &&
          mediaTypes == other.mediaTypes;
}

enum BridgeModelInputSource { local, remoteUrl }

enum BridgeModelModality { text, image, audio, video, file }

class BridgeModelPriceTier {
  final String label;
  final double inputPerMtok;
  final double outputPerMtok;
  final double? cacheReadPerMtok;
  final double? cacheWritePerMtok;

  const BridgeModelPriceTier({
    required this.label,
    required this.inputPerMtok,
    required this.outputPerMtok,
    this.cacheReadPerMtok,
    this.cacheWritePerMtok,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      inputPerMtok.hashCode ^
      outputPerMtok.hashCode ^
      cacheReadPerMtok.hashCode ^
      cacheWritePerMtok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelPriceTier &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          inputPerMtok == other.inputPerMtok &&
          outputPerMtok == other.outputPerMtok &&
          cacheReadPerMtok == other.cacheReadPerMtok &&
          cacheWritePerMtok == other.cacheWritePerMtok;
}

class BridgeModelPricing {
  final String currency;
  final List<BridgeModelPriceTier> tiers;
  final String source;
  final PlatformInt64 verifiedAt;

  const BridgeModelPricing({
    required this.currency,
    required this.tiers,
    required this.source,
    required this.verifiedAt,
  });

  @override
  int get hashCode =>
      currency.hashCode ^
      tiers.hashCode ^
      source.hashCode ^
      verifiedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelPricing &&
          runtimeType == other.runtimeType &&
          currency == other.currency &&
          tiers == other.tiers &&
          source == other.source &&
          verifiedAt == other.verifiedAt;
}

class BridgeModelReasoningDescriptor {
  final String parameter;
  final String label;
  final String? defaultCandidate;
  final List<String> candidates;

  const BridgeModelReasoningDescriptor({
    required this.parameter,
    required this.label,
    this.defaultCandidate,
    required this.candidates,
  });

  @override
  int get hashCode =>
      parameter.hashCode ^
      label.hashCode ^
      defaultCandidate.hashCode ^
      candidates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelReasoningDescriptor &&
          runtimeType == other.runtimeType &&
          parameter == other.parameter &&
          label == other.label &&
          defaultCandidate == other.defaultCandidate &&
          candidates == other.candidates;
}

class BridgeModelTransportDescriptor {
  final String protocol;
  final List<BridgeProviderConnectionModeDescriptor> connectionModes;
  final String defaultConnectionMode;

  const BridgeModelTransportDescriptor({
    required this.protocol,
    required this.connectionModes,
    required this.defaultConnectionMode,
  });

  @override
  int get hashCode =>
      protocol.hashCode ^
      connectionModes.hashCode ^
      defaultConnectionMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelTransportDescriptor &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          connectionModes == other.connectionModes &&
          defaultConnectionMode == other.defaultConnectionMode;
}

class BridgeProviderCatalogSnapshot {
  final int schemaVersion;
  final String revision;
  final List<BridgeProviderPresetDescriptor> presets;
  final List<BridgeModelCatalogDescriptor> modelCatalogs;

  const BridgeProviderCatalogSnapshot({
    required this.schemaVersion,
    required this.revision,
    required this.presets,
    required this.modelCatalogs,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      revision.hashCode ^
      presets.hashCode ^
      modelCatalogs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderCatalogSnapshot &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          revision == other.revision &&
          presets == other.presets &&
          modelCatalogs == other.modelCatalogs;
}

class BridgeProviderConnectionModeDescriptor {
  final String id;
  final String displayName;

  const BridgeProviderConnectionModeDescriptor({
    required this.id,
    required this.displayName,
  });

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderConnectionModeDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName;
}

class BridgeProviderPresetDescriptor {
  final bool pricingEnabled;
  final String id;
  final String displayName;
  final String? description;
  final String baseUrl;
  final String credentialLabel;
  final String? credentialEnv;
  final String modelCatalogId;
  final String suggestedModel;
  final String? iconKey;
  final BridgeProviderServiceCapabilitiesDescriptor serviceCapabilities;

  const BridgeProviderPresetDescriptor({
    required this.pricingEnabled,
    required this.id,
    required this.displayName,
    this.description,
    required this.baseUrl,
    required this.credentialLabel,
    this.credentialEnv,
    required this.modelCatalogId,
    required this.suggestedModel,
    this.iconKey,
    required this.serviceCapabilities,
  });

  @override
  int get hashCode =>
      pricingEnabled.hashCode ^
      id.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      baseUrl.hashCode ^
      credentialLabel.hashCode ^
      credentialEnv.hashCode ^
      modelCatalogId.hashCode ^
      suggestedModel.hashCode ^
      iconKey.hashCode ^
      serviceCapabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderPresetDescriptor &&
          runtimeType == other.runtimeType &&
          pricingEnabled == other.pricingEnabled &&
          id == other.id &&
          displayName == other.displayName &&
          description == other.description &&
          baseUrl == other.baseUrl &&
          credentialLabel == other.credentialLabel &&
          credentialEnv == other.credentialEnv &&
          modelCatalogId == other.modelCatalogId &&
          suggestedModel == other.suggestedModel &&
          iconKey == other.iconKey &&
          serviceCapabilities == other.serviceCapabilities;
}

class BridgeProviderServiceCapabilitiesDescriptor {
  final BridgeWebSearchProviderCapabilitiesDescriptor webSearch;
  final String promptCacheDialect;
  final bool responsesProgrammaticToolCalling;

  const BridgeProviderServiceCapabilitiesDescriptor({
    required this.webSearch,
    required this.promptCacheDialect,
    required this.responsesProgrammaticToolCalling,
  });

  @override
  int get hashCode =>
      webSearch.hashCode ^
      promptCacheDialect.hashCode ^
      responsesProgrammaticToolCalling.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderServiceCapabilitiesDescriptor &&
          runtimeType == other.runtimeType &&
          webSearch == other.webSearch &&
          promptCacheDialect == other.promptCacheDialect &&
          responsesProgrammaticToolCalling ==
              other.responsesProgrammaticToolCalling;
}

/// 不含 secret 的 Provider canonical 设置视图。
class BridgeProviderSettingsDto {
  final bool pricingEnabled;
  final String id;
  final String templateKind;
  final String name;
  final String baseUrl;
  final bool hasBearerToken;
  final bool credentialRequired;
  final String capabilitySource;
  final bool hostedWebSearch;
  final String hostedWebSearchDialect;
  final String? standaloneWebSearch;
  final String promptCacheDialect;
  final bool responsesProgrammaticToolCalling;
  final String defaultModel;
  final List<BridgeCustomModelSettingsDto> customModels;
  final List<BridgeModelConnectionSettingsDto> modelConnectionModes;
  final String? catalogId;

  const BridgeProviderSettingsDto({
    required this.pricingEnabled,
    required this.id,
    required this.templateKind,
    required this.name,
    required this.baseUrl,
    required this.hasBearerToken,
    required this.credentialRequired,
    required this.capabilitySource,
    required this.hostedWebSearch,
    required this.hostedWebSearchDialect,
    this.standaloneWebSearch,
    required this.promptCacheDialect,
    required this.responsesProgrammaticToolCalling,
    required this.defaultModel,
    required this.customModels,
    required this.modelConnectionModes,
    this.catalogId,
  });

  @override
  int get hashCode =>
      pricingEnabled.hashCode ^
      id.hashCode ^
      templateKind.hashCode ^
      name.hashCode ^
      baseUrl.hashCode ^
      hasBearerToken.hashCode ^
      credentialRequired.hashCode ^
      capabilitySource.hashCode ^
      hostedWebSearch.hashCode ^
      hostedWebSearchDialect.hashCode ^
      standaloneWebSearch.hashCode ^
      promptCacheDialect.hashCode ^
      responsesProgrammaticToolCalling.hashCode ^
      defaultModel.hashCode ^
      customModels.hashCode ^
      modelConnectionModes.hashCode ^
      catalogId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderSettingsDto &&
          runtimeType == other.runtimeType &&
          pricingEnabled == other.pricingEnabled &&
          id == other.id &&
          templateKind == other.templateKind &&
          name == other.name &&
          baseUrl == other.baseUrl &&
          hasBearerToken == other.hasBearerToken &&
          credentialRequired == other.credentialRequired &&
          capabilitySource == other.capabilitySource &&
          hostedWebSearch == other.hostedWebSearch &&
          hostedWebSearchDialect == other.hostedWebSearchDialect &&
          standaloneWebSearch == other.standaloneWebSearch &&
          promptCacheDialect == other.promptCacheDialect &&
          responsesProgrammaticToolCalling ==
              other.responsesProgrammaticToolCalling &&
          defaultModel == other.defaultModel &&
          customModels == other.customModels &&
          modelConnectionModes == other.modelConnectionModes &&
          catalogId == other.catalogId;
}

/// 角色到 provider/model/effort 的 canonical 路由。
class BridgeRoleSettingsDto {
  final String key;
  final String providerId;
  final String model;
  final String effort;

  const BridgeRoleSettingsDto({
    required this.key,
    required this.providerId,
    required this.model,
    required this.effort,
  });

  @override
  int get hashCode =>
      key.hashCode ^ providerId.hashCode ^ model.hashCode ^ effort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoleSettingsDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          providerId == other.providerId &&
          model == other.model &&
          effort == other.effort;
}

/// Skills 页的 canonical 设置。
class BridgeSkillsSettingsDto {
  final bool enabled;
  final bool autoLearn;
  final bool systemEnabled;
  final String projectDir;
  final String userDir;
  final List<String> externalDirs;
  final List<String> disabled;
  final int autoLearnMinToolCalls;

  const BridgeSkillsSettingsDto({
    required this.enabled,
    required this.autoLearn,
    required this.systemEnabled,
    required this.projectDir,
    required this.userDir,
    required this.externalDirs,
    required this.disabled,
    required this.autoLearnMinToolCalls,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      autoLearn.hashCode ^
      systemEnabled.hashCode ^
      projectDir.hashCode ^
      userDir.hashCode ^
      externalDirs.hashCode ^
      disabled.hashCode ^
      autoLearnMinToolCalls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSkillsSettingsDto &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          autoLearn == other.autoLearn &&
          systemEnabled == other.systemEnabled &&
          projectDir == other.projectDir &&
          userDir == other.userDir &&
          externalDirs == other.externalDirs &&
          disabled == other.disabled &&
          autoLearnMinToolCalls == other.autoLearnMinToolCalls;
}

/// Studio 配置与本地界面设置的 canonical typed 快照。
class BridgeStudioSettingsDto {
  final String? defaultProviderId;
  final List<BridgeProviderSettingsDto> providers;
  final List<BridgeRoleSettingsDto> roles;
  final String permissionMode;
  final BridgeInstructionsSettingsDto instructions;
  final BridgeSkillsSettingsDto skills;
  final List<BridgeMcpServerSettingsDto> mcpServers;
  final BridgeGeneralSettingsDto general;
  final BridgeWebSearchSettingsDto webSearch;
  final BridgeDeepSeekWebSearchSettingsDto deepseekWebSearch;

  const BridgeStudioSettingsDto({
    this.defaultProviderId,
    required this.providers,
    required this.roles,
    required this.permissionMode,
    required this.instructions,
    required this.skills,
    required this.mcpServers,
    required this.general,
    required this.webSearch,
    required this.deepseekWebSearch,
  });

  @override
  int get hashCode =>
      defaultProviderId.hashCode ^
      providers.hashCode ^
      roles.hashCode ^
      permissionMode.hashCode ^
      instructions.hashCode ^
      skills.hashCode ^
      mcpServers.hashCode ^
      general.hashCode ^
      webSearch.hashCode ^
      deepseekWebSearch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioSettingsDto &&
          runtimeType == other.runtimeType &&
          defaultProviderId == other.defaultProviderId &&
          providers == other.providers &&
          roles == other.roles &&
          permissionMode == other.permissionMode &&
          instructions == other.instructions &&
          skills == other.skills &&
          mcpServers == other.mcpServers &&
          general == other.general &&
          webSearch == other.webSearch &&
          deepseekWebSearch == other.deepseekWebSearch;
}

class BridgeWebSearchProviderCapabilitiesDescriptor {
  final bool hostedResponses;
  final String hostedDialect;
  final String? standalone;

  const BridgeWebSearchProviderCapabilitiesDescriptor({
    required this.hostedResponses,
    required this.hostedDialect,
    this.standalone,
  });

  @override
  int get hashCode =>
      hostedResponses.hashCode ^ hostedDialect.hashCode ^ standalone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWebSearchProviderCapabilitiesDescriptor &&
          runtimeType == other.runtimeType &&
          hostedResponses == other.hostedResponses &&
          hostedDialect == other.hostedDialect &&
          standalone == other.standalone;
}

/// Web 搜索配置、有效状态和自动 OpenAI backend 的 canonical bridge 快照。
class BridgeWebSearchSettingsDto {
  final String configuredMode;
  final String effectiveMode;
  final String availability;
  final bool selected;
  final String? contextSize;
  final List<String> allowedDomains;
  final String? country;
  final String? region;
  final String? city;
  final String? timezone;
  final String? providerId;
  final String? model;

  const BridgeWebSearchSettingsDto({
    required this.configuredMode,
    required this.effectiveMode,
    required this.availability,
    required this.selected,
    this.contextSize,
    required this.allowedDomains,
    this.country,
    this.region,
    this.city,
    this.timezone,
    this.providerId,
    this.model,
  });

  @override
  int get hashCode =>
      configuredMode.hashCode ^
      effectiveMode.hashCode ^
      availability.hashCode ^
      selected.hashCode ^
      contextSize.hashCode ^
      allowedDomains.hashCode ^
      country.hashCode ^
      region.hashCode ^
      city.hashCode ^
      timezone.hashCode ^
      providerId.hashCode ^
      model.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWebSearchSettingsDto &&
          runtimeType == other.runtimeType &&
          configuredMode == other.configuredMode &&
          effectiveMode == other.effectiveMode &&
          availability == other.availability &&
          selected == other.selected &&
          contextSize == other.contextSize &&
          allowedDomains == other.allowedDomains &&
          country == other.country &&
          region == other.region &&
          city == other.city &&
          timezone == other.timezone &&
          providerId == other.providerId &&
          model == other.model;
}

/// DeepSeek 原生 Web 搜索开关的 typed bridge 输入。
class DeepSeekWebSearchSettingsInput {
  final bool enabled;

  const DeepSeekWebSearchSettingsInput({required this.enabled});

  @override
  int get hashCode => enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeepSeekWebSearchSettingsInput &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled;
}

class GeneralSettingsInput {
  final bool followSystemTheme;
  final bool followActiveTurn;
  final bool compactTimeline;

  const GeneralSettingsInput({
    required this.followSystemTheme,
    required this.followActiveTurn,
    required this.compactTimeline,
  });

  @override
  int get hashCode =>
      followSystemTheme.hashCode ^
      followActiveTurn.hashCode ^
      compactTimeline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneralSettingsInput &&
          runtimeType == other.runtimeType &&
          followSystemTheme == other.followSystemTheme &&
          followActiveTurn == other.followActiveTurn &&
          compactTimeline == other.compactTimeline;
}

class InstructionsSettingsInput {
  final String baseOverride;
  final String developer;
  final String user;
  final BigInt projectDocMaxBytes;
  final List<String> projectDocFallbackFilenames;

  const InstructionsSettingsInput({
    required this.baseOverride,
    required this.developer,
    required this.user,
    required this.projectDocMaxBytes,
    required this.projectDocFallbackFilenames,
  });

  @override
  int get hashCode =>
      baseOverride.hashCode ^
      developer.hashCode ^
      user.hashCode ^
      projectDocMaxBytes.hashCode ^
      projectDocFallbackFilenames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstructionsSettingsInput &&
          runtimeType == other.runtimeType &&
          baseOverride == other.baseOverride &&
          developer == other.developer &&
          user == other.user &&
          projectDocMaxBytes == other.projectDocMaxBytes &&
          projectDocFallbackFilenames == other.projectDocFallbackFilenames;
}

@freezed
sealed class LspScopeInput with _$LspScopeInput {
  const LspScopeInput._();

  const factory LspScopeInput.server({
    required String projectId,
    required String serverId,
  }) = LspScopeInput_Server;
  const factory LspScopeInput.workspace({required String projectId}) =
      LspScopeInput_Workspace;
  const factory LspScopeInput.all() = LspScopeInput_All;
}

@freezed
sealed class McpResetInput with _$McpResetInput {
  const McpResetInput._();

  const factory McpResetInput.server({required String serverId}) =
      McpResetInput_Server;
  const factory McpResetInput.all() = McpResetInput_All;
}

class McpServerInput {
  final String id;
  final bool enabled;
  final String transport;
  final String endpoint;

  const McpServerInput({
    required this.id,
    required this.enabled,
    required this.transport,
    required this.endpoint,
  });

  @override
  int get hashCode =>
      id.hashCode ^ enabled.hashCode ^ transport.hashCode ^ endpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpServerInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          enabled == other.enabled &&
          transport == other.transport &&
          endpoint == other.endpoint;
}

class McpSettingsInput {
  final List<McpServerInput> servers;

  const McpSettingsInput({required this.servers});

  @override
  int get hashCode => servers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is McpSettingsInput &&
          runtimeType == other.runtimeType &&
          servers == other.servers;
}

class ProviderInput {
  final String id;
  final String? originalId;
  final String templateKind;
  final String name;
  final String baseUrl;
  final ProviderSecretInput secret;
  final bool pricingEnabled;
  final String defaultModel;
  final List<ProviderModelInput> customModels;
  final List<ProviderModelConnectionInput> modelConnectionModes;

  const ProviderInput({
    required this.id,
    this.originalId,
    required this.templateKind,
    required this.name,
    required this.baseUrl,
    required this.secret,
    required this.pricingEnabled,
    required this.defaultModel,
    required this.customModels,
    required this.modelConnectionModes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      originalId.hashCode ^
      templateKind.hashCode ^
      name.hashCode ^
      baseUrl.hashCode ^
      secret.hashCode ^
      pricingEnabled.hashCode ^
      defaultModel.hashCode ^
      customModels.hashCode ^
      modelConnectionModes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          originalId == other.originalId &&
          templateKind == other.templateKind &&
          name == other.name &&
          baseUrl == other.baseUrl &&
          secret == other.secret &&
          pricingEnabled == other.pricingEnabled &&
          defaultModel == other.defaultModel &&
          customModels == other.customModels &&
          modelConnectionModes == other.modelConnectionModes;
}

class ProviderModelConnectionInput {
  final String slug;
  final String connectionMode;

  const ProviderModelConnectionInput({
    required this.slug,
    required this.connectionMode,
  });

  @override
  int get hashCode => slug.hashCode ^ connectionMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderModelConnectionInput &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          connectionMode == other.connectionMode;
}

class ProviderModelInput {
  final String slug;
  final String displayName;
  final String wireProtocol;
  final BigInt contextWindow;
  final BigInt maxOutputTokens;

  const ProviderModelInput({
    required this.slug,
    required this.displayName,
    required this.wireProtocol,
    required this.contextWindow,
    required this.maxOutputTokens,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      displayName.hashCode ^
      wireProtocol.hashCode ^
      contextWindow.hashCode ^
      maxOutputTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderModelInput &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          displayName == other.displayName &&
          wireProtocol == other.wireProtocol &&
          contextWindow == other.contextWindow &&
          maxOutputTokens == other.maxOutputTokens;
}

@freezed
sealed class ProviderSecretInput with _$ProviderSecretInput {
  const ProviderSecretInput._();

  const factory ProviderSecretInput.preserve() = ProviderSecretInput_Preserve;
  const factory ProviderSecretInput.replace({required String value}) =
      ProviderSecretInput_Replace;
  const factory ProviderSecretInput.clear() = ProviderSecretInput_Clear;
}

class ProviderSettingsInput {
  final String defaultProviderId;
  final List<ProviderInput> providers;
  final List<RoleInput> roles;

  const ProviderSettingsInput({
    required this.defaultProviderId,
    required this.providers,
    required this.roles,
  });

  @override
  int get hashCode =>
      defaultProviderId.hashCode ^ providers.hashCode ^ roles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderSettingsInput &&
          runtimeType == other.runtimeType &&
          defaultProviderId == other.defaultProviderId &&
          providers == other.providers &&
          roles == other.roles;
}

class RoleInput {
  final String key;
  final String provider;
  final String model;
  final String effort;

  const RoleInput({
    required this.key,
    required this.provider,
    required this.model,
    required this.effort,
  });

  @override
  int get hashCode =>
      key.hashCode ^ provider.hashCode ^ model.hashCode ^ effort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoleInput &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          provider == other.provider &&
          model == other.model &&
          effort == other.effort;
}

class SkillsSettingsInput {
  final bool enabled;
  final bool autoLearn;
  final bool systemEnabled;
  final String projectDir;
  final String userDir;
  final List<String> externalDirs;
  final List<String> disabled;
  final int autoLearnMinToolCalls;

  const SkillsSettingsInput({
    required this.enabled,
    required this.autoLearn,
    required this.systemEnabled,
    required this.projectDir,
    required this.userDir,
    required this.externalDirs,
    required this.disabled,
    required this.autoLearnMinToolCalls,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      autoLearn.hashCode ^
      systemEnabled.hashCode ^
      projectDir.hashCode ^
      userDir.hashCode ^
      externalDirs.hashCode ^
      disabled.hashCode ^
      autoLearnMinToolCalls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillsSettingsInput &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          autoLearn == other.autoLearn &&
          systemEnabled == other.systemEnabled &&
          projectDir == other.projectDir &&
          userDir == other.userDir &&
          externalDirs == other.externalDirs &&
          disabled == other.disabled &&
          autoLearnMinToolCalls == other.autoLearnMinToolCalls;
}

/// Web 搜索设置的 typed bridge 输入。
class WebSearchSettingsInput {
  final String mode;
  final String? contextSize;
  final List<String> allowedDomains;
  final String? country;
  final String? region;
  final String? city;
  final String? timezone;

  const WebSearchSettingsInput({
    required this.mode,
    this.contextSize,
    required this.allowedDomains,
    this.country,
    this.region,
    this.city,
    this.timezone,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      contextSize.hashCode ^
      allowedDomains.hashCode ^
      country.hashCode ^
      region.hashCode ^
      city.hashCode ^
      timezone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebSearchSettingsInput &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          contextSize == other.contextSize &&
          allowedDomains == other.allowedDomains &&
          country == other.country &&
          region == other.region &&
          city == other.city &&
          timezone == other.timezone;
}
