// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'updater.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

@freezed
sealed class BridgeStudioUpdateEventDto with _$BridgeStudioUpdateEventDto {
  const BridgeStudioUpdateEventDto._();

  const factory BridgeStudioUpdateEventDto.started({required BigInt total}) =
      BridgeStudioUpdateEventDto_Started;
  const factory BridgeStudioUpdateEventDto.progress({
    required BigInt downloaded,
    required BigInt total,
  }) = BridgeStudioUpdateEventDto_Progress;
  const factory BridgeStudioUpdateEventDto.verifying() =
      BridgeStudioUpdateEventDto_Verifying;
  const factory BridgeStudioUpdateEventDto.installerLaunched() =
      BridgeStudioUpdateEventDto_InstallerLaunched;
  const factory BridgeStudioUpdateEventDto.failed({
    required String code,
    required String message,
  }) = BridgeStudioUpdateEventDto_Failed;
}
