[package]
name = "pl-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
sqlite = ["dep:sea-orm", "dep:fs4", "dep:url"]

[dependencies]
serde = { workspace = true, features = ["rc"] }
sea-orm = { workspace = true, optional = true }
fs4 = { workspace = true, optional = true }
url = { workspace = true, optional = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[[test]]
name = "entry_storage"
path = "tests/entry_storage.rs"
required-features = ["sqlite"]
