[package]
name = "pl-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
docker-tools = []

[dependencies]
pl-protocol = { workspace = true }
pl-trace = { workspace = true }
pl-model = { workspace = true }
pl-lsp = { workspace = true }
pl-output = { workspace = true }
pl-patch = { workspace = true }
pl-skill-core = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
secrecy = { workspace = true }
include_dir = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
base64 = { workspace = true }
image = { workspace = true }
which = { workspace = true }
sha2 = { workspace = true }
grep-regex = { workspace = true }
grep-matcher = { workspace = true }
grep-searcher = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
