// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/agent.dart';
import '../types/event.dart';
import '../types/interaction.dart';
import '../types/message.dart';
import '../types/response.dart';
import '../types/runtime.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BridgeStudioEventsResponse> loadStudioEvents({
  required String sessionId,
  PlatformInt64? afterSequence,
  PlatformInt64? limit,
}) => RustLib.instance.api.crateApiStudioHandlersEventsLoadStudioEvents(
  sessionId: sessionId,
  afterSequence: afterSequence,
  limit: limit,
);

Stream<BridgeEventEnvelope> subscribeSessionEvents({
  required String sessionId,
}) => RustLib.instance.api.crateApiStudioHandlersEventsSubscribeSessionEvents(
  sessionId: sessionId,
);

Stream<BridgeEventEnvelope> subscribeGlobalEvents() =>
    RustLib.instance.api.crateApiStudioHandlersEventsSubscribeGlobalEvents();
