[workspace]
members = [
    "code/*",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
bitflags = { version = "2", features = ["serde"] }
reqwest = { version = "0.13", features = ["json", "stream"] }
eventsource-stream = "0.2"
clap = { version = "4", features = ["derive"] }
toml = "0.8"

pl-protocol = { path = "code/pl-protocol" }
pl-core = { path = "code/pl-core" }
pl-model = { path = "code/pl-model" }
