//! Dependency types required to construct and consume the complete core interface.
pub use pl_protocol::ToolApprovalRequest as InteractionToolApprovalRequest;
pub use pl_protocol::{
    AGENT_SESSION_PLAN_CONFIRMATION_QUESTION_ID, AgentProfileSnapshot,
    AgentSessionPlanAvailableTransition, AgentSessionPlanConfirmationPurpose,
    AgentSessionPlanDocument, AgentSessionPlanMutationResponse, AgentSessionPlanOperation,
    AgentSessionPlanOperationReceipt, AgentSessionPlanPhase, AgentSessionPlanResultCode,
    AgentSessionPlanSnapshot, AgentSessionPlanState, AgentSessionPlanTransitionActor,
    AgentSessionPlanTransitionError, AgentSessionPlanTransitionRecord, AgentSessionSnapshot,
    AgentWorkingState, AgentWorkspaceAssignmentSnapshot, AgentWorkspaceDisposition,
    AgentWorkspaceMode, AgentWorktreeSnapshot, ApprovedThreadTool, AwaitingApprovalThreadTool,
    BudgetLimitSnapshot, BudgetLimitedTurnState, CancelInteraction, CancelledThreadAgent,
    CancelledThreadInference, CancelledThreadTool, CancelledTurnState, CompletedThreadInference,
    CompletedTurnState, ConversationRecoveryMode, ConversationRecoveryRecord,
    ConversationRecoveryState, ConversationRecoveryTurnRange, CredentialDescriptorDto,
    DeniedThreadAgent, DeniedThreadTool, FailedThreadAgent, FailedThreadInference,
    FailedThreadTool, FailedTurnState, HostedWebSearchDialect, HostedWebSearchOptions,
    InferenceAccounting, InferenceBillingAppend, InferenceBillingRecord,
    InferenceOrchestrationMetrics, InferenceTiming, InferenceTokenUsage, InteractionCommand,
    InteractionContinuationInput, InteractionContinuationPreset, InteractionPurpose, LabeledEnum,
    ModelCapabilitiesDto, ModelCatalogDescriptor, ModelContextSectionSnapshot,
    ModelContextSnapshot, ModelDescriptor, ModelInputCapabilityDto, ModelInputSourceDto,
    ModelModalityDto, ModelPricingSnapshot, ModelReasoningDescriptor, ModelTransportDescriptor,
    ObservedResource, ObservedResourceCommand, ObservedResourceKind,
    PROVIDER_CATALOG_SCHEMA_VERSION, PricingMode, PricingOutcome, PromptPrefixChangedReason,
    ProviderFailureKind, QueuedThreadAgent, QueuedTurnState, ReopenRecoveredInteraction,
    ResolveToolApproval, ResolveUserInput, ResponsesContextItem, ResponsesContextItemKind,
    RunningThreadAgent, RunningThreadInference, RunningThreadTool, RunningTurnState, SessionEntry,
    SessionNote, SkillActivationCause, SkillActivationResourceBase, StartedThreadTool, StateError,
    StateOperation, StreamingThreadTool, SucceededThreadAgent, SucceededThreadTool,
    THREAD_SCHEMA_VERSION, Thread, ThreadAgentIdentity, ThreadAgentItem, ThreadAgentState,
    ThreadAttachment, ThreadContentLifecycle, ThreadContextCompactionItem,
    ThreadContextDisposition, ThreadFileItem, ThreadInferenceItem, ThreadInferenceState,
    ThreadItemDelta, ThreadItemDeltaState, ThreadItemKind, ThreadItemState, ThreadPromptMetadata,
    ThreadPromptSnapshot, ThreadRuntimeSnapshot, ThreadRuntimeUsage, ThreadSkillItem, ThreadStatus,
    ThreadSubscriptionRequest, ThreadSubscriptionUpdate, ThreadTextChannel, ThreadTextItem,
    ThreadThinkingItem, ThreadToolFailure, ThreadToolFailureKind, ThreadToolInvocation,
    ThreadToolItem, ThreadToolOutput, ThreadToolState, ThreadTurnItem, TodoItem, TodoListSnapshot,
    TodoStatus, ToolApprovalResolutionPayload, ToolCallCaller, ToolCallKind, ToolCallRecord,
    ToolCallerMode, ToolMediaContext, ToolResultRecord, TurnBillingRecord, TurnCancellationCause,
    TurnCompletion, TurnOutcome, TurnPhase, TurnRolloverOutcome, TurnState, UnknownLabelError,
    UnpricedReason, UsageReport, UserInputResolution, WebSearchContextSize, WebSearchFilters,
    WebSearchProviderCapabilitiesDescriptor, WebSearchResolutionDescriptor, WebSearchUserLocation,
    WorkflowOperationReceipt, WorkflowRun, WorkflowRunArchive, WorkflowRunLifecycle,
    WorkflowRuntimeSnapshot, WorkflowSessionState, WorkflowTransitionRecord,
};
