// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../subscription.dart';
import '../types/error.dart';
import '../types/product_topic.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 订阅一个 typed 产品 topic。
///
/// 一次订阅只观察一个领域：runtime 先登记该 topic 的接收者，再读取领域基线；本模块
/// producer 把首帧 `Baseline` 与后续事件转发给 Dart sink，`Lagged` 帧提示客户端仅重读
/// 该 topic 的基线（无 durable replay）。
Future<BridgeEventSubscription> createProductTopicSubscription({
  required BridgeProductTopic topic,
}) => RustLib.instance.api
    .crateApiStudioSubscriptionProductTopicCreateProductTopicSubscription(
      topic: topic,
    );
