// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/attachment.dart';
import '../types/chat.dart';
import '../types/error.dart';
import '../types/thread_stream.dart';
import '../types/thread_stream/item.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_focus`, `bridge_item`, `bridge_snapshot`, `bridge_update`, `core_focus`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

Future<BridgeChatView> openChatView({
  required String threadId,
  required BridgeChatFocus focus,
}) => RustLib.instance.api.crateApiStudioHandlersChatOpenChatView(
  threadId: threadId,
  focus: focus,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeChatView>>
abstract class BridgeChatView implements RustOpaqueInterface {
  Future<void> close();

  Future<BridgeChatSnapshot> focus({required BridgeChatFocus focus});

  /// The subscription baseline is captured before returning the handle.
  Future<BridgeChatSnapshot> initial();

  Future<BridgeChatSnapshot> load({required BridgeChatDirection direction});

  /// Waits for one consolidated batch, then returns control to the consumer.
  Future<BridgeChatUpdate?> next();

  Future<BridgeChatItem?> readItem({required String itemId});

  Future<BridgeChatSnapshot> snapshot();
}
