// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/runtime.dart';
import '../types/shutdown.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attempt_active`, `begin_shutdown`, `begin_start`, `bridge_early_issues_slot`, `bridge_issue`, `bridge_startup_stage`, `disarm`, `fail_start`, `finish_start`, `lock`, `new`, `new`, `prepare`, `publish_stage`, `publish_startup_stage`, `record_bridge_early_issues`, `record_shutdown_report`, `remaining_ms_u32`, `shutdown_runtime_for_update`, `startup_attempt_active`, `subscribe_startup_attempt`, `subscribe`, `take_bridge_early_issues`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StartClaim`, `StartupDemote`, `StartupFrame`, `StartupOwner`, `StartupPhase`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// 发放一次新的启动尝试令牌；可在 bridge 安装前（pre-installed）调用。
///
/// 同一时刻只有一个活跃令牌：start 在途期间明确拒绝；已 Ready（runtime 运行中）同样
/// 拒绝——重启前必须先 shutdown。新令牌发放后旧令牌立即过期。shutdown 开始后本进程
/// 不再支持新的启动尝试：bridge 的 OnceCell 与 shutdown 令牌都是一次性资源。
Future<BigInt> prepareStartupAttempt() =>
    RustLib.instance.api.crateApiStudioHandlersLifecyclePrepareStartupAttempt();

/// 以指定令牌启动 Studio runtime。
///
/// `attempt` 必须是 [`prepare_startup_attempt`] 发放且未过期的令牌；在途期间的重复
/// start、旧令牌与失败/停机后的复用都被明确拒绝。已 Ready 的同令牌调用幂等成功：
/// 返回前核对真实 runtime 仍处于 Ready 且 shutdown 未开始，否则以 `runtime_stopped`
/// 明确失败而不是虚报快照；不重开 runtime、不虚发 `OpeningStorage`，进度流保持
/// `Ready` 终态。start 在途的失败与任务取消都把本尝试落为 `Failed` 终态，不会永久
/// 卡在 in-progress。
Future<RuntimeSnapshot> startStudioRuntime({required BigInt attempt}) => RustLib
    .instance
    .api
    .crateApiStudioHandlersLifecycleStartStudioRuntime(attempt: attempt);

/// Early application-exit entry: seal the one-way exit latch and fence the installed runtime
/// **before** the caller performs its own bounded cancellations.
///
/// The native host owns the single 30s deadline. When the first close arrives it must call this
/// entry first so that Rust stops admitting new work immediately, instead of waiting until the
/// Dart-side product/Thread/progress cancellations have all settled before the first
/// `shutdown_runtime` call. This entry:
///
/// - arms the bridge exit latch synchronously (never waiting on the lifecycle gate), so a late
///   `start_studio_runtime` can never publish a runtime once exit has begun;
/// - fixes the single first deadline from the caller's remaining cleanup budget, so a later
///   `shutdown_runtime` never extends it;
/// - invalidates the startup attempt token synchronously (before any await and independent of an
///   installed runtime) and wakes a pre-active startup observer, so a concurrent attempt can never
///   publish a runtime once exit has begun;
/// - when a runtime is already installed, synchronously fences domain admission and broadcasts
///   cancellation to the runtime's independent owners.
///
/// It never triggers initialization (an uninstalled runtime stays `NotStarted` for the final
/// report), never runs the real service stops/joins, never publishes `Stopped` and never releases
/// the instance lock. Those remain the job of the single `shutdown_runtime` orchestration, which
/// folds the same bridge/external issues into the same collector. Failures observed here are kept
/// on the runtime's early-exit slot and logged; they are neither swallowed nor faked as success.
///
/// `remaining_ms` is the caller's remaining cleanup budget (native's single deadline minus the
/// time already spent), not a fresh window.
Future<void> beginRuntimeExit({required int remainingMs}) => RustLib
    .instance
    .api
    .crateApiStudioHandlersLifecycleBeginRuntimeExit(remainingMs: remainingMs);

/// Application-exit shutdown with a caller-supplied cleanup budget in milliseconds.
///
/// The desktop host owns the single 30s deadline and passes its remaining cleanup time; this
/// entry caps it at 28s, never extends the deadline, and returns a typed report even when the
/// run is `Degraded` or times out.
///
/// The one-way exit latch is closed synchronously before any await, so a late install can never
/// publish a runtime even if initialization is hanging and the lifecycle gate cannot be taken.
/// Every exit step (latch, gate observation, subscription/update cancellation, runtime stages and
/// diagnostics) shares this single first deadline; repeated close never extends it.
///
/// `external_issues` carries the cancellations the caller (native host / Dart) already performed
/// and observed before this call — bridge- and Dart-owned subscriptions (including the shutdown
/// progress stream) and update operations whose owner did not confirm. They are fed into the
/// **same** runtime shutdown orchestration as success preconditions, so the runtime itself refuses
/// `Clean`, never publishes `Stopped` and never releases the instance lock when any owner is
/// unresolved. There is no post-hoc report merge and no second cleanup path.
Future<BridgeShutdownReport> shutdownRuntime({
  required int remainingMs,
  required List<BridgeShutdownIssue> externalIssues,
}) => RustLib.instance.api.crateApiStudioHandlersLifecycleShutdownRuntime(
  remainingMs: remainingMs,
  externalIssues: externalIssues,
);

/// Finalizes diagnostics independent of runtime initialization.
///
/// Idempotent and safe without an installed runtime; the GUI calls it before a safe dispose or
/// before exiting so diagnostics are flushed even when startup never completed. The synchronous
/// flush (which joins the non-blocking log worker) runs on the blocking pool so it cannot hold a
/// Tokio worker or the cleanup deadline while runtime owners are still being polled.
Future<void> finishShutdownDiagnostics() => RustLib.instance.api
    .crateApiStudioHandlersLifecycleFinishShutdownDiagnostics();

Future<ProjectDto> openProject({required String path}) =>
    RustLib.instance.api.crateApiStudioHandlersLifecycleOpenProject(path: path);

Future<void> activateProject({required String projectId}) => RustLib
    .instance
    .api
    .crateApiStudioHandlersLifecycleActivateProject(projectId: projectId);

Future<ProjectDto?> archiveProject({required String projectId}) => RustLib
    .instance
    .api
    .crateApiStudioHandlersLifecycleArchiveProject(projectId: projectId);

/// Changes a Project display name, preserving its path and connection.
Future<ProjectDto> renameProject({
  required String projectId,
  required String name,
}) => RustLib.instance.api.crateApiStudioHandlersLifecycleRenameProject(
  projectId: projectId,
  name: name,
);

Future<BridgeRecoveryStateSnapshot> readRecoveryState() =>
    RustLib.instance.api.crateApiStudioHandlersLifecycleReadRecoveryState();

Future<BridgeRecoveryStateSnapshot> retryRecovery() =>
    RustLib.instance.api.crateApiStudioHandlersLifecycleRetryRecovery();
