// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/runtime.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 跳过当前退避并立即重试保存积压的内存事实。
Future<BridgePersistenceStateSnapshot> retryPersistence() =>
    RustLib.instance.api.crateApiStudioHandlersPersistenceRetryPersistence();

/// Retry exactly one latched Thread fault; returns only after its fixed save fence is confirmed.
Future<BridgePersistenceQueueSnapshot> retryThreadHistory({
  required String threadId,
  required BigInt faultGeneration,
}) => RustLib.instance.api.crateApiStudioHandlersPersistenceRetryThreadHistory(
  threadId: threadId,
  faultGeneration: faultGeneration,
);

/// 显式继续：在保存重试已按同一代数确认后再解除准入闩，让下一轮模型/工具工作可以开始。
///
/// 与 [`retry_thread_history`] 是两个动作：重试只把积压事实写下去，本命令才恢复执行。代数过期、
/// 后端仍在上报故障或仍有未上交批次时会失败，调用方必须按 typed 存储状态重试而不是假定成功。
Future<BridgePersistenceQueueSnapshot> resumeThreadHistory({
  required String threadId,
  required BigInt faultGeneration,
}) => RustLib.instance.api.crateApiStudioHandlersPersistenceResumeThreadHistory(
  threadId: threadId,
  faultGeneration: faultGeneration,
);

/// 读取进程级持久化队列压力与逐 Thread 水位。
///
/// 返回协调器已观测到的真实值：队列操作数、字节、在途字节、最老待保存年龄与最近错误，
/// 以及每个 Thread 的 checkpoint/history/calls 水位。纯读取，不触发写入、重试或恢复。
Future<BridgePersistenceQueueSnapshot> readPersistenceQueue() => RustLib
    .instance
    .api
    .crateApiStudioHandlersPersistenceReadPersistenceQueue();
