// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/runtime.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `owned_skills_state`, `provider_usage_state`, `skills_state`

Future<BridgeProviderUsageStateSnapshot> readProviderUsageState() => RustLib
    .instance
    .api
    .crateApiStudioHandlersProvidersReadProviderUsageState();

Future<BridgeProviderUsageStateSnapshot> checkProviderUsage() =>
    RustLib.instance.api.crateApiStudioHandlersProvidersCheckProviderUsage();

Future<BridgeSkillsStateSnapshot> readSkillsState({
  required String projectId,
}) => RustLib.instance.api.crateApiStudioHandlersProvidersReadSkillsState(
  projectId: projectId,
);

Future<BridgeSkillsStateSnapshot> discoverSkills({required String projectId}) =>
    RustLib.instance.api.crateApiStudioHandlersProvidersDiscoverSkills(
      projectId: projectId,
    );

Future<BridgeSkillSearchResult> searchSkills({
  required String projectId,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiStudioHandlersProvidersSearchSkills(
  projectId: projectId,
  query: query,
  limit: limit,
);
