// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/ssh.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connection_dto`, `server_dto`

Future<List<SshServerDto>> listSshServers() =>
    RustLib.instance.api.crateApiStudioHandlersSshListSshServers();

Future<SshServerDto> saveSshServer({required SaveSshServerRequest request}) =>
    RustLib.instance.api.crateApiStudioHandlersSshSaveSshServer(
      request: request,
    );

Future<void> deleteSshServer({required String serverId}) => RustLib.instance.api
    .crateApiStudioHandlersSshDeleteSshServer(serverId: serverId);

Future<SshConnectionSnapshotDto> testSshConnection({
  required String serverId,
}) => RustLib.instance.api.crateApiStudioHandlersSshTestSshConnection(
  serverId: serverId,
);

Future<SshConnectionSnapshotDto> reconnectSshServer({
  required String serverId,
}) => RustLib.instance.api.crateApiStudioHandlersSshReconnectSshServer(
  serverId: serverId,
);

Future<RemoteDirectoryListingDto> browseRemoteDirectories({
  required String serverId,
  String? path,
}) => RustLib.instance.api.crateApiStudioHandlersSshBrowseRemoteDirectories(
  serverId: serverId,
  path: path,
);

Future<ProjectDto> openRemoteProject({
  required String serverId,
  required String path,
}) => RustLib.instance.api.crateApiStudioHandlersSshOpenRemoteProject(
  serverId: serverId,
  path: path,
);
