import 'package:flutter/material.dart';

import 'studio_semantic_colors.dart';

/// Canonical palette. Widgets consume Material roles, never these literals.
ColorScheme siameseColorScheme() => ColorScheme.fromSeed(
  seedColor: const Color(0xff514039),
  brightness: Brightness.light,
  primary: const Color(0xff514039),
  onPrimary: const Color(0xfff6f0e7),
  primaryContainer: const Color(0xffe1d4c5),
  onPrimaryContainer: const Color(0xff40362f),
  primaryFixed: const Color(0xffe1d4c5),
  primaryFixedDim: const Color(0xffd9cab9),
  onPrimaryFixed: const Color(0xff40362f),
  onPrimaryFixedVariant: const Color(0xff514039),
  secondary: const Color(0xff66584e),
  onSecondary: const Color(0xfff6f0e7),
  secondaryContainer: const Color(0xffe1d4c5),
  onSecondaryContainer: const Color(0xff40362f),
  secondaryFixed: const Color(0xffe1d4c5),
  secondaryFixedDim: const Color(0xffd9cab9),
  onSecondaryFixed: const Color(0xff40362f),
  onSecondaryFixedVariant: const Color(0xff514039),
  tertiary: const Color(0xff685449),
  onTertiary: const Color(0xfff6f0e7),
  tertiaryContainer: const Color(0xffe7ded2),
  onTertiaryContainer: const Color(0xff40362f),
  tertiaryFixed: const Color(0xffe7ded2),
  tertiaryFixedDim: const Color(0xffd9cab9),
  onTertiaryFixed: const Color(0xff40362f),
  onTertiaryFixedVariant: const Color(0xff514039),
  surface: const Color(0xfff3ede3),
  surfaceDim: const Color(0xffe7ded2),
  surfaceBright: const Color(0xfff6f0e7),
  surfaceContainerLowest: const Color(0xfff6f0e7),
  surfaceContainerLow: const Color(0xffefe6da),
  surfaceContainer: const Color(0xffe7ded2),
  surfaceContainerHigh: const Color(0xffe1d4c5),
  surfaceContainerHighest: const Color(0xffd9cab9),
  onSurface: const Color(0xff40362f),
  onSurfaceVariant: const Color(0xff66584e),
  outline: const Color(0xff8a7a6c),
  outlineVariant: const Color(0xffd8cdbf),
  error: const Color(0xff914447),
  onError: const Color(0xfff6f0e7),
  errorContainer: const Color(0xfff3e0dd),
  onErrorContainer: const Color(0xff914447),
  inverseSurface: const Color(0xff40362f),
  onInverseSurface: const Color(0xfff6f0e7),
  inversePrimary: const Color(0xffe1d4c5),
  surfaceTint: Colors.transparent,
  shadow: const Color(0xff40362f),
  scrim: const Color(0xff40362f),
);

const siameseSemanticColors = StudioSemanticColors(
  eyeAccent: Color(0xff6f94a8),
  activeIndicator: Color(0xff55798c),
  success: Color(0xff42604c),
  successContainer: Color(0xffe5ebe2),
  warning: Color(0xff795625),
  warningContainer: Color(0xfff0e3cd),
);
