// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'attachment.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'thread_stream.dart';
import 'thread_stream/item.dart';
part 'chat.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

enum BridgeChatDirection { older, newer }

@freezed
sealed class BridgeChatFocus with _$BridgeChatFocus {
  const BridgeChatFocus._();

  const factory BridgeChatFocus.latest() = BridgeChatFocus_Latest;
  const factory BridgeChatFocus.around({required String itemId}) =
      BridgeChatFocus_Around;
}

class BridgeChatItem {
  final BridgeThreadItem item;
  final bool saved;

  /// Bytes omitted from the canonical body in a bounded window preview.
  final BigInt omittedBytes;

  const BridgeChatItem({
    required this.item,
    required this.saved,
    required this.omittedBytes,
  });

  @override
  int get hashCode => item.hashCode ^ saved.hashCode ^ omittedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeChatItem &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          saved == other.saved &&
          omittedBytes == other.omittedBytes;
}

class BridgeChatSnapshot {
  final BridgeChatFocus focus;
  final BigInt version;
  final List<BridgeChatItem> items;
  final bool hasOlder;
  final bool hasNewer;

  const BridgeChatSnapshot({
    required this.focus,
    required this.version,
    required this.items,
    required this.hasOlder,
    required this.hasNewer,
  });

  @override
  int get hashCode =>
      focus.hashCode ^
      version.hashCode ^
      items.hashCode ^
      hasOlder.hashCode ^
      hasNewer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeChatSnapshot &&
          runtimeType == other.runtimeType &&
          focus == other.focus &&
          version == other.version &&
          items == other.items &&
          hasOlder == other.hasOlder &&
          hasNewer == other.hasNewer;
}

@freezed
sealed class BridgeChatUpdate with _$BridgeChatUpdate {
  const BridgeChatUpdate._();

  const factory BridgeChatUpdate.reset({required BridgeChatSnapshot snapshot}) =
      BridgeChatUpdate_Reset;
  const factory BridgeChatUpdate.patch({
    required BigInt from,
    required BigInt to,
    required List<BridgeViewChange> changes,
    required bool hasNewer,
  }) = BridgeChatUpdate_Patch;
}

@freezed
sealed class BridgeViewChange with _$BridgeViewChange {
  const BridgeViewChange._();

  const factory BridgeViewChange.splice({
    required BigInt index,
    required BigInt remove,
    required List<BridgeChatItem> items,
  }) = BridgeViewChange_Splice;
  const factory BridgeViewChange.appendText({
    required String itemId,
    required String partId,
    required BigInt expectedRevision,
    required BigInt revision,
    required String text,
  }) = BridgeViewChange_AppendText;
}
