// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'shutdown.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `is_clean`, `not_started`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class BridgePendingPersistence with _$BridgePendingPersistence {
  const BridgePendingPersistence._();

  const factory BridgePendingPersistence.unknown() =
      BridgePendingPersistence_Unknown;
  const factory BridgePendingPersistence.pending({required BigInt count}) =
      BridgePendingPersistence_Pending;
  const factory BridgePendingPersistence.drained() =
      BridgePendingPersistence_Drained;
}

/// One aggregated shutdown-stage diagnostic.
class BridgeShutdownIssue {
  final String stage;
  final String code;
  final String message;
  final bool retryable;
  final String correlationId;

  const BridgeShutdownIssue({
    required this.stage,
    required this.code,
    required this.message,
    required this.retryable,
    required this.correlationId,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      code.hashCode ^
      message.hashCode ^
      retryable.hashCode ^
      correlationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShutdownIssue &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          code == other.code &&
          message == other.message &&
          retryable == other.retryable &&
          correlationId == other.correlationId;
}

/// Shutdown result classification.
enum BridgeShutdownOutcome { notStarted, clean, degraded }

/// Result of `shutdown_runtime(remaining_ms)`.
class BridgeShutdownReport {
  final BridgeShutdownOutcome outcome;
  final List<BridgeShutdownIssue> issues;
  final BridgePendingPersistence persistence;

  const BridgeShutdownReport({
    required this.outcome,
    required this.issues,
    required this.persistence,
  });

  @override
  int get hashCode => outcome.hashCode ^ issues.hashCode ^ persistence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeShutdownReport &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          issues == other.issues &&
          persistence == other.persistence;
}
