// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'types/error.dart';
import 'types/event.dart';
import 'types/response.dart';
import 'types/runtime.dart';
import 'types/settings.dart';
import 'types/thread_activity.dart';
import 'types/thread_stream.dart';
import 'types/updater.dart';
part 'subscription.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_shutdown_progress`, `cancel_all`, `cancel_and_wait`, `new`, `next_id`, `register`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeSubscriptionInner`, `BridgeSubscriptionKind`, `BridgeTaskRegistry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `drop`, `fmt`, `fmt`, `fmt`

/// 订阅一个 Thread 的**状态流**：Turn、活动、交互、运行时与 lagged 帧。
///
/// 内容不在状态流里：条目与流式正文只由 ChatView 窗口交付。内容帧的过滤发生在生产端
/// （runtime 的状态流不再转发 `Item*`/`Delta`），所以这里没有“末端丢弃内容帧”的开关，客户端
/// 也不会再因为过滤内容帧而看到 revision 空洞。状态流的 envelope `revision` 只按状态帧递增，
/// 与 ChatView 窗口的内容 revision 相互独立。
Future<BridgeEventSubscription> subscribeThread({required String threadId}) =>
    RustLib.instance.api.crateApiStudioSubscriptionSubscribeThread(
      threadId: threadId,
    );

Future<BridgeEventSubscription> createProductSubscription() =>
    RustLib.instance.api.crateApiStudioSubscriptionCreateProductSubscription();

/// Creates an independently owned shutdown-progress subscription, including during retry.
///
/// The caller cancels this handle before cancelling its Dart stream, so failed shutdown
/// does not leave stream cancellation waiting for a future progress event.
Future<BridgeEventSubscription> subscribeShutdownProgress() =>
    RustLib.instance.api.crateApiStudioSubscriptionSubscribeShutdownProgress();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeEventSubscription>>
abstract class BridgeEventSubscription implements RustOpaqueInterface {
  Future<void> cancel();

  Stream<BridgeProductStreamEnvelope> productStream();

  /// Opens this shutdown subscription once. Cancellation closes the native sink.
  ///
  /// # Errors
  /// Rejects another subscription kind or a second stream consumer.
  Stream<BridgeShutdownProgress> shutdownStream();

  Stream<BridgeThreadStreamEnvelope> threadStream();
}

@freezed
sealed class BridgeProductStreamEnvelope with _$BridgeProductStreamEnvelope {
  const BridgeProductStreamEnvelope._();

  const factory BridgeProductStreamEnvelope.data({
    required BridgeProductEventEnvelope event,
  }) = BridgeProductStreamEnvelope_Data;
  const factory BridgeProductStreamEnvelope.failure({
    required BridgeError error,
  }) = BridgeProductStreamEnvelope_Failure;
  const factory BridgeProductStreamEnvelope.closed() =
      BridgeProductStreamEnvelope_Closed;
}

@freezed
sealed class BridgeThreadStreamEnvelope with _$BridgeThreadStreamEnvelope {
  const BridgeThreadStreamEnvelope._();

  const factory BridgeThreadStreamEnvelope.data({
    required BridgeThreadSubscriptionUpdate update,
  }) = BridgeThreadStreamEnvelope_Data;
  const factory BridgeThreadStreamEnvelope.failure({
    required BridgeError error,
  }) = BridgeThreadStreamEnvelope_Failure;
  const factory BridgeThreadStreamEnvelope.closed() =
      BridgeThreadStreamEnvelope_Closed;
}
