[package]
name = "pure-studio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
pl-core = { workspace = true }
pl-protocol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
tauri-plugin-dialog = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
