// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'agent.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

class BridgeAgentSnapshotDto {
  final String id;
  final String sessionId;
  final String path;
  final String? parentPath;
  final String role;
  final String task;
  final String status;
  final String? summary;
  final int depth;
  final String? error;
  final String? reason;
  final PlatformInt64 updatedAt;

  const BridgeAgentSnapshotDto({
    required this.id,
    required this.sessionId,
    required this.path,
    this.parentPath,
    required this.role,
    required this.task,
    required this.status,
    this.summary,
    required this.depth,
    this.error,
    this.reason,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sessionId.hashCode ^
      path.hashCode ^
      parentPath.hashCode ^
      role.hashCode ^
      task.hashCode ^
      status.hashCode ^
      summary.hashCode ^
      depth.hashCode ^
      error.hashCode ^
      reason.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAgentSnapshotDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sessionId == other.sessionId &&
          path == other.path &&
          parentPath == other.parentPath &&
          role == other.role &&
          task == other.task &&
          status == other.status &&
          summary == other.summary &&
          depth == other.depth &&
          error == other.error &&
          reason == other.reason &&
          updatedAt == other.updatedAt;
}

class BridgeAgentTimelineEventDto {
  final String eventId;
  final String sessionId;
  final BigInt sequence;
  final PlatformInt64 createdAt;
  final BridgeAgentTimelinePayloadDto payload;

  const BridgeAgentTimelineEventDto({
    required this.eventId,
    required this.sessionId,
    required this.sequence,
    required this.createdAt,
    required this.payload,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      sessionId.hashCode ^
      sequence.hashCode ^
      createdAt.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAgentTimelineEventDto &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          sessionId == other.sessionId &&
          sequence == other.sequence &&
          createdAt == other.createdAt &&
          payload == other.payload;
}

class BridgeTodoListSnapshotDto {
  final String callId;
  final String? agentId;
  final String? path;
  final String? parentPath;
  final String? explanation;
  final List<BridgeTodoItemDto> items;

  const BridgeTodoListSnapshotDto({
    required this.callId,
    this.agentId,
    this.path,
    this.parentPath,
    this.explanation,
    required this.items,
  });

  @override
  int get hashCode =>
      callId.hashCode ^
      agentId.hashCode ^
      path.hashCode ^
      parentPath.hashCode ^
      explanation.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTodoListSnapshotDto &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          agentId == other.agentId &&
          path == other.path &&
          parentPath == other.parentPath &&
          explanation == other.explanation &&
          items == other.items;
}

class BridgeTodoItemDto {
  final String step;
  final String status;

  const BridgeTodoItemDto({required this.step, required this.status});

  @override
  int get hashCode => step.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTodoItemDto &&
          runtimeType == other.runtimeType &&
          step == other.step &&
          status == other.status;
}

@freezed
sealed class BridgeAgentTimelinePayloadDto
    with _$BridgeAgentTimelinePayloadDto {
  const BridgeAgentTimelinePayloadDto._();

  const factory BridgeAgentTimelinePayloadDto.subAgentActivity({
    required String callId,
    String? agentId,
    String? path,
    String? parentPath,
    required String kind,
    String? status,
    String? message,
    required bool timedOut,
    String? error,
  }) = BridgeAgentTimelinePayloadDto_SubAgentActivity;

  const factory BridgeAgentTimelinePayloadDto.todoListUpdated({
    required BridgeTodoListSnapshotDto snapshot,
  }) = BridgeAgentTimelinePayloadDto_TodoListUpdated;
}
