// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BridgeStudioAgentPartDto {
  final String id;
  final String path;
  final String? parentPath;
  final String role;
  final String task;
  final String status;
  final String? summary;
  final int depth;
  final String? error;
  final String? reason;

  const BridgeStudioAgentPartDto({
    required this.id,
    required this.path,
    this.parentPath,
    required this.role,
    required this.task,
    required this.status,
    this.summary,
    required this.depth,
    this.error,
    this.reason,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      parentPath.hashCode ^
      role.hashCode ^
      task.hashCode ^
      status.hashCode ^
      summary.hashCode ^
      depth.hashCode ^
      error.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioAgentPartDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          parentPath == other.parentPath &&
          role == other.role &&
          task == other.task &&
          status == other.status &&
          summary == other.summary &&
          depth == other.depth &&
          error == other.error &&
          reason == other.reason;
}

class BridgeStudioMessageDto {
  final String messageId;
  final String sessionId;
  final String turnId;
  final String role;
  final String status;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? completedAt;
  final String? error;

  const BridgeStudioMessageDto({
    required this.messageId,
    required this.sessionId,
    required this.turnId,
    required this.role,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
    this.completedAt,
    this.error,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      sessionId.hashCode ^
      turnId.hashCode ^
      role.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      completedAt.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioMessageDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          sessionId == other.sessionId &&
          turnId == other.turnId &&
          role == other.role &&
          status == other.status &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          completedAt == other.completedAt &&
          error == other.error;
}

class BridgeStudioPartDeltaDto {
  final String partId;
  final BigInt revision;
  final String field;
  final String delta;
  final int? chunkIndex;

  const BridgeStudioPartDeltaDto({
    required this.partId,
    required this.revision,
    required this.field,
    required this.delta,
    this.chunkIndex,
  });

  @override
  int get hashCode =>
      partId.hashCode ^
      revision.hashCode ^
      field.hashCode ^
      delta.hashCode ^
      chunkIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioPartDeltaDto &&
          runtimeType == other.runtimeType &&
          partId == other.partId &&
          revision == other.revision &&
          field == other.field &&
          delta == other.delta &&
          chunkIndex == other.chunkIndex;
}

class BridgeStudioPartDto {
  final String partId;
  final String messageId;
  final String sessionId;
  final String turnId;
  final String partType;
  final BigInt order;
  final BigInt revision;
  final String status;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64? completedAt;
  final String? error;
  final String? textChannel;
  final String? activityGroupId;
  final String text;
  final BridgeStudioToolPartDto? tool;
  final BridgeStudioAgentPartDto? agent;
  final BridgeStudioPlanPartDto? plan;
  final bool synthetic;
  final bool ignored;

  const BridgeStudioPartDto({
    required this.partId,
    required this.messageId,
    required this.sessionId,
    required this.turnId,
    required this.partType,
    required this.order,
    required this.revision,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
    this.completedAt,
    this.error,
    this.textChannel,
    this.activityGroupId,
    required this.text,
    this.tool,
    this.agent,
    this.plan,
    required this.synthetic,
    required this.ignored,
  });

  @override
  int get hashCode =>
      partId.hashCode ^
      messageId.hashCode ^
      sessionId.hashCode ^
      turnId.hashCode ^
      partType.hashCode ^
      order.hashCode ^
      revision.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      completedAt.hashCode ^
      error.hashCode ^
      textChannel.hashCode ^
      activityGroupId.hashCode ^
      text.hashCode ^
      tool.hashCode ^
      agent.hashCode ^
      plan.hashCode ^
      synthetic.hashCode ^
      ignored.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioPartDto &&
          runtimeType == other.runtimeType &&
          partId == other.partId &&
          messageId == other.messageId &&
          sessionId == other.sessionId &&
          turnId == other.turnId &&
          partType == other.partType &&
          order == other.order &&
          revision == other.revision &&
          status == other.status &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          completedAt == other.completedAt &&
          error == other.error &&
          textChannel == other.textChannel &&
          activityGroupId == other.activityGroupId &&
          text == other.text &&
          tool == other.tool &&
          agent == other.agent &&
          plan == other.plan &&
          synthetic == other.synthetic &&
          ignored == other.ignored;
}

class BridgeStudioPlanPartDto {
  final String content;

  const BridgeStudioPlanPartDto({required this.content});

  @override
  int get hashCode => content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioPlanPartDto &&
          runtimeType == other.runtimeType &&
          content == other.content;
}

class BridgeStudioToolPartDto {
  final String toolCallId;
  final String? callId;
  final String? providerItemId;
  final String name;
  final String arguments;
  final String? result;
  final String outputArtifactsJson;
  final int? exitCode;
  final bool timedOut;
  final String? workingDirectory;
  final String? denialReason;

  const BridgeStudioToolPartDto({
    required this.toolCallId,
    this.callId,
    this.providerItemId,
    required this.name,
    required this.arguments,
    this.result,
    required this.outputArtifactsJson,
    this.exitCode,
    required this.timedOut,
    this.workingDirectory,
    this.denialReason,
  });

  @override
  int get hashCode =>
      toolCallId.hashCode ^
      callId.hashCode ^
      providerItemId.hashCode ^
      name.hashCode ^
      arguments.hashCode ^
      result.hashCode ^
      outputArtifactsJson.hashCode ^
      exitCode.hashCode ^
      timedOut.hashCode ^
      workingDirectory.hashCode ^
      denialReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioToolPartDto &&
          runtimeType == other.runtimeType &&
          toolCallId == other.toolCallId &&
          callId == other.callId &&
          providerItemId == other.providerItemId &&
          name == other.name &&
          arguments == other.arguments &&
          result == other.result &&
          outputArtifactsJson == other.outputArtifactsJson &&
          exitCode == other.exitCode &&
          timedOut == other.timedOut &&
          workingDirectory == other.workingDirectory &&
          denialReason == other.denialReason;
}

class BridgeStudioTurnDto {
  final String turnId;
  final String sessionId;
  final String status;
  final String? reason;
  final PlatformInt64 updatedAt;

  const BridgeStudioTurnDto({
    required this.turnId,
    required this.sessionId,
    required this.status,
    this.reason,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      turnId.hashCode ^
      sessionId.hashCode ^
      status.hashCode ^
      reason.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStudioTurnDto &&
          runtimeType == other.runtimeType &&
          turnId == other.turnId &&
          sessionId == other.sessionId &&
          status == other.status &&
          reason == other.reason &&
          updatedAt == other.updatedAt;
}
