// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `InstructionsSettingsInput`, `McpServerInput`, `McpSettingsInput`, `ProviderInput`, `ProviderModelInput`, `ProviderSettingsInput`, `RoleInput`, `SkillsSettingsInput`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

class BridgeModelCapabilities {
  final bool streaming;
  final bool temperature;
  final bool reasoning;
  final bool webSearch;
  final bool functionCalling;
  final bool parallelToolCalls;
  final bool customTools;
  final bool freeformTools;

  const BridgeModelCapabilities({
    required this.streaming,
    required this.temperature,
    required this.reasoning,
    required this.webSearch,
    required this.functionCalling,
    required this.parallelToolCalls,
    required this.customTools,
    required this.freeformTools,
  });

  @override
  int get hashCode =>
      streaming.hashCode ^
      temperature.hashCode ^
      reasoning.hashCode ^
      webSearch.hashCode ^
      functionCalling.hashCode ^
      parallelToolCalls.hashCode ^
      customTools.hashCode ^
      freeformTools.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelCapabilities &&
          runtimeType == other.runtimeType &&
          streaming == other.streaming &&
          temperature == other.temperature &&
          reasoning == other.reasoning &&
          webSearch == other.webSearch &&
          functionCalling == other.functionCalling &&
          parallelToolCalls == other.parallelToolCalls &&
          customTools == other.customTools &&
          freeformTools == other.freeformTools;
}

class BridgeModelCatalogDescriptor {
  final String id;
  final List<BridgeModelDescriptor> models;

  const BridgeModelCatalogDescriptor({required this.id, required this.models});

  @override
  int get hashCode => id.hashCode ^ models.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelCatalogDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          models == other.models;
}

class BridgeModelDescriptor {
  final String id;
  final String displayName;
  final String? description;
  final BigInt? contextWindow;
  final BigInt? maxContextWindow;
  final BigInt? maxOutputTokens;
  final List<String> modalities;
  final BridgeModelCapabilities capabilities;
  final BridgeModelReasoningDescriptor? reasoning;
  final BridgeModelPricing? pricing;

  const BridgeModelDescriptor({
    required this.id,
    required this.displayName,
    this.description,
    this.contextWindow,
    this.maxContextWindow,
    this.maxOutputTokens,
    required this.modalities,
    required this.capabilities,
    this.reasoning,
    this.pricing,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      contextWindow.hashCode ^
      maxContextWindow.hashCode ^
      maxOutputTokens.hashCode ^
      modalities.hashCode ^
      capabilities.hashCode ^
      reasoning.hashCode ^
      pricing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          description == other.description &&
          contextWindow == other.contextWindow &&
          maxContextWindow == other.maxContextWindow &&
          maxOutputTokens == other.maxOutputTokens &&
          modalities == other.modalities &&
          capabilities == other.capabilities &&
          reasoning == other.reasoning &&
          pricing == other.pricing;
}

class BridgeModelPricing {
  final String currency;
  final double? inputPerMtok;
  final double? outputPerMtok;
  final double? cacheReadPerMtok;

  const BridgeModelPricing({
    required this.currency,
    this.inputPerMtok,
    this.outputPerMtok,
    this.cacheReadPerMtok,
  });

  @override
  int get hashCode =>
      currency.hashCode ^
      inputPerMtok.hashCode ^
      outputPerMtok.hashCode ^
      cacheReadPerMtok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelPricing &&
          runtimeType == other.runtimeType &&
          currency == other.currency &&
          inputPerMtok == other.inputPerMtok &&
          outputPerMtok == other.outputPerMtok &&
          cacheReadPerMtok == other.cacheReadPerMtok;
}

class BridgeModelReasoningDescriptor {
  final String parameter;
  final String label;
  final String? defaultCandidate;
  final List<String> candidates;

  const BridgeModelReasoningDescriptor({
    required this.parameter,
    required this.label,
    this.defaultCandidate,
    required this.candidates,
  });

  @override
  int get hashCode =>
      parameter.hashCode ^
      label.hashCode ^
      defaultCandidate.hashCode ^
      candidates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeModelReasoningDescriptor &&
          runtimeType == other.runtimeType &&
          parameter == other.parameter &&
          label == other.label &&
          defaultCandidate == other.defaultCandidate &&
          candidates == other.candidates;
}

class BridgeProviderCatalogSnapshot {
  final int schemaVersion;
  final String revision;
  final List<BridgeProviderPresetDescriptor> presets;
  final List<BridgeModelCatalogDescriptor> modelCatalogs;

  const BridgeProviderCatalogSnapshot({
    required this.schemaVersion,
    required this.revision,
    required this.presets,
    required this.modelCatalogs,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      revision.hashCode ^
      presets.hashCode ^
      modelCatalogs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderCatalogSnapshot &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          revision == other.revision &&
          presets == other.presets &&
          modelCatalogs == other.modelCatalogs;
}

class BridgeProviderConnectionModeDescriptor {
  final String id;
  final String displayName;

  const BridgeProviderConnectionModeDescriptor({
    required this.id,
    required this.displayName,
  });

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderConnectionModeDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName;
}

class BridgeProviderPresetDescriptor {
  final String id;
  final String displayName;
  final String? description;
  final BridgeProviderTransportDescriptor transport;
  final String baseUrl;
  final String credentialLabel;
  final String? credentialEnv;
  final String modelCatalogId;
  final String suggestedModel;
  final String? iconKey;
  final BridgeProviderServiceCapabilitiesDescriptor serviceCapabilities;

  const BridgeProviderPresetDescriptor({
    required this.id,
    required this.displayName,
    this.description,
    required this.transport,
    required this.baseUrl,
    required this.credentialLabel,
    this.credentialEnv,
    required this.modelCatalogId,
    required this.suggestedModel,
    this.iconKey,
    required this.serviceCapabilities,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      transport.hashCode ^
      baseUrl.hashCode ^
      credentialLabel.hashCode ^
      credentialEnv.hashCode ^
      modelCatalogId.hashCode ^
      suggestedModel.hashCode ^
      iconKey.hashCode ^
      serviceCapabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderPresetDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          description == other.description &&
          transport == other.transport &&
          baseUrl == other.baseUrl &&
          credentialLabel == other.credentialLabel &&
          credentialEnv == other.credentialEnv &&
          modelCatalogId == other.modelCatalogId &&
          suggestedModel == other.suggestedModel &&
          iconKey == other.iconKey &&
          serviceCapabilities == other.serviceCapabilities;
}

class BridgeProviderServiceCapabilitiesDescriptor {
  final BridgeWebSearchProviderCapabilitiesDescriptor webSearch;

  const BridgeProviderServiceCapabilitiesDescriptor({required this.webSearch});

  @override
  int get hashCode => webSearch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderServiceCapabilitiesDescriptor &&
          runtimeType == other.runtimeType &&
          webSearch == other.webSearch;
}

class BridgeProviderTransportDescriptor {
  final String protocol;
  final List<BridgeProviderConnectionModeDescriptor> connectionModes;
  final String defaultConnectionMode;

  const BridgeProviderTransportDescriptor({
    required this.protocol,
    required this.connectionModes,
    required this.defaultConnectionMode,
  });

  @override
  int get hashCode =>
      protocol.hashCode ^
      connectionModes.hashCode ^
      defaultConnectionMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProviderTransportDescriptor &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          connectionModes == other.connectionModes &&
          defaultConnectionMode == other.defaultConnectionMode;
}

class BridgeWebSearchProviderCapabilitiesDescriptor {
  final bool hostedResponses;
  final String? standalone;

  const BridgeWebSearchProviderCapabilitiesDescriptor({
    required this.hostedResponses,
    this.standalone,
  });

  @override
  int get hashCode => hostedResponses.hashCode ^ standalone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWebSearchProviderCapabilitiesDescriptor &&
          runtimeType == other.runtimeType &&
          hostedResponses == other.hostedResponses &&
          standalone == other.standalone;
}

/// Web 搜索配置、有效状态和自动 OpenAI backend 的 canonical bridge 快照。
class BridgeWebSearchSettingsDto {
  final String configuredMode;
  final String effectiveMode;
  final String availability;
  final String? contextSize;
  final List<String> allowedDomains;
  final String? country;
  final String? region;
  final String? city;
  final String? timezone;
  final String? providerId;
  final String? model;

  const BridgeWebSearchSettingsDto({
    required this.configuredMode,
    required this.effectiveMode,
    required this.availability,
    this.contextSize,
    required this.allowedDomains,
    this.country,
    this.region,
    this.city,
    this.timezone,
    this.providerId,
    this.model,
  });

  @override
  int get hashCode =>
      configuredMode.hashCode ^
      effectiveMode.hashCode ^
      availability.hashCode ^
      contextSize.hashCode ^
      allowedDomains.hashCode ^
      country.hashCode ^
      region.hashCode ^
      city.hashCode ^
      timezone.hashCode ^
      providerId.hashCode ^
      model.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWebSearchSettingsDto &&
          runtimeType == other.runtimeType &&
          configuredMode == other.configuredMode &&
          effectiveMode == other.effectiveMode &&
          availability == other.availability &&
          contextSize == other.contextSize &&
          allowedDomains == other.allowedDomains &&
          country == other.country &&
          region == other.region &&
          city == other.city &&
          timezone == other.timezone &&
          providerId == other.providerId &&
          model == other.model;
}

/// Web 搜索设置的 typed bridge 输入。
class WebSearchSettingsInput {
  final String mode;
  final String? contextSize;
  final List<String> allowedDomains;
  final String? country;
  final String? region;
  final String? city;
  final String? timezone;

  const WebSearchSettingsInput({
    required this.mode,
    this.contextSize,
    required this.allowedDomains,
    this.country,
    this.region,
    this.city,
    this.timezone,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      contextSize.hashCode ^
      allowedDomains.hashCode ^
      country.hashCode ^
      region.hashCode ^
      city.hashCode ^
      timezone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebSearchSettingsInput &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          contextSize == other.contextSize &&
          allowedDomains == other.allowedDomains &&
          country == other.country &&
          region == other.region &&
          city == other.city &&
          timezone == other.timezone;
}
