import 'dart:async';
import 'dart:convert';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:pure_studio/src/app/pure_studio_app.dart';
import 'package:pure_studio/src/app/theme/studio_tokens.dart';
import 'package:pure_studio/src/data/frb/studio_api.dart';
import 'package:pure_studio/src/data/repositories/studio_repository.dart';
import 'package:pure_studio/src/domain/models/studio_models.dart';
import 'package:pure_studio/src/features/settings/settings_page.dart';
import 'package:pure_studio/src/features/interaction/composer_dock.dart';
import 'package:pure_studio/src/features/shell/studio_shell.dart';
import 'package:pure_studio/src/features/status/status_bar_item.dart';
import 'package:pure_studio/src/features/status/context_usage_readout.dart';
import 'package:pure_studio/src/features/status/thread_status_bar.dart';
import 'package:pure_studio/src/features/status/task_runtime_detail.dart';
import 'package:pure_studio/src/features/todo/todo_panel.dart';
import 'package:pure_studio/src/features/timeline/markdown_repair.dart';
import 'package:pure_studio/src/features/timeline/timeline_view.dart';
import 'package:pure_studio/src/features/update/studio_update_controller.dart';
import 'package:pure_studio/src/l10n/app_localizations.dart';
import 'package:pure_studio/src/shared/studio_chrome.dart';
import 'package:pure_studio/src/shared/studio_driver_keys.dart';
import 'package:pure_studio/src/shared/studio_driver_state.dart';

import 'support/responsive_visual_fixture.dart';

part 'widget_test/controller_stream_tests.dart';
part 'widget_test/reducer_recovery_tests.dart';
part 'widget_test/recovery_issue_tests.dart';
part 'widget_test/task_recovery_tests.dart';
part 'widget_test/timeline_model_tests.dart';
part 'widget_test/snapshot_settings_tests.dart';
part 'widget_test/thread_stream_tests.dart';
part 'widget_test/agent_workspace_tests.dart';
part 'widget_test/demo_project_tests.dart';
part 'widget_test/markdown_render_tests.dart';
part 'widget_test/timeline_tool_tests.dart';
part 'widget_test/timeline_turn_activity_tests.dart';
part 'widget_test/timeline_scroll_tests.dart';
part 'widget_test/responsive_layout_tests.dart';
part 'widget_test/status_accessibility_tests.dart';
part 'widget_test/task_runtime_detail_tests.dart';
part 'widget_test/shell_settings_tests.dart';
part 'widget_test/interaction_tests.dart';
part 'widget_test/skills_tests.dart';
part 'widget_test/fixture_helpers.dart';
part 'widget_test/bridge_event_helpers.dart';
part 'widget_test/menu_scroll_helpers.dart';
part 'widget_test/state_fixtures.dart';
part 'widget_test/fake_studio_api.dart';
part 'widget_test/settings_helpers.dart';
part 'widget_test/studio_update_tests.dart';
part 'widget_test/provider_lifecycle_tests.dart';
part 'widget_test/app_lifecycle_tests.dart';

void main() {
  registerControllerStreamTests();
  registerReducerRecoveryTests();
  registerRecoveryIssueTests();
  registerTaskRecoveryTests();
  registerTimelineModelTests();
  registerSnapshotSettingsTests();
  registerThreadStreamTests();
  registerAgentWorkspaceTests();
  registerDemoProjectTests();
  registerMarkdownRenderTests();
  registerTimelineToolTests();
  registerTimelineTurnActivityTests();
  registerTimelineScrollTests();
  registerResponsiveLayoutTests();
  registerStatusAccessibilityTests();
  registerTaskRuntimeDetailTests();
  registerShellSettingsTests();
  registerInteractionTests();
  registerSkillsTests();
  registerStudioUpdateTests();
  registerProviderLifecycleTests();
  registerAppLifecycleTests();
}
