// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `agent_dto`, `agent_event_dto`, `block_on`, `bootstrap_studio_inner`, `bridge`, `is_session_state_event`, `json_response`, `load_session_state_inner`, `new`, `project_dto`, `provider_edit`, `provider_model_edit`, `provider_settings_edit`, `provider_usage_dto`, `resolve_interaction_response`, `role_edit`, `runtime_snapshot`, `session_dto`, `session_runtime_dto`, `stale`, `studio_settings_draft_key`, `studio_snapshot_from_projects_inner`, `studio_snapshot_inner`, `unix_nanos_hex`, `unix_seconds`, `zhipu_window_labels`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AgentDto`, `AgentTimelineEventDto`, `BootstrapResponse`, `BridgeRuntime`, `DeepSeekBalanceDto`, `DeepSeekBalanceInfoDto`, `ProjectDto`, `ProviderInput`, `ProviderModelInput`, `ProviderSettingsInput`, `ProviderUsageDto`, `ProviderUsagesResponse`, `ResolveInteractionResponse`, `RoleInput`, `SessionDto`, `SessionRuntimeDto`, `SessionStateResponse`, `StopPromptResponse`, `StudioEventsResponse`, `StudioMessageProjectionDto`, `StudioPartProjectionDto`, `SubmitPromptResponse`, `ZhipuCodingPlanUsageDto`, `ZhipuQuotaLimitDto`, `ZhipuToolUsageDetailDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Future<RuntimeSnapshot> initializeRuntime() =>
    RustLib.instance.api.crateApiStudioInitializeRuntime();

Future<RuntimeSnapshot> startRuntime() =>
    RustLib.instance.api.crateApiStudioStartRuntime();

Future<RuntimeSnapshot> shutdownRuntime() =>
    RustLib.instance.api.crateApiStudioShutdownRuntime();

Future<JsonResponse> bootstrapStudio() =>
    RustLib.instance.api.crateApiStudioBootstrapStudio();

Future<JsonResponse> openProject({required String path}) =>
    RustLib.instance.api.crateApiStudioOpenProject(path: path);

Future<JsonResponse> selectProject({required String projectId}) =>
    RustLib.instance.api.crateApiStudioSelectProject(projectId: projectId);

Future<JsonResponse> archiveProject({
  required String projectId,
  String? selectedProjectId,
}) => RustLib.instance.api.crateApiStudioArchiveProject(
  projectId: projectId,
  selectedProjectId: selectedProjectId,
);

Future<JsonResponse> createSession({
  required String projectId,
  String? title,
}) => RustLib.instance.api.crateApiStudioCreateSession(
  projectId: projectId,
  title: title,
);

Future<JsonResponse> archiveSession({
  required String sessionId,
  String? selectedSessionId,
}) => RustLib.instance.api.crateApiStudioArchiveSession(
  sessionId: sessionId,
  selectedSessionId: selectedSessionId,
);

Future<JsonResponse> setSessionMode({
  required String sessionId,
  required String mode,
}) => RustLib.instance.api.crateApiStudioSetSessionMode(
  sessionId: sessionId,
  mode: mode,
);

Future<JsonResponse> setModelRole({
  required String roleKey,
  required String providerId,
  required String model,
  String? effort,
  String? selectedSessionId,
}) => RustLib.instance.api.crateApiStudioSetModelRole(
  roleKey: roleKey,
  providerId: providerId,
  model: model,
  effort: effort,
  selectedSessionId: selectedSessionId,
);

Future<JsonResponse> saveRuntimePermissionMode({required String mode}) =>
    RustLib.instance.api.crateApiStudioSaveRuntimePermissionMode(mode: mode);

Future<JsonResponse> saveProviderSettings({required String settingsJson}) =>
    RustLib.instance.api.crateApiStudioSaveProviderSettings(
      settingsJson: settingsJson,
    );

Future<JsonResponse> loadProviderUsages() =>
    RustLib.instance.api.crateApiStudioLoadProviderUsages();

Future<JsonResponse> listDiscoveredSkills({required String projectId}) =>
    RustLib.instance.api.crateApiStudioListDiscoveredSkills(
      projectId: projectId,
    );

Future<JsonResponse> saveStudioSettingsDraft({
  required String section,
  required String draftJson,
}) => RustLib.instance.api.crateApiStudioSaveStudioSettingsDraft(
  section: section,
  draftJson: draftJson,
);

Future<JsonResponse> submitPrompt({
  required String sessionId,
  required String prompt,
  required List<String> attachmentIds,
}) => RustLib.instance.api.crateApiStudioSubmitPrompt(
  sessionId: sessionId,
  prompt: prompt,
  attachmentIds: attachmentIds,
);

Future<JsonResponse> stopPrompt({required String sessionId}) =>
    RustLib.instance.api.crateApiStudioStopPrompt(sessionId: sessionId);

Future<JsonResponse> resolveInteraction({
  required String interactionId,
  required String resolutionJson,
}) => RustLib.instance.api.crateApiStudioResolveInteraction(
  interactionId: interactionId,
  resolutionJson: resolutionJson,
);

Future<JsonResponse> loadSessionState({required String sessionId}) =>
    RustLib.instance.api.crateApiStudioLoadSessionState(sessionId: sessionId);

Future<JsonResponse> loadStudioEvents({
  required String sessionId,
  PlatformInt64? afterSequence,
  PlatformInt64? limit,
}) => RustLib.instance.api.crateApiStudioLoadStudioEvents(
  sessionId: sessionId,
  afterSequence: afterSequence,
  limit: limit,
);

Stream<BridgeEventEnvelope> subscribeSessionEvents({
  required String sessionId,
}) => RustLib.instance.api.crateApiStudioSubscribeSessionEvents(
  sessionId: sessionId,
);

Stream<BridgeEventEnvelope> subscribeGlobalEvents() =>
    RustLib.instance.api.crateApiStudioSubscribeGlobalEvents();

class BridgeActiveTurn {
  final String sessionId;
  final String turnId;

  const BridgeActiveTurn({required this.sessionId, required this.turnId});

  @override
  int get hashCode => sessionId.hashCode ^ turnId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeActiveTurn &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          turnId == other.turnId;
}

class BridgeEventEnvelope {
  final String eventId;
  final String? sessionId;
  final String? turnId;
  final BigInt sequence;
  final PlatformInt64 createdAt;
  final String kindType;
  final String payloadJson;

  const BridgeEventEnvelope({
    required this.eventId,
    this.sessionId,
    this.turnId,
    required this.sequence,
    required this.createdAt,
    required this.kindType,
    required this.payloadJson,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      sessionId.hashCode ^
      turnId.hashCode ^
      sequence.hashCode ^
      createdAt.hashCode ^
      kindType.hashCode ^
      payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEventEnvelope &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          sessionId == other.sessionId &&
          turnId == other.turnId &&
          sequence == other.sequence &&
          createdAt == other.createdAt &&
          kindType == other.kindType &&
          payloadJson == other.payloadJson;
}

enum BridgeRuntimeStatus {
  uninitialized,
  initializing,
  ready,
  shuttingDown,
  stopped,
  failed,
}

class JsonResponse {
  final String json;

  const JsonResponse({required this.json});

  @override
  int get hashCode => json.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsonResponse &&
          runtimeType == other.runtimeType &&
          json == other.json;
}

class RuntimeSnapshot {
  final BridgeRuntimeStatus status;
  final List<BridgeActiveTurn> activeTurns;
  final PlatformInt64 updatedAt;
  final String? error;

  const RuntimeSnapshot({
    required this.status,
    required this.activeTurns,
    required this.updatedAt,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      activeTurns.hashCode ^
      updatedAt.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeSnapshot &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          activeTurns == other.activeTurns &&
          updatedAt == other.updatedAt &&
          error == other.error;
}
