[package]
name = "pl-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = { workspace = true }
lsp-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
process-wrap = { workspace = true }
lsp-server = { workspace = true }
tokio-util = { workspace = true, features = ["io-util", "rt"] }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
