// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/agent_profile.dart';
import '../types/error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Reads every valid Agent Profile for settings, including disabled profiles.
/// Built-in profiles are immutable and marked with `system: true`.
Future<List<BridgeAgentProfileDto>> readAgentProfiles() =>
    RustLib.instance.api.crateApiStudioHandlersAgentProfilesReadAgentProfiles();

/// Enables or disables an immutable built-in Agent Profile.
Future<List<BridgeAgentProfileDto>> setSystemAgentEnabled({
  required String profileId,
  required bool enabled,
}) => RustLib.instance.api
    .crateApiStudioHandlersAgentProfilesSetSystemAgentEnabled(
      profileId: profileId,
      enabled: enabled,
    );

/// Atomically creates or replaces one user Agent Profile TOML file.
Future<List<BridgeAgentProfileDto>> saveUserAgentProfile({
  required String profileId,
  required bool enabled,
  required String displayName,
  required String description,
  required String whenToUse,
  required String systemInstructions,
  required String providerId,
  required String model,
  String? effort,
}) => RustLib.instance.api
    .crateApiStudioHandlersAgentProfilesSaveUserAgentProfile(
      profileId: profileId,
      enabled: enabled,
      displayName: displayName,
      description: description,
      whenToUse: whenToUse,
      systemInstructions: systemInstructions,
      providerId: providerId,
      model: model,
      effort: effort,
    );
