// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/runtime.dart';
import '../types/settings.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BridgeMcpStateSnapshot> readMcpState() =>
    RustLib.instance.api.crateApiStudioHandlersExternalStateReadMcpState();

Future<BridgeMcpStateSnapshot> resetMcp({required McpResetInput input}) =>
    RustLib.instance.api.crateApiStudioHandlersExternalStateResetMcp(
      input: input,
    );

Future<BridgeLspStateSnapshot> readLspState() =>
    RustLib.instance.api.crateApiStudioHandlersExternalStateReadLspState();

Future<BridgeLspStateSnapshot> probeLspServer({required String projectId}) =>
    RustLib.instance.api.crateApiStudioHandlersExternalStateProbeLspServer(
      projectId: projectId,
    );

Future<BridgeLspStateSnapshot> repairLspServer({
  required String projectId,
  required String serverId,
}) => RustLib.instance.api.crateApiStudioHandlersExternalStateRepairLspServer(
  projectId: projectId,
  serverId: serverId,
);

Future<BridgeLspStateSnapshot> resetLsp({required LspScopeInput input}) =>
    RustLib.instance.api.crateApiStudioHandlersExternalStateResetLsp(
      input: input,
    );
