// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/runtime.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 跳过当前退避并立即重试保存积压的内存事实。
Future<BridgePersistenceStateSnapshot> retryPersistence() =>
    RustLib.instance.api.crateApiStudioHandlersPersistenceRetryPersistence();
