// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/interaction.dart';
import '../types/response.dart';
import '../types/session_stream.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `interaction_resolution`

Future<SubmitPromptResponse> submitPrompt({
  required String sessionId,
  required String prompt,
  required List<String> attachmentIds,
}) => RustLib.instance.api.crateApiStudioHandlersPromptSubmitPrompt(
  sessionId: sessionId,
  prompt: prompt,
  attachmentIds: attachmentIds,
);

Future<SubmitPromptResponse> resumeTask({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiStudioHandlersPromptResumeTask(sessionId: sessionId);

Future<StopPromptResponse> stopPrompt({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiStudioHandlersPromptStopPrompt(sessionId: sessionId);

Future<ResolveInteractionResponse> resolveInteraction({
  required String interactionId,
  required BridgeInteractionResolution resolution,
}) => RustLib.instance.api.crateApiStudioHandlersPromptResolveInteraction(
  interactionId: interactionId,
  resolution: resolution,
);
