// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/runtime.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BridgeTaskRecoveryPreviewDto> previewTaskRecovery({
  required String rootThreadId,
}) => RustLib.instance.api.crateApiStudioHandlersRecoveryPreviewTaskRecovery(
  rootThreadId: rootThreadId,
);

Future<BridgeTaskRecoveryResultDto> applyTaskRecovery({
  required BridgeTaskRecoveryRequestDto request,
}) => RustLib.instance.api.crateApiStudioHandlersRecoveryApplyTaskRecovery(
  request: request,
);

Future<BridgeRecoveryCleanupPreviewDto> previewRecoveryIssueCleanup({
  required String issueId,
}) => RustLib.instance.api
    .crateApiStudioHandlersRecoveryPreviewRecoveryIssueCleanup(
      issueId: issueId,
    );

Future<BridgeRecoveryCleanupPreviewDto> previewProjectCleanup({
  required String projectId,
}) => RustLib.instance.api.crateApiStudioHandlersRecoveryPreviewProjectCleanup(
  projectId: projectId,
);

Future<RuntimeSnapshot> cleanupRecoveryIssue({
  required String issueId,
  required String expectedRevision,
}) => RustLib.instance.api.crateApiStudioHandlersRecoveryCleanupRecoveryIssue(
  issueId: issueId,
  expectedRevision: expectedRevision,
);

Future<RuntimeSnapshot> retryRecoveryIssue({required String issueId}) => RustLib
    .instance
    .api
    .crateApiStudioHandlersRecoveryRetryRecoveryIssue(issueId: issueId);

Future<RuntimeSnapshot> cleanupProject({
  required String projectId,
  required String expectedRevision,
}) => RustLib.instance.api.crateApiStudioHandlersRecoveryCleanupProject(
  projectId: projectId,
  expectedRevision: expectedRevision,
);
