// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/runtime.dart';
import '../types/settings.dart';
import '../types/thread_stream.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BridgeRecoveryCleanupPreviewDto> previewRecoveryIssueCleanup({
  required String issueId,
}) => RustLib.instance.api
    .crateApiStudioHandlersRecoveryPreviewRecoveryIssueCleanup(
      issueId: issueId,
    );

Future<BridgeRecoveryCleanupPreviewDto> previewProjectCleanup({
  required String projectId,
}) => RustLib.instance.api.crateApiStudioHandlersRecoveryPreviewProjectCleanup(
  projectId: projectId,
);

Future<BridgeStudioSnapshotResponse> cleanupRecoveryIssue({
  required String issueId,
  required String expectedRevision,
  String? selectedProjectId,
  String? selectedThreadId,
}) => RustLib.instance.api.crateApiStudioHandlersRecoveryCleanupRecoveryIssue(
  issueId: issueId,
  expectedRevision: expectedRevision,
  selectedProjectId: selectedProjectId,
  selectedThreadId: selectedThreadId,
);

Future<BridgeStudioSnapshotResponse> retryRecoveryIssue({
  required String issueId,
  String? selectedProjectId,
  String? selectedThreadId,
}) => RustLib.instance.api.crateApiStudioHandlersRecoveryRetryRecoveryIssue(
  issueId: issueId,
  selectedProjectId: selectedProjectId,
  selectedThreadId: selectedThreadId,
);

Future<BridgeStudioSnapshotResponse> cleanupProject({
  required String projectId,
  required String expectedRevision,
  String? selectedProjectId,
}) => RustLib.instance.api.crateApiStudioHandlersRecoveryCleanupProject(
  projectId: projectId,
  expectedRevision: expectedRevision,
  selectedProjectId: selectedProjectId,
);
