// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/runtime.dart';
import '../types/settings.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BridgeProviderCatalogSnapshot> loadProviderCatalog() =>
    RustLib.instance.api.crateApiStudioHandlersSettingsLoadProviderCatalog();

Future<BridgeWebSearchSettingsDto> readWebSearchSettings() =>
    RustLib.instance.api.crateApiStudioHandlersSettingsReadWebSearchSettings();

Future<BridgeSettingsStateSnapshot> saveWebSearchSettings({
  required BigInt expectedSettingsRevision,
  required WebSearchSettingsInput input,
}) => RustLib.instance.api.crateApiStudioHandlersSettingsSaveWebSearchSettings(
  expectedSettingsRevision: expectedSettingsRevision,
  input: input,
);

Future<BridgeSettingsStateSnapshot> readSettingsState() =>
    RustLib.instance.api.crateApiStudioHandlersSettingsReadSettingsState();

Future<BridgeSettingsStateSnapshot> reloadSettingsFromDisk({
  required BigInt expectedSettingsRevision,
}) => RustLib.instance.api.crateApiStudioHandlersSettingsReloadSettingsFromDisk(
  expectedSettingsRevision: expectedSettingsRevision,
);

Future<BridgeSettingsStateSnapshot> saveRuntimePermissionMode({
  required BigInt expectedSettingsRevision,
  required String mode,
}) => RustLib.instance.api
    .crateApiStudioHandlersSettingsSaveRuntimePermissionMode(
      expectedSettingsRevision: expectedSettingsRevision,
      mode: mode,
    );

Future<BridgeSettingsStateSnapshot> saveProviderSettings({
  required BigInt expectedSettingsRevision,
  required ProviderSettingsInput input,
}) => RustLib.instance.api.crateApiStudioHandlersSettingsSaveProviderSettings(
  expectedSettingsRevision: expectedSettingsRevision,
  input: input,
);

Future<BridgeSettingsStateSnapshot> saveInstructionsSettings({
  required BigInt expectedSettingsRevision,
  required InstructionsSettingsInput input,
}) =>
    RustLib.instance.api.crateApiStudioHandlersSettingsSaveInstructionsSettings(
      expectedSettingsRevision: expectedSettingsRevision,
      input: input,
    );

Future<BridgeSettingsStateSnapshot> saveSkillsSettings({
  required BigInt expectedSettingsRevision,
  required SkillsSettingsInput input,
}) => RustLib.instance.api.crateApiStudioHandlersSettingsSaveSkillsSettings(
  expectedSettingsRevision: expectedSettingsRevision,
  input: input,
);

Future<BridgeSettingsStateSnapshot> saveMcpSettings({
  required BigInt expectedSettingsRevision,
  required McpSettingsInput input,
}) => RustLib.instance.api.crateApiStudioHandlersSettingsSaveMcpSettings(
  expectedSettingsRevision: expectedSettingsRevision,
  input: input,
);

Future<BridgeSettingsStateSnapshot> saveGeneralSettings({
  required BigInt expectedSettingsRevision,
  required GeneralSettingsInput input,
}) => RustLib.instance.api.crateApiStudioHandlersSettingsSaveGeneralSettings(
  expectedSettingsRevision: expectedSettingsRevision,
  input: input,
);

Future<BridgeSettingsStateSnapshot> setModelRole({
  required BigInt expectedSettingsRevision,
  required String roleKey,
  required String providerId,
  required String model,
  String? effort,
}) => RustLib.instance.api.crateApiStudioHandlersSettingsSetModelRole(
  expectedSettingsRevision: expectedSettingsRevision,
  roleKey: roleKey,
  providerId: providerId,
  model: model,
  effort: effort,
);
