// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/thread_stream.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Creates a Simple root Thread and accepts its first Turn.
///
/// # Errors
///
/// Returns an error when the Project does not exist, the prompt is empty, or the Turn is rejected.
Future<StartNewThreadResponse> startNewThread({
  required String projectId,
  required String prompt,
  required List<String> attachmentIds,
}) => RustLib.instance.api.crateApiStudioHandlersThreadStartNewThread(
  projectId: projectId,
  prompt: prompt,
  attachmentIds: attachmentIds,
);

/// Archives a root Thread and selects the next available Thread.
///
/// # Errors
///
/// Returns an error when the Thread does not exist, is a child Thread, or its tree is active.
Future<ArchiveThreadResult> archiveThread({required String threadId}) => RustLib
    .instance
    .api
    .crateApiStudioHandlersThreadArchiveThread(threadId: threadId);

/// Changes the selected root Thread between Simple and Task mode.
///
/// # Errors
///
/// Returns an error when the Thread does not exist, is a child Thread, or has an active Task.
Future<void> setThreadMode({
  required String threadId,
  required BridgeThreadMode mode,
}) => RustLib.instance.api.crateApiStudioHandlersThreadSetThreadMode(
  threadId: threadId,
  mode: mode,
);
