// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/error.dart';
import '../types/response.dart';
import '../types/runtime.dart';
import '../types/updater.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_event`, `bridge_update_state`, `cancel_all_update_operations`, `runtime_error`, `update_operations`, `wait`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeStudioUpdateOperationInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

Future<BridgeUpdaterStateSnapshot> checkStudioUpdate() =>
    RustLib.instance.api.crateApiStudioHandlersUpdaterCheckStudioUpdate();

Future<BridgeUpdaterStateSnapshot> readStudioUpdateState() =>
    RustLib.instance.api.crateApiStudioHandlersUpdaterReadStudioUpdateState();

Future<BridgeStudioUpdateOperation> installStudioUpdate({
  required BigInt expectedRevision,
  required String version,
}) => RustLib.instance.api.crateApiStudioHandlersUpdaterInstallStudioUpdate(
  expectedRevision: expectedRevision,
  version: version,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeStudioUpdateOperation>>
abstract class BridgeStudioUpdateOperation implements RustOpaqueInterface {
  Future<void> cancel();

  Stream<BridgeStudioUpdateEventDto> progressStream();
}
