// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types/updater.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_event`, `bridge_update`, `runtime_error`, `runtime_update`, `updater`

Future<BridgeStudioUpdateCheckDto> checkStudioUpdate({
  required String currentVersion,
}) => RustLib.instance.api.crateApiStudioHandlersUpdaterCheckStudioUpdate(
  currentVersion: currentVersion,
);

Stream<BridgeStudioUpdateEventDto> installStudioUpdate({
  required BridgeStudioUpdateDto update,
}) => RustLib.instance.api.crateApiStudioHandlersUpdaterInstallStudioUpdate(
  update: update,
);
