// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/studio/handlers/lifecycle.dart';
import 'api/studio/handlers/prompt.dart';
import 'api/studio/handlers/providers.dart';
import 'api/studio/handlers/recovery.dart';
import 'api/studio/handlers/session.dart';
import 'api/studio/handlers/settings.dart';
import 'api/studio/handlers/updater.dart';
import 'api/studio/subscription.dart';
import 'api/studio/types/error.dart';
import 'api/studio/types/event.dart';
import 'api/studio/types/interaction.dart';
import 'api/studio/types/response.dart';
import 'api/studio/types/runtime.dart';
import 'api/studio/types/session_stream.dart';
import 'api/studio/types/settings.dart';
import 'api/studio/types/updater.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeEventSubscriptionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscriptionPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeStudioUpdateOperationPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperationPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BridgeEventSubscription
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    dynamic raw,
  );

  @protected
  BridgeStudioUpdateOperation
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    dynamic raw,
  );

  @protected
  BridgeEventSubscription
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    dynamic raw,
  );

  @protected
  BridgeStudioUpdateOperation
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    dynamic raw,
  );

  @protected
  BridgeEventSubscription
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    dynamic raw,
  );

  @protected
  BridgeStudioUpdateOperation
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    dynamic raw,
  );

  @protected
  RustStreamSink<BridgeProductStreamEnvelope>
  dco_decode_StreamSink_bridge_product_stream_envelope_Sse(dynamic raw);

  @protected
  RustStreamSink<BridgeSessionStreamEnvelope>
  dco_decode_StreamSink_bridge_session_stream_envelope_Sse(dynamic raw);

  @protected
  RustStreamSink<BridgeStudioUpdateEventDto>
  dco_decode_StreamSink_bridge_studio_update_event_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  BridgeAgentStatus dco_decode_box_autoadd_bridge_agent_status(dynamic raw);

  @protected
  BridgeBudgetLimitKind dco_decode_box_autoadd_bridge_budget_limit_kind(
    dynamic raw,
  );

  @protected
  BridgeBudgetUsage dco_decode_box_autoadd_bridge_budget_usage(dynamic raw);

  @protected
  BridgeError dco_decode_box_autoadd_bridge_error(dynamic raw);

  @protected
  BridgeInteractionRequest dco_decode_box_autoadd_bridge_interaction_request(
    dynamic raw,
  );

  @protected
  BridgeInteractionResolution
  dco_decode_box_autoadd_bridge_interaction_resolution(dynamic raw);

  @protected
  BridgeLspHealthDto dco_decode_box_autoadd_bridge_lsp_health_dto(dynamic raw);

  @protected
  BridgeMcpHealthDto dco_decode_box_autoadd_bridge_mcp_health_dto(dynamic raw);

  @protected
  BridgeModelPricing dco_decode_box_autoadd_bridge_model_pricing(dynamic raw);

  @protected
  BridgeModelReasoningDescriptor
  dco_decode_box_autoadd_bridge_model_reasoning_descriptor(dynamic raw);

  @protected
  BridgePlanLifecycleEvent dco_decode_box_autoadd_bridge_plan_lifecycle_event(
    dynamic raw,
  );

  @protected
  BridgeProductEventEnvelope
  dco_decode_box_autoadd_bridge_product_event_envelope(dynamic raw);

  @protected
  BridgeSessionAgentPart dco_decode_box_autoadd_bridge_session_agent_part(
    dynamic raw,
  );

  @protected
  BridgeSessionAgentSnapshot
  dco_decode_box_autoadd_bridge_session_agent_snapshot(dynamic raw);

  @protected
  BridgeSessionContextCompaction
  dco_decode_box_autoadd_bridge_session_context_compaction(dynamic raw);

  @protected
  BridgeSessionEventEnvelope
  dco_decode_box_autoadd_bridge_session_event_envelope(dynamic raw);

  @protected
  BridgeSessionMcpHealthSnapshot
  dco_decode_box_autoadd_bridge_session_mcp_health_snapshot(dynamic raw);

  @protected
  BridgeSessionMessage dco_decode_box_autoadd_bridge_session_message(
    dynamic raw,
  );

  @protected
  BridgeSessionOwnerSnapshot
  dco_decode_box_autoadd_bridge_session_owner_snapshot(dynamic raw);

  @protected
  BridgeSessionPart dco_decode_box_autoadd_bridge_session_part(dynamic raw);

  @protected
  BridgeSessionPartDelta dco_decode_box_autoadd_bridge_session_part_delta(
    dynamic raw,
  );

  @protected
  BridgeSessionResyncReason dco_decode_box_autoadd_bridge_session_resync_reason(
    dynamic raw,
  );

  @protected
  BridgeSessionRuntimeSnapshot
  dco_decode_box_autoadd_bridge_session_runtime_snapshot(dynamic raw);

  @protected
  BridgeSessionRuntimeUsage dco_decode_box_autoadd_bridge_session_runtime_usage(
    dynamic raw,
  );

  @protected
  BridgeSessionTimelineEvent
  dco_decode_box_autoadd_bridge_session_timeline_event(dynamic raw);

  @protected
  BridgeSessionToolPart dco_decode_box_autoadd_bridge_session_tool_part(
    dynamic raw,
  );

  @protected
  BridgeSessionTurn dco_decode_box_autoadd_bridge_session_turn(dynamic raw);

  @protected
  BridgeSessionViewSnapshot dco_decode_box_autoadd_bridge_session_view_snapshot(
    dynamic raw,
  );

  @protected
  BridgeSkillActivation dco_decode_box_autoadd_bridge_skill_activation(
    dynamic raw,
  );

  @protected
  BridgeStudioUpdateDto dco_decode_box_autoadd_bridge_studio_update_dto(
    dynamic raw,
  );

  @protected
  BridgeTaskRuntimeDto dco_decode_box_autoadd_bridge_task_runtime_dto(
    dynamic raw,
  );

  @protected
  BridgeTodoListSnapshot dco_decode_box_autoadd_bridge_todo_list_snapshot(
    dynamic raw,
  );

  @protected
  BridgeTokenUsageSnapshot dco_decode_box_autoadd_bridge_token_usage_snapshot(
    dynamic raw,
  );

  @protected
  DeepSeekBalanceDto dco_decode_box_autoadd_deep_seek_balance_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GeneralSettingsInput dco_decode_box_autoadd_general_settings_input(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  InstructionsSettingsInput dco_decode_box_autoadd_instructions_settings_input(
    dynamic raw,
  );

  @protected
  McpSettingsInput dco_decode_box_autoadd_mcp_settings_input(dynamic raw);

  @protected
  ProviderSettingsInput dco_decode_box_autoadd_provider_settings_input(
    dynamic raw,
  );

  @protected
  SkillsSettingsInput dco_decode_box_autoadd_skills_settings_input(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  WebSearchSettingsInput dco_decode_box_autoadd_web_search_settings_input(
    dynamic raw,
  );

  @protected
  ZhipuCodingPlanUsageDto dco_decode_box_autoadd_zhipu_coding_plan_usage_dto(
    dynamic raw,
  );

  @protected
  BridgeSessionStreamFrame dco_decode_box_bridge_session_stream_frame(
    dynamic raw,
  );

  @protected
  BridgeTaskRuntimeDto dco_decode_box_bridge_task_runtime_dto(dynamic raw);

  @protected
  BridgeActiveTurn dco_decode_bridge_active_turn(dynamic raw);

  @protected
  BridgeAgentStatus dco_decode_bridge_agent_status(dynamic raw);

  @protected
  BridgeBudgetLimitKind dco_decode_bridge_budget_limit_kind(dynamic raw);

  @protected
  BridgeBudgetUsage dco_decode_bridge_budget_usage(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeErrorCode dco_decode_bridge_error_code(dynamic raw);

  @protected
  BridgeErrorSeverity dco_decode_bridge_error_severity(dynamic raw);

  @protected
  BridgeInteractionChangedDto dco_decode_bridge_interaction_changed_dto(
    dynamic raw,
  );

  @protected
  BridgeInteractionKind dco_decode_bridge_interaction_kind(dynamic raw);

  @protected
  BridgeInteractionPayload dco_decode_bridge_interaction_payload(dynamic raw);

  @protected
  BridgeInteractionPayloadDto dco_decode_bridge_interaction_payload_dto(
    dynamic raw,
  );

  @protected
  BridgeInteractionRequest dco_decode_bridge_interaction_request(dynamic raw);

  @protected
  BridgeInteractionResolution dco_decode_bridge_interaction_resolution(
    dynamic raw,
  );

  @protected
  BridgeInteractionScope dco_decode_bridge_interaction_scope(dynamic raw);

  @protected
  BridgeInteractionStatus dco_decode_bridge_interaction_status(dynamic raw);

  @protected
  BridgeLspHealthDto dco_decode_bridge_lsp_health_dto(dynamic raw);

  @protected
  BridgeMcpHealthDto dco_decode_bridge_mcp_health_dto(dynamic raw);

  @protected
  BridgeMcpServerDto dco_decode_bridge_mcp_server_dto(dynamic raw);

  @protected
  BridgeModelCapabilities dco_decode_bridge_model_capabilities(dynamic raw);

  @protected
  BridgeModelCatalogDescriptor dco_decode_bridge_model_catalog_descriptor(
    dynamic raw,
  );

  @protected
  BridgeModelDescriptor dco_decode_bridge_model_descriptor(dynamic raw);

  @protected
  BridgeModelPricing dco_decode_bridge_model_pricing(dynamic raw);

  @protected
  BridgeModelReasoningDescriptor dco_decode_bridge_model_reasoning_descriptor(
    dynamic raw,
  );

  @protected
  BridgePlanConfirmationResolution
  dco_decode_bridge_plan_confirmation_resolution(dynamic raw);

  @protected
  BridgePlanLifecycleEvent dco_decode_bridge_plan_lifecycle_event(dynamic raw);

  @protected
  BridgePlanLifecycleState dco_decode_bridge_plan_lifecycle_state(dynamic raw);

  @protected
  BridgeProductEventEnvelope dco_decode_bridge_product_event_envelope(
    dynamic raw,
  );

  @protected
  BridgeProductEventPayload dco_decode_bridge_product_event_payload(
    dynamic raw,
  );

  @protected
  BridgeProductStreamEnvelope dco_decode_bridge_product_stream_envelope(
    dynamic raw,
  );

  @protected
  BridgeProviderCatalogSnapshot dco_decode_bridge_provider_catalog_snapshot(
    dynamic raw,
  );

  @protected
  BridgeProviderConnectionModeDescriptor
  dco_decode_bridge_provider_connection_mode_descriptor(dynamic raw);

  @protected
  BridgeProviderPresetDescriptor dco_decode_bridge_provider_preset_descriptor(
    dynamic raw,
  );

  @protected
  BridgeProviderServiceCapabilitiesDescriptor
  dco_decode_bridge_provider_service_capabilities_descriptor(dynamic raw);

  @protected
  BridgeProviderTransportDescriptor
  dco_decode_bridge_provider_transport_descriptor(dynamic raw);

  @protected
  BridgeRecoveryCleanupPreviewDto
  dco_decode_bridge_recovery_cleanup_preview_dto(dynamic raw);

  @protected
  BridgeRecoveryCleanupResourceDto
  dco_decode_bridge_recovery_cleanup_resource_dto(dynamic raw);

  @protected
  BridgeRecoveryIssueAction dco_decode_bridge_recovery_issue_action(
    dynamic raw,
  );

  @protected
  BridgeRecoveryIssueCategory dco_decode_bridge_recovery_issue_category(
    dynamic raw,
  );

  @protected
  BridgeRecoveryIssueScope dco_decode_bridge_recovery_issue_scope(dynamic raw);

  @protected
  BridgeRecoveryResourcePresence dco_decode_bridge_recovery_resource_presence(
    dynamic raw,
  );

  @protected
  BridgeRuntimeCostAmount dco_decode_bridge_runtime_cost_amount(dynamic raw);

  @protected
  BridgeRuntimeStatus dco_decode_bridge_runtime_status(dynamic raw);

  @protected
  BridgeSessionAgentPart dco_decode_bridge_session_agent_part(dynamic raw);

  @protected
  BridgeSessionAgentSnapshot dco_decode_bridge_session_agent_snapshot(
    dynamic raw,
  );

  @protected
  BridgeSessionAttachment dco_decode_bridge_session_attachment(dynamic raw);

  @protected
  BridgeSessionContextCompaction dco_decode_bridge_session_context_compaction(
    dynamic raw,
  );

  @protected
  BridgeSessionEventEnvelope dco_decode_bridge_session_event_envelope(
    dynamic raw,
  );

  @protected
  BridgeSessionEventKind dco_decode_bridge_session_event_kind(dynamic raw);

  @protected
  BridgeSessionEventPosition dco_decode_bridge_session_event_position(
    dynamic raw,
  );

  @protected
  BridgeSessionMcpAvailabilityDescriptor
  dco_decode_bridge_session_mcp_availability_descriptor(dynamic raw);

  @protected
  BridgeSessionMcpHealthSnapshot dco_decode_bridge_session_mcp_health_snapshot(
    dynamic raw,
  );

  @protected
  BridgeSessionMcpServerDescriptor
  dco_decode_bridge_session_mcp_server_descriptor(dynamic raw);

  @protected
  BridgeSessionMessage dco_decode_bridge_session_message(dynamic raw);

  @protected
  BridgeSessionMessageRole dco_decode_bridge_session_message_role(dynamic raw);

  @protected
  BridgeSessionMessageStatus dco_decode_bridge_session_message_status(
    dynamic raw,
  );

  @protected
  BridgeSessionOwnerSnapshot dco_decode_bridge_session_owner_snapshot(
    dynamic raw,
  );

  @protected
  BridgeSessionPart dco_decode_bridge_session_part(dynamic raw);

  @protected
  BridgeSessionPartContent dco_decode_bridge_session_part_content(dynamic raw);

  @protected
  BridgeSessionPartDelta dco_decode_bridge_session_part_delta(dynamic raw);

  @protected
  BridgeSessionPartDeltaField dco_decode_bridge_session_part_delta_field(
    dynamic raw,
  );

  @protected
  BridgeSessionPartStatus dco_decode_bridge_session_part_status(dynamic raw);

  @protected
  BridgeSessionResyncReason dco_decode_bridge_session_resync_reason(
    dynamic raw,
  );

  @protected
  BridgeSessionRuntimeSnapshot dco_decode_bridge_session_runtime_snapshot(
    dynamic raw,
  );

  @protected
  BridgeSessionRuntimeUsage dco_decode_bridge_session_runtime_usage(
    dynamic raw,
  );

  @protected
  BridgeSessionStreamEnvelope dco_decode_bridge_session_stream_envelope(
    dynamic raw,
  );

  @protected
  BridgeSessionStreamFrame dco_decode_bridge_session_stream_frame(dynamic raw);

  @protected
  BridgeSessionTextChannel dco_decode_bridge_session_text_channel(dynamic raw);

  @protected
  BridgeSessionTimelineEvent dco_decode_bridge_session_timeline_event(
    dynamic raw,
  );

  @protected
  BridgeSessionTimelineEventKind dco_decode_bridge_session_timeline_event_kind(
    dynamic raw,
  );

  @protected
  BridgeSessionToolPart dco_decode_bridge_session_tool_part(dynamic raw);

  @protected
  BridgeSessionTurn dco_decode_bridge_session_turn(dynamic raw);

  @protected
  BridgeSessionTurnActivity dco_decode_bridge_session_turn_activity(
    dynamic raw,
  );

  @protected
  BridgeSessionTurnState dco_decode_bridge_session_turn_state(dynamic raw);

  @protected
  BridgeSessionViewSnapshot dco_decode_bridge_session_view_snapshot(
    dynamic raw,
  );

  @protected
  BridgeSkillActivation dco_decode_bridge_skill_activation(dynamic raw);

  @protected
  BridgeStudioRecoveryIssueDto dco_decode_bridge_studio_recovery_issue_dto(
    dynamic raw,
  );

  @protected
  BridgeStudioSnapshotResponse dco_decode_bridge_studio_snapshot_response(
    dynamic raw,
  );

  @protected
  BridgeStudioUpdateCheckDto dco_decode_bridge_studio_update_check_dto(
    dynamic raw,
  );

  @protected
  BridgeStudioUpdateDto dco_decode_bridge_studio_update_dto(dynamic raw);

  @protected
  BridgeStudioUpdateEventDto dco_decode_bridge_studio_update_event_dto(
    dynamic raw,
  );

  @protected
  BridgeSubAgentActivityKind dco_decode_bridge_sub_agent_activity_kind(
    dynamic raw,
  );

  @protected
  BridgeTaskAgentDto dco_decode_bridge_task_agent_dto(dynamic raw);

  @protected
  BridgeTaskMergeDto dco_decode_bridge_task_merge_dto(dynamic raw);

  @protected
  BridgeTaskReviewDto dco_decode_bridge_task_review_dto(dynamic raw);

  @protected
  BridgeTaskRuntimeDto dco_decode_bridge_task_runtime_dto(dynamic raw);

  @protected
  BridgeTaskWorkUnitDto dco_decode_bridge_task_work_unit_dto(dynamic raw);

  @protected
  BridgeTodoItem dco_decode_bridge_todo_item(dynamic raw);

  @protected
  BridgeTodoListSnapshot dco_decode_bridge_todo_list_snapshot(dynamic raw);

  @protected
  BridgeTodoStatus dco_decode_bridge_todo_status(dynamic raw);

  @protected
  BridgeTokenUsageSnapshot dco_decode_bridge_token_usage_snapshot(dynamic raw);

  @protected
  BridgeToolApprovalResolution dco_decode_bridge_tool_approval_resolution(
    dynamic raw,
  );

  @protected
  BridgeUserInputAnswer dco_decode_bridge_user_input_answer(dynamic raw);

  @protected
  BridgeUserQuestion dco_decode_bridge_user_question(dynamic raw);

  @protected
  BridgeUserQuestionDto dco_decode_bridge_user_question_dto(dynamic raw);

  @protected
  BridgeUserQuestionOption dco_decode_bridge_user_question_option(dynamic raw);

  @protected
  BridgeUserQuestionOptionDto dco_decode_bridge_user_question_option_dto(
    dynamic raw,
  );

  @protected
  BridgeWebSearchProviderCapabilitiesDescriptor
  dco_decode_bridge_web_search_provider_capabilities_descriptor(dynamic raw);

  @protected
  BridgeWebSearchSettingsDto dco_decode_bridge_web_search_settings_dto(
    dynamic raw,
  );

  @protected
  DeepSeekBalanceDto dco_decode_deep_seek_balance_dto(dynamic raw);

  @protected
  DeepSeekBalanceInfoDto dco_decode_deep_seek_balance_info_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GeneralSettingsInput dco_decode_general_settings_input(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InstructionsSettingsInput dco_decode_instructions_settings_input(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BridgeActiveTurn> dco_decode_list_bridge_active_turn(dynamic raw);

  @protected
  List<BridgeInteractionRequest> dco_decode_list_bridge_interaction_request(
    dynamic raw,
  );

  @protected
  List<BridgeMcpServerDto> dco_decode_list_bridge_mcp_server_dto(dynamic raw);

  @protected
  List<BridgeModelCatalogDescriptor>
  dco_decode_list_bridge_model_catalog_descriptor(dynamic raw);

  @protected
  List<BridgeModelDescriptor> dco_decode_list_bridge_model_descriptor(
    dynamic raw,
  );

  @protected
  List<BridgePlanLifecycleEvent> dco_decode_list_bridge_plan_lifecycle_event(
    dynamic raw,
  );

  @protected
  List<BridgeProviderConnectionModeDescriptor>
  dco_decode_list_bridge_provider_connection_mode_descriptor(dynamic raw);

  @protected
  List<BridgeProviderPresetDescriptor>
  dco_decode_list_bridge_provider_preset_descriptor(dynamic raw);

  @protected
  List<BridgeRecoveryCleanupResourceDto>
  dco_decode_list_bridge_recovery_cleanup_resource_dto(dynamic raw);

  @protected
  List<BridgeRecoveryIssueAction> dco_decode_list_bridge_recovery_issue_action(
    dynamic raw,
  );

  @protected
  List<BridgeRuntimeCostAmount> dco_decode_list_bridge_runtime_cost_amount(
    dynamic raw,
  );

  @protected
  List<BridgeSessionAgentSnapshot>
  dco_decode_list_bridge_session_agent_snapshot(dynamic raw);

  @protected
  List<BridgeSessionAttachment> dco_decode_list_bridge_session_attachment(
    dynamic raw,
  );

  @protected
  List<BridgeSessionMcpAvailabilityDescriptor>
  dco_decode_list_bridge_session_mcp_availability_descriptor(dynamic raw);

  @protected
  List<BridgeSessionMessage> dco_decode_list_bridge_session_message(
    dynamic raw,
  );

  @protected
  List<BridgeSessionPart> dco_decode_list_bridge_session_part(dynamic raw);

  @protected
  List<BridgeSessionTimelineEvent>
  dco_decode_list_bridge_session_timeline_event(dynamic raw);

  @protected
  List<BridgeSkillActivation> dco_decode_list_bridge_skill_activation(
    dynamic raw,
  );

  @protected
  List<BridgeStudioRecoveryIssueDto>
  dco_decode_list_bridge_studio_recovery_issue_dto(dynamic raw);

  @protected
  List<BridgeTaskAgentDto> dco_decode_list_bridge_task_agent_dto(dynamic raw);

  @protected
  List<BridgeTaskMergeDto> dco_decode_list_bridge_task_merge_dto(dynamic raw);

  @protected
  List<BridgeTaskReviewDto> dco_decode_list_bridge_task_review_dto(dynamic raw);

  @protected
  List<BridgeTaskWorkUnitDto> dco_decode_list_bridge_task_work_unit_dto(
    dynamic raw,
  );

  @protected
  List<BridgeTodoItem> dco_decode_list_bridge_todo_item(dynamic raw);

  @protected
  List<BridgeUserInputAnswer> dco_decode_list_bridge_user_input_answer(
    dynamic raw,
  );

  @protected
  List<BridgeUserQuestion> dco_decode_list_bridge_user_question(dynamic raw);

  @protected
  List<BridgeUserQuestionDto> dco_decode_list_bridge_user_question_dto(
    dynamic raw,
  );

  @protected
  List<BridgeUserQuestionOption> dco_decode_list_bridge_user_question_option(
    dynamic raw,
  );

  @protected
  List<BridgeUserQuestionOptionDto>
  dco_decode_list_bridge_user_question_option_dto(dynamic raw);

  @protected
  List<DeepSeekBalanceInfoDto> dco_decode_list_deep_seek_balance_info_dto(
    dynamic raw,
  );

  @protected
  List<McpServerInput> dco_decode_list_mcp_server_input(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectDto> dco_decode_list_project_dto(dynamic raw);

  @protected
  List<ProviderInput> dco_decode_list_provider_input(dynamic raw);

  @protected
  List<ProviderModelInput> dco_decode_list_provider_model_input(dynamic raw);

  @protected
  List<ProviderUsageDto> dco_decode_list_provider_usage_dto(dynamic raw);

  @protected
  List<RoleInput> dco_decode_list_role_input(dynamic raw);

  @protected
  List<SessionDto> dco_decode_list_session_dto(dynamic raw);

  @protected
  List<SkillSummaryDto> dco_decode_list_skill_summary_dto(dynamic raw);

  @protected
  List<ZhipuQuotaLimitDto> dco_decode_list_zhipu_quota_limit_dto(dynamic raw);

  @protected
  List<ZhipuToolUsageDetailDto> dco_decode_list_zhipu_tool_usage_detail_dto(
    dynamic raw,
  );

  @protected
  McpServerInput dco_decode_mcp_server_input(dynamic raw);

  @protected
  McpSettingsInput dco_decode_mcp_settings_input(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  BridgeAgentStatus? dco_decode_opt_box_autoadd_bridge_agent_status(
    dynamic raw,
  );

  @protected
  BridgeBudgetLimitKind? dco_decode_opt_box_autoadd_bridge_budget_limit_kind(
    dynamic raw,
  );

  @protected
  BridgeBudgetUsage? dco_decode_opt_box_autoadd_bridge_budget_usage(
    dynamic raw,
  );

  @protected
  BridgeInteractionResolution?
  dco_decode_opt_box_autoadd_bridge_interaction_resolution(dynamic raw);

  @protected
  BridgeModelPricing? dco_decode_opt_box_autoadd_bridge_model_pricing(
    dynamic raw,
  );

  @protected
  BridgeModelReasoningDescriptor?
  dco_decode_opt_box_autoadd_bridge_model_reasoning_descriptor(dynamic raw);

  @protected
  BridgeSessionMcpHealthSnapshot?
  dco_decode_opt_box_autoadd_bridge_session_mcp_health_snapshot(dynamic raw);

  @protected
  BridgeSessionOwnerSnapshot?
  dco_decode_opt_box_autoadd_bridge_session_owner_snapshot(dynamic raw);

  @protected
  BridgeSessionRuntimeSnapshot?
  dco_decode_opt_box_autoadd_bridge_session_runtime_snapshot(dynamic raw);

  @protected
  BridgeSessionRuntimeUsage?
  dco_decode_opt_box_autoadd_bridge_session_runtime_usage(dynamic raw);

  @protected
  BridgeSessionTurn? dco_decode_opt_box_autoadd_bridge_session_turn(
    dynamic raw,
  );

  @protected
  BridgeTaskRuntimeDto? dco_decode_opt_box_autoadd_bridge_task_runtime_dto(
    dynamic raw,
  );

  @protected
  BridgeTokenUsageSnapshot?
  dco_decode_opt_box_autoadd_bridge_token_usage_snapshot(dynamic raw);

  @protected
  DeepSeekBalanceDto? dco_decode_opt_box_autoadd_deep_seek_balance_dto(
    dynamic raw,
  );

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ZhipuCodingPlanUsageDto?
  dco_decode_opt_box_autoadd_zhipu_coding_plan_usage_dto(dynamic raw);

  @protected
  BridgeTaskRuntimeDto? dco_decode_opt_box_bridge_task_runtime_dto(dynamic raw);

  @protected
  List<BridgeUserQuestionOption>?
  dco_decode_opt_list_bridge_user_question_option(dynamic raw);

  @protected
  List<BridgeUserQuestionOptionDto>?
  dco_decode_opt_list_bridge_user_question_option_dto(dynamic raw);

  @protected
  ProjectDto dco_decode_project_dto(dynamic raw);

  @protected
  ProviderInput dco_decode_provider_input(dynamic raw);

  @protected
  ProviderModelInput dco_decode_provider_model_input(dynamic raw);

  @protected
  ProviderSecretInput dco_decode_provider_secret_input(dynamic raw);

  @protected
  ProviderSettingsInput dco_decode_provider_settings_input(dynamic raw);

  @protected
  ProviderUsageDto dco_decode_provider_usage_dto(dynamic raw);

  @protected
  ProviderUsagesResponse dco_decode_provider_usages_response(dynamic raw);

  @protected
  ResolveInteractionResponse dco_decode_resolve_interaction_response(
    dynamic raw,
  );

  @protected
  RoleInput dco_decode_role_input(dynamic raw);

  @protected
  RuntimeSnapshot dco_decode_runtime_snapshot(dynamic raw);

  @protected
  SessionDto dco_decode_session_dto(dynamic raw);

  @protected
  SkillSummaryDto dco_decode_skill_summary_dto(dynamic raw);

  @protected
  SkillsResponse dco_decode_skills_response(dynamic raw);

  @protected
  SkillsSettingsInput dco_decode_skills_settings_input(dynamic raw);

  @protected
  StopPromptResponse dco_decode_stop_prompt_response(dynamic raw);

  @protected
  SubmitPromptResponse dco_decode_submit_prompt_response(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WebSearchSettingsInput dco_decode_web_search_settings_input(dynamic raw);

  @protected
  ZhipuCodingPlanUsageDto dco_decode_zhipu_coding_plan_usage_dto(dynamic raw);

  @protected
  ZhipuQuotaLimitDto dco_decode_zhipu_quota_limit_dto(dynamic raw);

  @protected
  ZhipuToolUsageDetailDto dco_decode_zhipu_tool_usage_detail_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BridgeEventSubscription
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStudioUpdateOperation
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEventSubscription
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStudioUpdateOperation
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    SseDeserializer deserializer,
  );

  @protected
  BridgeEventSubscription
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStudioUpdateOperation
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeProductStreamEnvelope>
  sse_decode_StreamSink_bridge_product_stream_envelope_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeSessionStreamEnvelope>
  sse_decode_StreamSink_bridge_session_stream_envelope_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BridgeStudioUpdateEventDto>
  sse_decode_StreamSink_bridge_studio_update_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BridgeAgentStatus sse_decode_box_autoadd_bridge_agent_status(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBudgetLimitKind sse_decode_box_autoadd_bridge_budget_limit_kind(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBudgetUsage sse_decode_box_autoadd_bridge_budget_usage(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError sse_decode_box_autoadd_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeInteractionRequest sse_decode_box_autoadd_bridge_interaction_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionResolution
  sse_decode_box_autoadd_bridge_interaction_resolution(
    SseDeserializer deserializer,
  );

  @protected
  BridgeLspHealthDto sse_decode_box_autoadd_bridge_lsp_health_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMcpHealthDto sse_decode_box_autoadd_bridge_mcp_health_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeModelPricing sse_decode_box_autoadd_bridge_model_pricing(
    SseDeserializer deserializer,
  );

  @protected
  BridgeModelReasoningDescriptor
  sse_decode_box_autoadd_bridge_model_reasoning_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlanLifecycleEvent sse_decode_box_autoadd_bridge_plan_lifecycle_event(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProductEventEnvelope
  sse_decode_box_autoadd_bridge_product_event_envelope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionAgentPart sse_decode_box_autoadd_bridge_session_agent_part(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionAgentSnapshot
  sse_decode_box_autoadd_bridge_session_agent_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionContextCompaction
  sse_decode_box_autoadd_bridge_session_context_compaction(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionEventEnvelope
  sse_decode_box_autoadd_bridge_session_event_envelope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionMcpHealthSnapshot
  sse_decode_box_autoadd_bridge_session_mcp_health_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionMessage sse_decode_box_autoadd_bridge_session_message(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionOwnerSnapshot
  sse_decode_box_autoadd_bridge_session_owner_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionPart sse_decode_box_autoadd_bridge_session_part(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionPartDelta sse_decode_box_autoadd_bridge_session_part_delta(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionResyncReason sse_decode_box_autoadd_bridge_session_resync_reason(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionRuntimeSnapshot
  sse_decode_box_autoadd_bridge_session_runtime_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionRuntimeUsage sse_decode_box_autoadd_bridge_session_runtime_usage(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionTimelineEvent
  sse_decode_box_autoadd_bridge_session_timeline_event(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionToolPart sse_decode_box_autoadd_bridge_session_tool_part(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionTurn sse_decode_box_autoadd_bridge_session_turn(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionViewSnapshot sse_decode_box_autoadd_bridge_session_view_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSkillActivation sse_decode_box_autoadd_bridge_skill_activation(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStudioUpdateDto sse_decode_box_autoadd_bridge_studio_update_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTaskRuntimeDto sse_decode_box_autoadd_bridge_task_runtime_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTodoListSnapshot sse_decode_box_autoadd_bridge_todo_list_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTokenUsageSnapshot sse_decode_box_autoadd_bridge_token_usage_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  DeepSeekBalanceDto sse_decode_box_autoadd_deep_seek_balance_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GeneralSettingsInput sse_decode_box_autoadd_general_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  InstructionsSettingsInput sse_decode_box_autoadd_instructions_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  McpSettingsInput sse_decode_box_autoadd_mcp_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  ProviderSettingsInput sse_decode_box_autoadd_provider_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  SkillsSettingsInput sse_decode_box_autoadd_skills_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WebSearchSettingsInput sse_decode_box_autoadd_web_search_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  ZhipuCodingPlanUsageDto sse_decode_box_autoadd_zhipu_coding_plan_usage_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionStreamFrame sse_decode_box_bridge_session_stream_frame(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTaskRuntimeDto sse_decode_box_bridge_task_runtime_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeActiveTurn sse_decode_bridge_active_turn(SseDeserializer deserializer);

  @protected
  BridgeAgentStatus sse_decode_bridge_agent_status(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBudgetLimitKind sse_decode_bridge_budget_limit_kind(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBudgetUsage sse_decode_bridge_budget_usage(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeErrorCode sse_decode_bridge_error_code(SseDeserializer deserializer);

  @protected
  BridgeErrorSeverity sse_decode_bridge_error_severity(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionChangedDto sse_decode_bridge_interaction_changed_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionKind sse_decode_bridge_interaction_kind(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionPayload sse_decode_bridge_interaction_payload(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionPayloadDto sse_decode_bridge_interaction_payload_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionRequest sse_decode_bridge_interaction_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionResolution sse_decode_bridge_interaction_resolution(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionScope sse_decode_bridge_interaction_scope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionStatus sse_decode_bridge_interaction_status(
    SseDeserializer deserializer,
  );

  @protected
  BridgeLspHealthDto sse_decode_bridge_lsp_health_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMcpHealthDto sse_decode_bridge_mcp_health_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMcpServerDto sse_decode_bridge_mcp_server_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeModelCapabilities sse_decode_bridge_model_capabilities(
    SseDeserializer deserializer,
  );

  @protected
  BridgeModelCatalogDescriptor sse_decode_bridge_model_catalog_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgeModelDescriptor sse_decode_bridge_model_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgeModelPricing sse_decode_bridge_model_pricing(
    SseDeserializer deserializer,
  );

  @protected
  BridgeModelReasoningDescriptor sse_decode_bridge_model_reasoning_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlanConfirmationResolution
  sse_decode_bridge_plan_confirmation_resolution(SseDeserializer deserializer);

  @protected
  BridgePlanLifecycleEvent sse_decode_bridge_plan_lifecycle_event(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlanLifecycleState sse_decode_bridge_plan_lifecycle_state(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProductEventEnvelope sse_decode_bridge_product_event_envelope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProductEventPayload sse_decode_bridge_product_event_payload(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProductStreamEnvelope sse_decode_bridge_product_stream_envelope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProviderCatalogSnapshot sse_decode_bridge_provider_catalog_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProviderConnectionModeDescriptor
  sse_decode_bridge_provider_connection_mode_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProviderPresetDescriptor sse_decode_bridge_provider_preset_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProviderServiceCapabilitiesDescriptor
  sse_decode_bridge_provider_service_capabilities_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProviderTransportDescriptor
  sse_decode_bridge_provider_transport_descriptor(SseDeserializer deserializer);

  @protected
  BridgeRecoveryCleanupPreviewDto
  sse_decode_bridge_recovery_cleanup_preview_dto(SseDeserializer deserializer);

  @protected
  BridgeRecoveryCleanupResourceDto
  sse_decode_bridge_recovery_cleanup_resource_dto(SseDeserializer deserializer);

  @protected
  BridgeRecoveryIssueAction sse_decode_bridge_recovery_issue_action(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRecoveryIssueCategory sse_decode_bridge_recovery_issue_category(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRecoveryIssueScope sse_decode_bridge_recovery_issue_scope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRecoveryResourcePresence sse_decode_bridge_recovery_resource_presence(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRuntimeCostAmount sse_decode_bridge_runtime_cost_amount(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRuntimeStatus sse_decode_bridge_runtime_status(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionAgentPart sse_decode_bridge_session_agent_part(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionAgentSnapshot sse_decode_bridge_session_agent_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionAttachment sse_decode_bridge_session_attachment(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionContextCompaction sse_decode_bridge_session_context_compaction(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionEventEnvelope sse_decode_bridge_session_event_envelope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionEventKind sse_decode_bridge_session_event_kind(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionEventPosition sse_decode_bridge_session_event_position(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionMcpAvailabilityDescriptor
  sse_decode_bridge_session_mcp_availability_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionMcpHealthSnapshot sse_decode_bridge_session_mcp_health_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionMcpServerDescriptor
  sse_decode_bridge_session_mcp_server_descriptor(SseDeserializer deserializer);

  @protected
  BridgeSessionMessage sse_decode_bridge_session_message(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionMessageRole sse_decode_bridge_session_message_role(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionMessageStatus sse_decode_bridge_session_message_status(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionOwnerSnapshot sse_decode_bridge_session_owner_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionPart sse_decode_bridge_session_part(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionPartContent sse_decode_bridge_session_part_content(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionPartDelta sse_decode_bridge_session_part_delta(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionPartDeltaField sse_decode_bridge_session_part_delta_field(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionPartStatus sse_decode_bridge_session_part_status(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionResyncReason sse_decode_bridge_session_resync_reason(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionRuntimeSnapshot sse_decode_bridge_session_runtime_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionRuntimeUsage sse_decode_bridge_session_runtime_usage(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionStreamEnvelope sse_decode_bridge_session_stream_envelope(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionStreamFrame sse_decode_bridge_session_stream_frame(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionTextChannel sse_decode_bridge_session_text_channel(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionTimelineEvent sse_decode_bridge_session_timeline_event(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionTimelineEventKind sse_decode_bridge_session_timeline_event_kind(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionToolPart sse_decode_bridge_session_tool_part(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionTurn sse_decode_bridge_session_turn(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionTurnActivity sse_decode_bridge_session_turn_activity(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionTurnState sse_decode_bridge_session_turn_state(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionViewSnapshot sse_decode_bridge_session_view_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSkillActivation sse_decode_bridge_skill_activation(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStudioRecoveryIssueDto sse_decode_bridge_studio_recovery_issue_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStudioSnapshotResponse sse_decode_bridge_studio_snapshot_response(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStudioUpdateCheckDto sse_decode_bridge_studio_update_check_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStudioUpdateDto sse_decode_bridge_studio_update_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStudioUpdateEventDto sse_decode_bridge_studio_update_event_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSubAgentActivityKind sse_decode_bridge_sub_agent_activity_kind(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTaskAgentDto sse_decode_bridge_task_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTaskMergeDto sse_decode_bridge_task_merge_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTaskReviewDto sse_decode_bridge_task_review_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTaskRuntimeDto sse_decode_bridge_task_runtime_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTaskWorkUnitDto sse_decode_bridge_task_work_unit_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTodoItem sse_decode_bridge_todo_item(SseDeserializer deserializer);

  @protected
  BridgeTodoListSnapshot sse_decode_bridge_todo_list_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTodoStatus sse_decode_bridge_todo_status(SseDeserializer deserializer);

  @protected
  BridgeTokenUsageSnapshot sse_decode_bridge_token_usage_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeToolApprovalResolution sse_decode_bridge_tool_approval_resolution(
    SseDeserializer deserializer,
  );

  @protected
  BridgeUserInputAnswer sse_decode_bridge_user_input_answer(
    SseDeserializer deserializer,
  );

  @protected
  BridgeUserQuestion sse_decode_bridge_user_question(
    SseDeserializer deserializer,
  );

  @protected
  BridgeUserQuestionDto sse_decode_bridge_user_question_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeUserQuestionOption sse_decode_bridge_user_question_option(
    SseDeserializer deserializer,
  );

  @protected
  BridgeUserQuestionOptionDto sse_decode_bridge_user_question_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeWebSearchProviderCapabilitiesDescriptor
  sse_decode_bridge_web_search_provider_capabilities_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgeWebSearchSettingsDto sse_decode_bridge_web_search_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  DeepSeekBalanceDto sse_decode_deep_seek_balance_dto(
    SseDeserializer deserializer,
  );

  @protected
  DeepSeekBalanceInfoDto sse_decode_deep_seek_balance_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GeneralSettingsInput sse_decode_general_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InstructionsSettingsInput sse_decode_instructions_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BridgeActiveTurn> sse_decode_list_bridge_active_turn(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeInteractionRequest> sse_decode_list_bridge_interaction_request(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeMcpServerDto> sse_decode_list_bridge_mcp_server_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeModelCatalogDescriptor>
  sse_decode_list_bridge_model_catalog_descriptor(SseDeserializer deserializer);

  @protected
  List<BridgeModelDescriptor> sse_decode_list_bridge_model_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgePlanLifecycleEvent> sse_decode_list_bridge_plan_lifecycle_event(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeProviderConnectionModeDescriptor>
  sse_decode_list_bridge_provider_connection_mode_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeProviderPresetDescriptor>
  sse_decode_list_bridge_provider_preset_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeRecoveryCleanupResourceDto>
  sse_decode_list_bridge_recovery_cleanup_resource_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeRecoveryIssueAction> sse_decode_list_bridge_recovery_issue_action(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeRuntimeCostAmount> sse_decode_list_bridge_runtime_cost_amount(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeSessionAgentSnapshot>
  sse_decode_list_bridge_session_agent_snapshot(SseDeserializer deserializer);

  @protected
  List<BridgeSessionAttachment> sse_decode_list_bridge_session_attachment(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeSessionMcpAvailabilityDescriptor>
  sse_decode_list_bridge_session_mcp_availability_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeSessionMessage> sse_decode_list_bridge_session_message(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeSessionPart> sse_decode_list_bridge_session_part(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeSessionTimelineEvent>
  sse_decode_list_bridge_session_timeline_event(SseDeserializer deserializer);

  @protected
  List<BridgeSkillActivation> sse_decode_list_bridge_skill_activation(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeStudioRecoveryIssueDto>
  sse_decode_list_bridge_studio_recovery_issue_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeTaskAgentDto> sse_decode_list_bridge_task_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeTaskMergeDto> sse_decode_list_bridge_task_merge_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeTaskReviewDto> sse_decode_list_bridge_task_review_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeTaskWorkUnitDto> sse_decode_list_bridge_task_work_unit_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeTodoItem> sse_decode_list_bridge_todo_item(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeUserInputAnswer> sse_decode_list_bridge_user_input_answer(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeUserQuestion> sse_decode_list_bridge_user_question(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeUserQuestionDto> sse_decode_list_bridge_user_question_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeUserQuestionOption> sse_decode_list_bridge_user_question_option(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeUserQuestionOptionDto>
  sse_decode_list_bridge_user_question_option_dto(SseDeserializer deserializer);

  @protected
  List<DeepSeekBalanceInfoDto> sse_decode_list_deep_seek_balance_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<McpServerInput> sse_decode_list_mcp_server_input(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectDto> sse_decode_list_project_dto(SseDeserializer deserializer);

  @protected
  List<ProviderInput> sse_decode_list_provider_input(
    SseDeserializer deserializer,
  );

  @protected
  List<ProviderModelInput> sse_decode_list_provider_model_input(
    SseDeserializer deserializer,
  );

  @protected
  List<ProviderUsageDto> sse_decode_list_provider_usage_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<RoleInput> sse_decode_list_role_input(SseDeserializer deserializer);

  @protected
  List<SessionDto> sse_decode_list_session_dto(SseDeserializer deserializer);

  @protected
  List<SkillSummaryDto> sse_decode_list_skill_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ZhipuQuotaLimitDto> sse_decode_list_zhipu_quota_limit_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ZhipuToolUsageDetailDto> sse_decode_list_zhipu_tool_usage_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  McpServerInput sse_decode_mcp_server_input(SseDeserializer deserializer);

  @protected
  McpSettingsInput sse_decode_mcp_settings_input(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BridgeAgentStatus? sse_decode_opt_box_autoadd_bridge_agent_status(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBudgetLimitKind? sse_decode_opt_box_autoadd_bridge_budget_limit_kind(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBudgetUsage? sse_decode_opt_box_autoadd_bridge_budget_usage(
    SseDeserializer deserializer,
  );

  @protected
  BridgeInteractionResolution?
  sse_decode_opt_box_autoadd_bridge_interaction_resolution(
    SseDeserializer deserializer,
  );

  @protected
  BridgeModelPricing? sse_decode_opt_box_autoadd_bridge_model_pricing(
    SseDeserializer deserializer,
  );

  @protected
  BridgeModelReasoningDescriptor?
  sse_decode_opt_box_autoadd_bridge_model_reasoning_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionMcpHealthSnapshot?
  sse_decode_opt_box_autoadd_bridge_session_mcp_health_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionOwnerSnapshot?
  sse_decode_opt_box_autoadd_bridge_session_owner_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionRuntimeSnapshot?
  sse_decode_opt_box_autoadd_bridge_session_runtime_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionRuntimeUsage?
  sse_decode_opt_box_autoadd_bridge_session_runtime_usage(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionTurn? sse_decode_opt_box_autoadd_bridge_session_turn(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTaskRuntimeDto? sse_decode_opt_box_autoadd_bridge_task_runtime_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTokenUsageSnapshot?
  sse_decode_opt_box_autoadd_bridge_token_usage_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  DeepSeekBalanceDto? sse_decode_opt_box_autoadd_deep_seek_balance_dto(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ZhipuCodingPlanUsageDto?
  sse_decode_opt_box_autoadd_zhipu_coding_plan_usage_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTaskRuntimeDto? sse_decode_opt_box_bridge_task_runtime_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeUserQuestionOption>?
  sse_decode_opt_list_bridge_user_question_option(SseDeserializer deserializer);

  @protected
  List<BridgeUserQuestionOptionDto>?
  sse_decode_opt_list_bridge_user_question_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProjectDto sse_decode_project_dto(SseDeserializer deserializer);

  @protected
  ProviderInput sse_decode_provider_input(SseDeserializer deserializer);

  @protected
  ProviderModelInput sse_decode_provider_model_input(
    SseDeserializer deserializer,
  );

  @protected
  ProviderSecretInput sse_decode_provider_secret_input(
    SseDeserializer deserializer,
  );

  @protected
  ProviderSettingsInput sse_decode_provider_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  ProviderUsageDto sse_decode_provider_usage_dto(SseDeserializer deserializer);

  @protected
  ProviderUsagesResponse sse_decode_provider_usages_response(
    SseDeserializer deserializer,
  );

  @protected
  ResolveInteractionResponse sse_decode_resolve_interaction_response(
    SseDeserializer deserializer,
  );

  @protected
  RoleInput sse_decode_role_input(SseDeserializer deserializer);

  @protected
  RuntimeSnapshot sse_decode_runtime_snapshot(SseDeserializer deserializer);

  @protected
  SessionDto sse_decode_session_dto(SseDeserializer deserializer);

  @protected
  SkillSummaryDto sse_decode_skill_summary_dto(SseDeserializer deserializer);

  @protected
  SkillsResponse sse_decode_skills_response(SseDeserializer deserializer);

  @protected
  SkillsSettingsInput sse_decode_skills_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  StopPromptResponse sse_decode_stop_prompt_response(
    SseDeserializer deserializer,
  );

  @protected
  SubmitPromptResponse sse_decode_submit_prompt_response(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WebSearchSettingsInput sse_decode_web_search_settings_input(
    SseDeserializer deserializer,
  );

  @protected
  ZhipuCodingPlanUsageDto sse_decode_zhipu_coding_plan_usage_dto(
    SseDeserializer deserializer,
  );

  @protected
  ZhipuQuotaLimitDto sse_decode_zhipu_quota_limit_dto(
    SseDeserializer deserializer,
  );

  @protected
  ZhipuToolUsageDetailDto sse_decode_zhipu_tool_usage_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    BridgeEventSubscription self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    BridgeStudioUpdateOperation self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    BridgeEventSubscription self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    BridgeStudioUpdateOperation self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    BridgeEventSubscription self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    BridgeStudioUpdateOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_product_stream_envelope_Sse(
    RustStreamSink<BridgeProductStreamEnvelope> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_session_stream_envelope_Sse(
    RustStreamSink<BridgeSessionStreamEnvelope> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bridge_studio_update_event_dto_Sse(
    RustStreamSink<BridgeStudioUpdateEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_agent_status(
    BridgeAgentStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_budget_limit_kind(
    BridgeBudgetLimitKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_budget_usage(
    BridgeBudgetUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_error(
    BridgeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_interaction_request(
    BridgeInteractionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_interaction_resolution(
    BridgeInteractionResolution self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_lsp_health_dto(
    BridgeLspHealthDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_mcp_health_dto(
    BridgeMcpHealthDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_model_pricing(
    BridgeModelPricing self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_model_reasoning_descriptor(
    BridgeModelReasoningDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_plan_lifecycle_event(
    BridgePlanLifecycleEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_product_event_envelope(
    BridgeProductEventEnvelope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_agent_part(
    BridgeSessionAgentPart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_agent_snapshot(
    BridgeSessionAgentSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_context_compaction(
    BridgeSessionContextCompaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_event_envelope(
    BridgeSessionEventEnvelope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_mcp_health_snapshot(
    BridgeSessionMcpHealthSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_message(
    BridgeSessionMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_owner_snapshot(
    BridgeSessionOwnerSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_part(
    BridgeSessionPart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_part_delta(
    BridgeSessionPartDelta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_resync_reason(
    BridgeSessionResyncReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_runtime_snapshot(
    BridgeSessionRuntimeSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_runtime_usage(
    BridgeSessionRuntimeUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_timeline_event(
    BridgeSessionTimelineEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_tool_part(
    BridgeSessionToolPart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_turn(
    BridgeSessionTurn self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_session_view_snapshot(
    BridgeSessionViewSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_skill_activation(
    BridgeSkillActivation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_studio_update_dto(
    BridgeStudioUpdateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_task_runtime_dto(
    BridgeTaskRuntimeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_todo_list_snapshot(
    BridgeTodoListSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_token_usage_snapshot(
    BridgeTokenUsageSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_deep_seek_balance_dto(
    DeepSeekBalanceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_general_settings_input(
    GeneralSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_instructions_settings_input(
    InstructionsSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mcp_settings_input(
    McpSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_provider_settings_input(
    ProviderSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_skills_settings_input(
    SkillsSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_web_search_settings_input(
    WebSearchSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_zhipu_coding_plan_usage_dto(
    ZhipuCodingPlanUsageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_bridge_session_stream_frame(
    BridgeSessionStreamFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_bridge_task_runtime_dto(
    BridgeTaskRuntimeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_active_turn(
    BridgeActiveTurn self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_agent_status(
    BridgeAgentStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_budget_limit_kind(
    BridgeBudgetLimitKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_budget_usage(
    BridgeBudgetUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error_code(
    BridgeErrorCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error_severity(
    BridgeErrorSeverity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_interaction_changed_dto(
    BridgeInteractionChangedDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_interaction_kind(
    BridgeInteractionKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_interaction_payload(
    BridgeInteractionPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_interaction_payload_dto(
    BridgeInteractionPayloadDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_interaction_request(
    BridgeInteractionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_interaction_resolution(
    BridgeInteractionResolution self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_interaction_scope(
    BridgeInteractionScope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_interaction_status(
    BridgeInteractionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_lsp_health_dto(
    BridgeLspHealthDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_mcp_health_dto(
    BridgeMcpHealthDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_mcp_server_dto(
    BridgeMcpServerDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_model_capabilities(
    BridgeModelCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_model_catalog_descriptor(
    BridgeModelCatalogDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_model_descriptor(
    BridgeModelDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_model_pricing(
    BridgeModelPricing self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_model_reasoning_descriptor(
    BridgeModelReasoningDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_plan_confirmation_resolution(
    BridgePlanConfirmationResolution self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_plan_lifecycle_event(
    BridgePlanLifecycleEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_plan_lifecycle_state(
    BridgePlanLifecycleState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_product_event_envelope(
    BridgeProductEventEnvelope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_product_event_payload(
    BridgeProductEventPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_product_stream_envelope(
    BridgeProductStreamEnvelope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_provider_catalog_snapshot(
    BridgeProviderCatalogSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_provider_connection_mode_descriptor(
    BridgeProviderConnectionModeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_provider_preset_descriptor(
    BridgeProviderPresetDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_provider_service_capabilities_descriptor(
    BridgeProviderServiceCapabilitiesDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_provider_transport_descriptor(
    BridgeProviderTransportDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_recovery_cleanup_preview_dto(
    BridgeRecoveryCleanupPreviewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_recovery_cleanup_resource_dto(
    BridgeRecoveryCleanupResourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_recovery_issue_action(
    BridgeRecoveryIssueAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_recovery_issue_category(
    BridgeRecoveryIssueCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_recovery_issue_scope(
    BridgeRecoveryIssueScope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_recovery_resource_presence(
    BridgeRecoveryResourcePresence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_runtime_cost_amount(
    BridgeRuntimeCostAmount self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_runtime_status(
    BridgeRuntimeStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_agent_part(
    BridgeSessionAgentPart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_agent_snapshot(
    BridgeSessionAgentSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_attachment(
    BridgeSessionAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_context_compaction(
    BridgeSessionContextCompaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_event_envelope(
    BridgeSessionEventEnvelope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_event_kind(
    BridgeSessionEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_event_position(
    BridgeSessionEventPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_mcp_availability_descriptor(
    BridgeSessionMcpAvailabilityDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_mcp_health_snapshot(
    BridgeSessionMcpHealthSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_mcp_server_descriptor(
    BridgeSessionMcpServerDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_message(
    BridgeSessionMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_message_role(
    BridgeSessionMessageRole self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_message_status(
    BridgeSessionMessageStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_owner_snapshot(
    BridgeSessionOwnerSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_part(
    BridgeSessionPart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_part_content(
    BridgeSessionPartContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_part_delta(
    BridgeSessionPartDelta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_part_delta_field(
    BridgeSessionPartDeltaField self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_part_status(
    BridgeSessionPartStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_resync_reason(
    BridgeSessionResyncReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_runtime_snapshot(
    BridgeSessionRuntimeSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_runtime_usage(
    BridgeSessionRuntimeUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_stream_envelope(
    BridgeSessionStreamEnvelope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_stream_frame(
    BridgeSessionStreamFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_text_channel(
    BridgeSessionTextChannel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_timeline_event(
    BridgeSessionTimelineEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_timeline_event_kind(
    BridgeSessionTimelineEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_tool_part(
    BridgeSessionToolPart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_turn(
    BridgeSessionTurn self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_turn_activity(
    BridgeSessionTurnActivity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_turn_state(
    BridgeSessionTurnState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_view_snapshot(
    BridgeSessionViewSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_skill_activation(
    BridgeSkillActivation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_studio_recovery_issue_dto(
    BridgeStudioRecoveryIssueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_studio_snapshot_response(
    BridgeStudioSnapshotResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_studio_update_check_dto(
    BridgeStudioUpdateCheckDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_studio_update_dto(
    BridgeStudioUpdateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_studio_update_event_dto(
    BridgeStudioUpdateEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_sub_agent_activity_kind(
    BridgeSubAgentActivityKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_task_agent_dto(
    BridgeTaskAgentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_task_merge_dto(
    BridgeTaskMergeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_task_review_dto(
    BridgeTaskReviewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_task_runtime_dto(
    BridgeTaskRuntimeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_task_work_unit_dto(
    BridgeTaskWorkUnitDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_todo_item(
    BridgeTodoItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_todo_list_snapshot(
    BridgeTodoListSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_todo_status(
    BridgeTodoStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_token_usage_snapshot(
    BridgeTokenUsageSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_tool_approval_resolution(
    BridgeToolApprovalResolution self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_user_input_answer(
    BridgeUserInputAnswer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_user_question(
    BridgeUserQuestion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_user_question_dto(
    BridgeUserQuestionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_user_question_option(
    BridgeUserQuestionOption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_user_question_option_dto(
    BridgeUserQuestionOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_web_search_provider_capabilities_descriptor(
    BridgeWebSearchProviderCapabilitiesDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_web_search_settings_dto(
    BridgeWebSearchSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_deep_seek_balance_dto(
    DeepSeekBalanceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_deep_seek_balance_info_dto(
    DeepSeekBalanceInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_general_settings_input(
    GeneralSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_instructions_settings_input(
    InstructionsSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_active_turn(
    List<BridgeActiveTurn> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_interaction_request(
    List<BridgeInteractionRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_mcp_server_dto(
    List<BridgeMcpServerDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_model_catalog_descriptor(
    List<BridgeModelCatalogDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_model_descriptor(
    List<BridgeModelDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_plan_lifecycle_event(
    List<BridgePlanLifecycleEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_provider_connection_mode_descriptor(
    List<BridgeProviderConnectionModeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_provider_preset_descriptor(
    List<BridgeProviderPresetDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_recovery_cleanup_resource_dto(
    List<BridgeRecoveryCleanupResourceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_recovery_issue_action(
    List<BridgeRecoveryIssueAction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_runtime_cost_amount(
    List<BridgeRuntimeCostAmount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_session_agent_snapshot(
    List<BridgeSessionAgentSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_session_attachment(
    List<BridgeSessionAttachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_session_mcp_availability_descriptor(
    List<BridgeSessionMcpAvailabilityDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_session_message(
    List<BridgeSessionMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_session_part(
    List<BridgeSessionPart> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_session_timeline_event(
    List<BridgeSessionTimelineEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_skill_activation(
    List<BridgeSkillActivation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_studio_recovery_issue_dto(
    List<BridgeStudioRecoveryIssueDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_task_agent_dto(
    List<BridgeTaskAgentDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_task_merge_dto(
    List<BridgeTaskMergeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_task_review_dto(
    List<BridgeTaskReviewDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_task_work_unit_dto(
    List<BridgeTaskWorkUnitDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_todo_item(
    List<BridgeTodoItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_user_input_answer(
    List<BridgeUserInputAnswer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_user_question(
    List<BridgeUserQuestion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_user_question_dto(
    List<BridgeUserQuestionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_user_question_option(
    List<BridgeUserQuestionOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_user_question_option_dto(
    List<BridgeUserQuestionOptionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_deep_seek_balance_info_dto(
    List<DeepSeekBalanceInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mcp_server_input(
    List<McpServerInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_dto(
    List<ProjectDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_input(
    List<ProviderInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_model_input(
    List<ProviderModelInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_usage_dto(
    List<ProviderUsageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_role_input(
    List<RoleInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_dto(
    List<SessionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_skill_summary_dto(
    List<SkillSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_zhipu_quota_limit_dto(
    List<ZhipuQuotaLimitDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_zhipu_tool_usage_detail_dto(
    List<ZhipuToolUsageDetailDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mcp_server_input(
    McpServerInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mcp_settings_input(
    McpSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_agent_status(
    BridgeAgentStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_budget_limit_kind(
    BridgeBudgetLimitKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_budget_usage(
    BridgeBudgetUsage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_interaction_resolution(
    BridgeInteractionResolution? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_model_pricing(
    BridgeModelPricing? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_model_reasoning_descriptor(
    BridgeModelReasoningDescriptor? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_session_mcp_health_snapshot(
    BridgeSessionMcpHealthSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_session_owner_snapshot(
    BridgeSessionOwnerSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_session_runtime_snapshot(
    BridgeSessionRuntimeSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_session_runtime_usage(
    BridgeSessionRuntimeUsage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_session_turn(
    BridgeSessionTurn? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_task_runtime_dto(
    BridgeTaskRuntimeDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_token_usage_snapshot(
    BridgeTokenUsageSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_deep_seek_balance_dto(
    DeepSeekBalanceDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_zhipu_coding_plan_usage_dto(
    ZhipuCodingPlanUsageDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_bridge_task_runtime_dto(
    BridgeTaskRuntimeDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_bridge_user_question_option(
    List<BridgeUserQuestionOption>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_bridge_user_question_option_dto(
    List<BridgeUserQuestionOptionDto>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_dto(ProjectDto self, SseSerializer serializer);

  @protected
  void sse_encode_provider_input(ProviderInput self, SseSerializer serializer);

  @protected
  void sse_encode_provider_model_input(
    ProviderModelInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_secret_input(
    ProviderSecretInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_settings_input(
    ProviderSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_usage_dto(
    ProviderUsageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_usages_response(
    ProviderUsagesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resolve_interaction_response(
    ResolveInteractionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_role_input(RoleInput self, SseSerializer serializer);

  @protected
  void sse_encode_runtime_snapshot(
    RuntimeSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_dto(SessionDto self, SseSerializer serializer);

  @protected
  void sse_encode_skill_summary_dto(
    SkillSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_skills_response(
    SkillsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_skills_settings_input(
    SkillsSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stop_prompt_response(
    StopPromptResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_submit_prompt_response(
    SubmitPromptResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_web_search_settings_input(
    WebSearchSettingsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_zhipu_coding_plan_usage_dto(
    ZhipuCodingPlanUsageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_zhipu_quota_limit_dto(
    ZhipuQuotaLimitDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_zhipu_tool_usage_detail_dto(
    ZhipuToolUsageDetailDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscriptionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pure_studio_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscriptionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscriptionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pure_studio_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscription =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeEventSubscriptionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pure_studio_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperationPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_pure_studio_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperation =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeStudioUpdateOperationPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
